@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for acs-engine-autoscaler:2.2.2

'There is one referenced Helm Chart
artifact "acs-engine-autoscaler:2.2.2\n====\n\tacs-engine-autoscaler\n====\n\t2.2.2\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: \n====\n\tKeywords: " as acs_engine_autoscaler_2_2_2 #Lavender

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/03/16 17:12:03 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
