@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for aerospike:0.3.2

'There is one referenced Helm Chart
artifact "aerospike:0.3.2\n====\n\taerospike\n====\n\t0.3.2\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: kavehmz, okgolove\n====\n\tKeywords: aerospike\nbig-data" as aerospike_0_3_2 #AntiqueWhite

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\taerospike/aerospike-server\n====\n\t4.5.0.5" as aerospike_aerospike_server_4_5_0_5 #FloralWhite

'Chart Dependencies
aerospike_0_3_2--[#orange]-|>aerospike_aerospike_server_4_5_0_5

center footer Generated on 2020/03/16 17:12:08 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
