@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for airflow:7.13.2

'There are 3 referenced Helm Charts
artifact "redis:10.5.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_10_5_7 #LightSeaGreen
artifact "airflow:7.13.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tgsemet\n\t\tthesuperzapper\n====\n\tKeywords: \n\t\tworkflow\n\t\tdag\n\t\tairflow" as airflow_7_13_2 #FloralWhite
artifact "postgresql:8.6.4\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_8_6_4 #LightSteelBlue

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/redis:5.0.7-debian-10-r32\n====\n5.0.7-debian-10-r32" as docker_io_bitnami_redis_5_0_7_debian_10_r32 #Azure
usecase "Image\n====\nDocker Hub\n====\napache/airflow\n====\n1.10.12-python3.6" as apache_airflow_1_10_12_python3_6 #LightSteelBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:11.7.0-debian-10-r9\n====\n11.7.0-debian-10-r9" as docker_io_bitnami_postgresql_11_7_0_debian_10_r9 #DarkSalmon

'Chart Dependencies
airflow_7_13_2--[#green]-|>redis_10_5_7
airflow_7_13_2--[#green]-|>postgresql_8_6_4
redis_10_5_7--[#orange]-|>docker_io_bitnami_redis_5_0_7_debian_10_r32
airflow_7_13_2--[#orange]-|>apache_airflow_1_10_12_python3_6
postgresql_8_6_4--[#orange]-|>docker_io_bitnami_postgresql_11_7_0_debian_10_r9

center footer Generated on 2022/05/13 07:01:53 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
