@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for artifactory-ha:0.4.1

'There are 2 referenced Helm Charts
artifact "artifactory-ha:0.4.1\n====\n\tartifactory-ha\n====\n\t0.4.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: \n====\n\tKeywords: artifactory\njfrog" as artifactory_ha_0_4_1 #FloralWhite
artifact "postgresql:0.8.7\n====\n\tpostgresql\n====\n\t0.8.7\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: swordbeta, databus23\n====\n\tKeywords: postgresql\npostgres\ndatabase\nsql" as postgresql_0_8_7 #LightSteelBlue

'There are 3 referenced Docker Images
usecase "Image\n====\n\tDocker Hub\n====\n\tpostgres\n====\n\t9.6.2" as postgres_9_6_2 #Ivory
usecase "Image\n====\n\tdocker.bintray.io\n====\n\tjfrog/nginx-artifactory-pro:6.2.0\n====\n\t6.2.0" as docker_bintray_io_jfrog_nginx_artifactory_pro_6_2_0 #GoldenRod
usecase "Image\n====\n\tdocker.bintray.io\n====\n\tjfrog/artifactory-pro:6.2.0\n====\n\t6.2.0" as docker_bintray_io_jfrog_artifactory_pro_6_2_0 #LightGoldenRodYellow

'Chart Dependencies
artifactory_ha_0_4_1--[#green]-|>postgresql_0_8_7
artifactory_ha_0_4_1--[#orange]-|>docker_bintray_io_jfrog_artifactory_pro_6_2_0
artifactory_ha_0_4_1--[#orange]-|>docker_bintray_io_jfrog_nginx_artifactory_pro_6_2_0
postgresql_0_8_7--[#orange]-|>postgres_9_6_2

center footer Generated on 2020/04/21 20:19:35 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
