@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for auditbeat:1.0.0

'There is one referenced Helm Chart
artifact "auditbeat:1.0.0\n====\n\tauditbeat\n====\n\t1.0.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: cpanato, mumoshu\n====\n\tKeywords: " as auditbeat_1_0_0 #LightPink

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/03/16 17:12:57 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
