@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for aws-iam-authenticator:0.1.1

'There is one referenced Helm Chart
artifact "aws-iam-authenticator:0.1.1\n====\n\taws-iam-authenticator\n====\n\t0.1.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: plumdog\n====\n\tKeywords: " as aws_iam_authenticator_0_1_1 #DarkSalmon

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/04/21 20:19:54 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
