@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for aws-cluster-autoscaler:0.3.4

'There is one referenced Helm Chart
artifact "aws-cluster-autoscaler:0.3.4\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: " as aws_cluster_autoscaler_0_3_4 #HoneyDew

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nk8s.gcr.io/cluster-autoscaler\n====\nv0.6.1" as k8s_gcr_io_cluster_autoscaler_v0_6_1 #LightCyan

'Chart Dependencies
aws_cluster_autoscaler_0_3_4--[#orange]-|>k8s_gcr_io_cluster_autoscaler_v0_6_1

center footer Generated on 2022/05/22 15:53:46 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
