@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for aws-iam-authenticator:0.1.4

'There is one referenced Helm Chart
artifact "aws-iam-authenticator:0.1.4\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tplumdog\n\t\tnckturner\n====\n\tKeywords: " as aws_iam_authenticator_0_1_4 #DarkSalmon

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/13 16:15:13 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
