@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for cert-manager:v0.6.7

'There is one referenced Helm Chart
artifact "cert-manager:v0.6.7\n====\n\tcert-manager\n====\n\tv0.6.7\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: \n====\n\tKeywords: cert-manager\nkube-lego\nletsencrypt\ntls" as cert_manager_v0_6_7 #Cornsilk

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/04/26 13:42:14 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
