@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for chartmuseum:2.12.0

'There is one referenced Helm Chart
artifact "chartmuseum:2.12.0\n====\n\tchartmuseum\n====\n\t2.12.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: codefresh-io, cloudposse, chartmuseum\n====\n\tKeywords: chartmuseum\nhelm\ncharts repo" as chartmuseum_2_12_0 #AntiqueWhite

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tchartmuseum/chartmuseum\n====\n\tv0.12.0" as chartmuseum_chartmuseum_v0_12_0 #LightSeaGreen

'Chart Dependencies
chartmuseum_2_12_0--[#orange]-|>chartmuseum_chartmuseum_v0_12_0

center footer Generated on 2020/04/21 20:20:36 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
