@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for chronograf:1.1.0

'There is one referenced Helm Chart
artifact "chronograf:1.1.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: jackzampolin\n====\n\tKeywords: \n\t\tchronograf\n\t\tvisualizaion\n\t\ttimeseries" as chronograf_1_1_0 #DarkGoldenRod

'There is one referenced Docker Image
usecase "Image\n====\nquay.io\n====\ninfluxdb/chronograf:1.7.12\n====\n1.7.12" as quay_io_influxdb_chronograf_1_7_12 #LightSteelBlue

'Chart Dependencies
chronograf_1_1_0--[#orange]-|>quay_io_influxdb_chronograf_1_7_12

center footer Generated on 2022/05/22 15:56:21 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
