@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for clamav:1.0.6

'There is one referenced Helm Chart
artifact "clamav:1.0.6\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: zakkg3\n====\n\tKeywords: " as clamav_1_0_6 #IndianRed

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nmailu/clamav\n====\n1.6" as mailu_clamav_1_6 #DarkTurquoise

'Chart Dependencies
clamav_1_0_6--[#orange]-|>mailu_clamav_1_6

center footer Generated on 2022/05/22 15:56:34 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
