@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for cloudserver:1.0.5

'There are 3 referenced Helm Charts
artifact "redis-ha:3.0.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: ssalaues\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_ha_3_0_0 #IndianRed
artifact "mongodb-replicaset:3.6.4\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tfoxish\n\t\tunguiculus\n====\n\tKeywords: " as mongodb_replicaset_3_6_4 #Fuchsia
artifact "cloudserver:1.0.5\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tssalaues\n\t\ttmacro\n====\n\tKeywords: " as cloudserver_1_0_5 #Cornsilk

'There are 3 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nzenko/cloudserver\n====\n8.1.5" as zenko_cloudserver_8_1_5 #CornflowerBlue
usecase "Image\n====\nDocker Hub\n====\nmongo\n====\n3.6" as mongo_3_6 #Aqua
usecase "Image\n====\nDocker Hub\n====\nredis\n====\n4.0.11-stretch" as redis_4_0_11_stretch #LightSeaGreen

'Chart Dependencies
cloudserver_1_0_5--[#green]-|>mongodb_replicaset_3_6_4
cloudserver_1_0_5--[#green]-|>redis_ha_3_0_0
redis_ha_3_0_0--[#orange]-|>redis_4_0_11_stretch
mongodb_replicaset_3_6_4--[#orange]-|>mongo_3_6
cloudserver_1_0_5--[#orange]-|>zenko_cloudserver_8_1_5

center footer Generated on 2022/05/07 19:50:51 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
