@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for concourse:8.2.7

'There are 2 referenced Helm Charts
artifact "concourse:8.2.7\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tcirocosta\n\t\twilliam-tran\n\t\tYoussB\n====\n\tKeywords: \n\t\tci\n\t\tconcourse\n\t\tconcourse.ci" as concourse_8_2_7 #GreenYellow
artifact "postgresql:5.3.8\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_5_3_8 #LightSteelBlue

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:11.3.0-debian-9-r38\n====\n11.3.0-debian-9-r38" as docker_io_bitnami_postgresql_11_3_0_debian_9_r38 #DarkSalmon
usecase "Image\n====\nDocker Hub\n====\nconcourse/concourse\n====\n5.6.0" as concourse_concourse_5_6_0 #LightCyan

'Chart Dependencies
concourse_8_2_7--[#green]-|>postgresql_5_3_8
concourse_8_2_7--[#orange]-|>concourse_concourse_5_6_0
postgresql_5_3_8--[#orange]-|>docker_io_bitnami_postgresql_11_3_0_debian_9_r38

center footer Generated on 2022/05/22 15:57:58 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
