@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for contour:0.1.1

'There is one referenced Helm Chart
artifact "contour:0.1.1\n====\n\tcontour\n====\n\t0.1.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: pickledrick\n====\n\tKeywords: ingress\nenvoy\ncontour" as contour_0_1_1 #DodgerBlue

'There is one referenced Docker Image
usecase "Image\n====\n\tgcr.io\n====\n\theptio-images/contour:v0.15.0\n====\n\tv0.15.0" as gcr_io_heptio_images_contour_v0_15_0 #LightCoral

'Chart Dependencies
contour_0_1_1--[#orange]-|>gcr_io_heptio_images_contour_v0_15_0

center footer Generated on 2020/04/21 20:21:27 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
