@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for cosbench:1.0.1

'There is one referenced Helm Chart
artifact "cosbench:1.0.1\n====\n\tcosbench\n====\n\t1.0.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: giacomoguiulfo\n====\n\tKeywords: " as cosbench_1_0_1 #LightCoral

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tzenko/zenko-cosbench\n====\n\t0.0.6" as zenko_zenko_cosbench_0_0_6 #Ivory

'Chart Dependencies
cosbench_1_0_1--[#orange]-|>zenko_zenko_cosbench_0_0_6

center footer Generated on 2020/04/21 20:21:33 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
