@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for coscale:1.0.2

'There is one referenced Helm Chart
artifact "coscale:1.0.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tmonitoring\n\t\talerting\n\t\tmetric\n\t\tevent\n\t\tanomaly detection" as coscale_1_0_2 #DodgerBlue

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/22 15:59:02 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
