@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for coscale:1.0.0

'There is one referenced Helm Chart
artifact "coscale:1.0.0\n====\n\tcoscale\n====\n\t1.0.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: fryckbos\n====\n\tKeywords: monitoring\nalerting\nmetric\nevent\nanomaly detection" as coscale_1_0_0 #DodgerBlue

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/03/16 17:14:44 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
