@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for couchdb:2.2.0

'There is one referenced Helm Chart
artifact "couchdb:2.2.0\n====\n\tcouchdb\n====\n\t2.2.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: kocolosk\n====\n\tKeywords: couchdb\ndatabase\nnosql" as couchdb_2_2_0 #DodgerBlue

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tcouchdb\n====\n\t2.3.1" as couchdb_2_3_1 #DodgerBlue

'Chart Dependencies
couchdb_2_2_0--[#orange]-|>couchdb_2_3_1

center footer Generated on 2020/04/26 13:43:39 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
