@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for distributed-jmeter:1.0.0

'There is one referenced Helm Chart
artifact "distributed-jmeter:1.0.0\n====\n\tdistributed-jmeter\n====\n\t1.0.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: pedrocesar-ti\n====\n\tKeywords: " as distributed_jmeter_1_0_0 #LightBlue

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tpedrocesarti/jmeter-docker\n====\n\t3.3" as pedrocesarti_jmeter_docker_3_3 #LightGreen

'Chart Dependencies
distributed_jmeter_1_0_0--[#orange]-|>pedrocesarti_jmeter_docker_3_3

center footer Generated on 2020/04/21 20:22:14 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
