@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for distributed-tensorflow:0.1.2

'There is one referenced Helm Chart
artifact "distributed-tensorflow:0.1.2\n====\n\tdistributed-tensorflow\n====\n\t0.1.2\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: cheyang\n====\n\tKeywords: " as distributed_tensorflow_0_1_2 #LightSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tcheyang/distributed-tf\n====\n\t1.6.0" as cheyang_distributed_tf_1_6_0 #LightGrey

'Chart Dependencies
distributed_tensorflow_0_1_2--[#orange]-|>cheyang_distributed_tf_1_6_0

center footer Generated on 2020/03/16 17:15:24 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
