@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for dmarc2logstash:1.3.0

'There is one referenced Helm Chart
artifact "dmarc2logstash:1.3.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: jertel\n====\n\tKeywords: " as dmarc2logstash_1_3_0 #CadetBlue

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/22 16:01:22 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
