@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for dokuwiki:6.0.9

'There is one referenced Helm Chart
artifact "dokuwiki:6.0.9\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tdokuwiki\n\t\twiki\n\t\thttp\n\t\tweb\n\t\tapplication\n\t\tphp" as dokuwiki_6_0_9 #Gainsboro

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/dokuwiki:0.20180422.201901061035-debian-10-r28\n====\n0.20180422.201901061035-debian-10-r28" as docker_io_bitnami_dokuwiki_0_20180422_201901061035_debian_10_r28 #GoldenRod

'Chart Dependencies
dokuwiki_6_0_9--[#orange]-|>docker_io_bitnami_dokuwiki_0_20180422_201901061035_debian_10_r28

center footer Generated on 2022/05/13 16:22:30 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
