@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for elastalert:1.5.0

'There is one referenced Helm Chart
artifact "elastalert:1.5.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tjertel\n\t\tolemarkus\n====\n\tKeywords: " as elastalert_1_5_0 #Lavender

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/07 19:56:19 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
