@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for elastabot:1.2.0

'There is one referenced Helm Chart
artifact "elastabot:1.2.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: jertel\n====\n\tKeywords: " as elastabot_1_2_0 #Lavender

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/13 16:23:17 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
