@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for express-gateway:1.6.6

'There are 2 referenced Helm Charts
artifact "redis:10.5.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_10_5_7 #LightSeaGreen
artifact "express-gateway:1.6.6\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: " as express_gateway_1_6_6 #CadetBlue

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/redis:5.0.7-debian-10-r32\n====\n5.0.7-debian-10-r32" as docker_io_bitnami_redis_5_0_7_debian_10_r32 #Azure
usecase "Image\n====\nDocker Hub\n====\nexpressgateway/express-gateway\n====\nv1.16.9" as expressgateway_express_gateway_v1_16_9 #FloralWhite

'Chart Dependencies
express_gateway_1_6_6--[#green]-|>redis_10_5_7
redis_10_5_7--[#orange]-|>docker_io_bitnami_redis_5_0_7_debian_10_r32
express_gateway_1_6_6--[#orange]-|>expressgateway_express_gateway_v1_16_9

center footer Generated on 2022/05/07 19:58:12 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
