@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for factorio:0.4.0

'There is one referenced Helm Chart
artifact "factorio:0.4.0\n====\n\tfactorio\n====\n\t0.4.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: gtaylor\n====\n\tKeywords: game\nserver" as factorio_0_4_0 #LemonChiffon

'There is one referenced Docker Image
usecase "Image\n====\n\tquay.io\n====\n\tgames_on_k8s/factorio:0.15.39\n====\n\t0.15.39" as quay_io_games_on_k8s_factorio_0_15_39 #Khaki

'Chart Dependencies
factorio_0_4_0--[#orange]-|>quay_io_games_on_k8s_factorio_0_15_39

center footer Generated on 2020/04/26 13:45:48 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
