@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for gangway:0.4.2

'There is one referenced Helm Chart
artifact "gangway:0.4.2\n====\n\tgangway\n====\n\t0.4.2\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: rk295\n====\n\tKeywords: " as gangway_0_4_2 #Azure

'There is one referenced Docker Image
usecase "Image\n====\n\tgcr.io\n====\n\theptio-images/gangway:v3.2.0\n====\n\tv3.2.0" as gcr_io_heptio_images_gangway_v3_2_0 #Coral

'Chart Dependencies
gangway_0_4_2--[#orange]-|>gcr_io_heptio_images_gangway_v3_2_0

center footer Generated on 2020/04/21 20:24:25 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
