@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for gce-ingress:1.2.0

'There is one referenced Helm Chart
artifact "gce-ingress:1.2.0\n====\n\tgce-ingress\n====\n\t1.2.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: paulczar\n====\n\tKeywords: ingress\ngce" as gce_ingress_1_2_0 #BurlyWood

'There are 2 referenced Docker Images
usecase "Image\n====\n\tDocker Hub\n====\n\tk8s.gcr.io/defaultbackend\n====\n\t1.4" as k8s_gcr_io_defaultbackend_1_4 #DarkSeaGreen
usecase "Image\n====\n\tDocker Hub\n====\n\tk8s.gcr.io/ingress-gce-glbc-amd64\n====\n\tv1.4.0" as k8s_gcr_io_ingress_gce_glbc_amd64_v1_4_0 #LightCoral

'Chart Dependencies
gce_ingress_1_2_0--[#orange]-|>k8s_gcr_io_ingress_gce_glbc_amd64_v1_4_0
gce_ingress_1_2_0--[#orange]-|>k8s_gcr_io_defaultbackend_1_4

center footer Generated on 2020/04/26 13:46:23 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
