@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for gcloud-endpoints:0.1.1

'There is one referenced Helm Chart
artifact "gcloud-endpoints:0.1.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: ultimateboy\n====\n\tKeywords: \n\t\tgoogle\n\t\tendpoints\n\t\tnginx\n\t\tgcloud\n\t\tproxy\n\t\tauthentication\n\t\tmonitoring\n\t\tapi\n\t\tswagger\n\t\topen api" as gcloud_endpoints_0_1_1 #Chartreuse

'There is one referenced Docker Image
usecase "Image\n====\nb.gcr.io\n====\nendpoints/endpoints-runtime:1\n====\n1" as b_gcr_io_endpoints_endpoints_runtime_1 #DarkSalmon

'Chart Dependencies
gcloud_endpoints_0_1_1--[#orange]-|>b_gcr_io_endpoints_endpoints_runtime_1

center footer Generated on 2022/05/07 20:00:37 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
