@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for gcp-night-king:1.0.1

'There is one referenced Helm Chart
artifact "gcp-night-king:1.0.1\n====\n\tgcp-night-king\n====\n\t1.0.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: itamaro\n====\n\tKeywords: " as gcp_night_king_1_0_1 #AliceBlue

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/04/21 20:24:45 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
