@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for gitlab-ee:0.2.3

'There are 3 referenced Helm Charts
artifact "gitlab-ee:0.2.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tgit\n\t\tci\n\t\tdeploy\n\t\tissue tracker\n\t\tcode review\n\t\twiki" as gitlab_ee_0_2_3 #Aqua
artifact "redis:0.9.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: bitnami-bot\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_0_9_0 #LightSeaGreen
artifact "postgresql:0.8.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tswordbeta\n\t\tdatabus23\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql" as postgresql_0_8_1 #LightSteelBlue

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nbitnami/redis\n====\n3.2.9-r2" as bitnami_redis_3_2_9_r2 #Khaki
usecase "Image\n====\nDocker Hub\n====\npostgres\n====\n9.6" as postgres_9_6 #Ivory

'Chart Dependencies
gitlab_ee_0_2_3--[#green]-|>postgresql_0_8_1
gitlab_ee_0_2_3--[#green]-|>redis_0_9_0
redis_0_9_0--[#orange]-|>bitnami_redis_3_2_9_r2
postgresql_0_8_1--[#orange]-|>postgres_9_6

center footer Generated on 2022/05/13 16:28:43 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
