@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for gocd:1.32.0

'There is one referenced Helm Chart
artifact "gocd:1.32.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tgocd\n\t\tci\n\t\tcd\n\t\tci/cd\n\t\tcontinuous-integration\n\t\tcontinuous-delivery\n\t\tcontinuous-deployment\n\t\tcontinuous-testing" as gocd_1_32_0 #LightSteelBlue

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\ngocd/gocd-server\n====\nv20.8.0" as gocd_gocd_server_v20_8_0 #Aqua
usecase "Image\n====\nDocker Hub\n====\ngocd/gocd-agent-alpine-3.9\n====\nv20.8.0" as gocd_gocd_agent_alpine_3_9_v20_8_0 #BurlyWood

'Chart Dependencies
gocd_1_32_0--[#orange]-|>gocd_gocd_server_v20_8_0
gocd_1_32_0--[#orange]-|>gocd_gocd_agent_alpine_3_9_v20_8_0

center footer Generated on 2022/05/22 16:08:58 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
