@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for hazelcast-jet:1.5.0

'There is one referenced Helm Chart
artifact "hazelcast-jet:1.5.0\n====\n\thazelcast-jet\n====\n\t1.5.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: emin, ali\n====\n\tKeywords: hazelcast\njet\nstreaming" as hazelcast_jet_1_5_0 #Darkorange

'There are 2 referenced Docker Images
usecase "Image\n====\n\tDocker Hub\n====\n\thazelcast/hazelcast-jet-management-center\n====\n\t4.0" as hazelcast_hazelcast_jet_management_center_4_0 #IndianRed
usecase "Image\n====\n\tDocker Hub\n====\n\thazelcast/hazelcast-jet\n====\n\t4.0" as hazelcast_hazelcast_jet_4_0 #LightGreen

'Chart Dependencies
hazelcast_jet_1_5_0--[#orange]-|>hazelcast_hazelcast_jet_4_0
hazelcast_jet_1_5_0--[#orange]-|>hazelcast_hazelcast_jet_management_center_4_0

center footer Generated on 2020/04/21 20:25:44 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
