@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for hl-composer:1.0.14

'There is one referenced Helm Chart
artifact "hl-composer:1.0.14\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tblockchain\n\t\thyperledger\n\t\tfabric\n\t\tcomposer" as hl_composer_1_0_14 #Aquamarine

'There are 3 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nhyperledger/composer-cli\n====\n0.20.0" as hyperledger_composer_cli_0_20_0 #Fuchsia
usecase "Image\n====\nDocker Hub\n====\nhyperledger/composer-playground\n====\n0.20.0" as hyperledger_composer_playground_0_20_0 #GoldenRod
usecase "Image\n====\nDocker Hub\n====\nhyperledger/composer-rest-server\n====\n0.20.0" as hyperledger_composer_rest_server_0_20_0 #AliceBlue

'Chart Dependencies
hl_composer_1_0_14--[#orange]-|>hyperledger_composer_cli_0_20_0
hl_composer_1_0_14--[#orange]-|>hyperledger_composer_rest_server_0_20_0
hl_composer_1_0_14--[#orange]-|>hyperledger_composer_playground_0_20_0

center footer Generated on 2022/05/07 20:04:24 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
