@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for home-assistant:0.13.4

'There is one referenced Helm Chart
artifact "home-assistant:0.13.4\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\thome-assistant\n\t\thass\n\t\thomeassistant" as home_assistant_0_13_4 #LightSalmon

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nhomeassistant/home-assistant\n====\n0.108.7" as homeassistant_home_assistant_0_108_7 #LightCoral

'Chart Dependencies
home_assistant_0_13_4--[#orange]-|>homeassistant_home_assistant_0_108_7

center footer Generated on 2022/05/22 16:13:09 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
