@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for horovod:0.2.1

'There is one referenced Helm Chart
artifact "horovod:0.2.1\n====\n\thorovod\n====\n\t0.2.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: cheyang\n====\n\tKeywords: " as horovod_0_2_1 #Fuchsia

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tuber/horovod\n====\n\t0.12.1-tf1.8.0-py3.5" as uber_horovod_0_12_1_tf1_8_0_py3_5 #Gainsboro

'Chart Dependencies
horovod_0_2_1--[#orange]-|>uber_horovod_0_12_1_tf1_8_0_py3_5

center footer Generated on 2020/04/21 20:26:32 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
