@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for hubot:1.0.1

'There are 2 referenced Helm Charts
artifact "hubot:1.0.1\n====\n\thubot\n====\n\t1.0.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: darioblanco, decayofmind\n====\n\tKeywords: slack\nhubot\nchatbot" as hubot_1_0_1 #Aqua
artifact "redis:9.4.3\n====\n\tredis\n====\n\t9.4.3\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: Bitnami, desaintmartin\n====\n\tKeywords: redis\nkeyvalue\ndatabase" as redis_9_4_3 #LightSeaGreen

'There are 2 referenced Docker Images
usecase "Image\n====\n\tDocker Hub\n====\n\tminddocdev/hubot\n====\n\t3.3.2" as minddocdev_hubot_3_3_2 #DodgerBlue
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/redis:5.0.5-debian-9-r169\n====\n\t5.0.5-debian-9-r169" as docker_io_bitnami_redis_5_0_5_debian_9_r169 #Azure

'Chart Dependencies
hubot_1_0_1--[#green]-|>redis_9_4_3
hubot_1_0_1--[#orange]-|>docker_io_bitnami_redis_5_0_5_debian_9_r169
hubot_1_0_1--[#orange]-|>minddocdev_hubot_3_3_2
redis_9_4_3--[#orange]-|>docker_io_bitnami_redis_5_0_5_debian_9_r169

center footer Generated on 2020/04/21 20:26:35 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
