@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for inbucket:3.1.0

'There is one referenced Helm Chart
artifact "inbucket:3.1.0\n====\n\tinbucket\n====\n\t3.1.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: cpanato, jhillyerd\n====\n\tKeywords: inbucket\nmail\nsmtp\npop3\nemail\ntesting\ndisposable webmail" as inbucket_3_1_0 #LightSkyBlue

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tjhillyerd/inbucket\n====\n\trelease-2.0.0" as jhillyerd_inbucket_release_2_0_0 #Chocolate

'Chart Dependencies
inbucket_3_1_0--[#orange]-|>jhillyerd_inbucket_release_2_0_0

center footer Generated on 2020/04/21 20:26:44 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
