@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for ingressmonitorcontroller:1.0.47

'There is one referenced Helm Chart
artifact "ingressmonitorcontroller:1.0.47\n====\n\tingressmonitorcontroller\n====\n\t1.0.47\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: rasheedamir, waseem-h, faizanahmad055, kahootali, ahmadiq\n====\n\tKeywords: IngressMonitorController\nkubernetes" as ingressmonitorcontroller_1_0_47 #DarkSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tstakater/ingressmonitorcontroller\n====\n\t1.0.47" as stakater_ingressmonitorcontroller_1_0_47 #GhostWhite

'Chart Dependencies
ingressmonitorcontroller_1_0_47--[#orange]-|>stakater_ingressmonitorcontroller_1_0_47

center footer Generated on 2020/04/26 13:48:52 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
