@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for jaeger-operator:2.12.0

'There is one referenced Helm Chart
artifact "jaeger-operator:2.12.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tcpanato\n\t\tbatazor\n====\n\tKeywords: " as jaeger_operator_2_12_0 #Azure

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\njaegertracing/jaeger-operator\n====\n1.15.1" as jaegertracing_jaeger_operator_1_15_1 #Chartreuse

'Chart Dependencies
jaeger_operator_2_12_0--[#orange]-|>jaegertracing_jaeger_operator_1_15_1

center footer Generated on 2022/05/22 16:15:21 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
