@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kapacitor:1.2.1

'There is one referenced Helm Chart
artifact "kapacitor:1.2.1\n====\n\tkapacitor\n====\n\t1.2.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: jackzampolin, aisuko\n====\n\tKeywords: kapacitor\nstream\netl\ntimeseries" as kapacitor_1_2_1 #Cornsilk

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/03/16 17:20:37 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
