@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for katafygio:1.0.0

'There is one referenced Helm Chart
artifact "katafygio:1.0.0\n====\n\tkatafygio\n====\n\t1.0.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: bpineau\n====\n\tKeywords: backup\ndump\nkatafygio\ngit" as katafygio_1_0_0 #LightSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tbpineau/katafygio\n====\n\tv0.8.1" as bpineau_katafygio_v0_8_1 #LavenderBlush

'Chart Dependencies
katafygio_1_0_0--[#orange]-|>bpineau_katafygio_v0_8_1

center footer Generated on 2020/03/16 17:20:43 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
