@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for keel:0.5.0

'There is one referenced Helm Chart
artifact "keel:0.5.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\trimusz\n\t\trusenask\n\t\tarchifleks\n====\n\tKeywords: \n\t\tkubernetes deployment\n\t\thelm release\n\t\tcontinuous deployment" as keel_0_5_0 #LightSteelBlue

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nkeelhq/keel\n====\n0.9.5" as keelhq_keel_0_9_5 #DarkTurquoise

'Chart Dependencies
keel_0_5_0--[#orange]-|>keelhq_keel_0_9_5

center footer Generated on 2022/05/13 16:37:37 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
