@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kiam:2.5.2

'There is one referenced Helm Chart
artifact "kiam:2.5.2\n====\n\tkiam\n====\n\t2.5.2\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: ewbankkit\n====\n\tKeywords: kiam\naws\niam\nsecurity" as kiam_2_5_2 #AliceBlue

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/04/26 13:50:15 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
