@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kong:0.36.5

'There is one referenced Helm Chart
artifact "kong:0.36.5\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tshashiranjan84\n\t\thbagdi\n====\n\tKeywords: " as kong_0_36_5 #LightSteelBlue

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nkong\n====\n1.4" as kong_1_4 #LightSteelBlue
usecase "Image\n====\nDocker Hub\n====\nkong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller\n====\n0.7.0" as kong_docker_kubernetes_ingress_controller_bintray_io_kong_ingress_controller_0_7_0 #IndianRed

'Chart Dependencies
kong_0_36_5--[#orange]-|>kong_1_4
kong_0_36_5--[#orange]-|>kong_docker_kubernetes_ingress_controller_bintray_io_kong_ingress_controller_0_7_0

center footer Generated on 2022/05/30 23:00:31 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
