@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kube-hunter:1.0.3

'There is one referenced Helm Chart
artifact "kube-hunter:1.0.3\n====\n\tkube-hunter\n====\n\t1.0.3\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: desaintmartin, lizrice\n====\n\tKeywords: kubernetes\nkube-hunter\nsecurity" as kube_hunter_1_0_3 #LavenderBlush

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/03/16 17:21:13 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
