@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kube-lego:0.4.1

'There is one referenced Helm Chart
artifact "kube-lego:0.4.1\n====\n\tkube-lego\n====\n\t0.4.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: \n====\n\tKeywords: kube-lego\nletsencrypt" as kube_lego_0_4_1 #Coral

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tjetstack/kube-lego\n====\n\t0.1.5" as jetstack_kube_lego_0_1_5 #LightPink

'Chart Dependencies
kube_lego_0_4_1--[#orange]-|>jetstack_kube_lego_0_1_5

center footer Generated on 2020/04/21 20:28:42 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
