@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kured:1.5.0

'There is one referenced Helm Chart
artifact "kured:1.5.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tplumdog\n\t\tpatrickmslatteryvt\n====\n\tKeywords: " as kured_1_5_0 #LightSeaGreen

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/07 20:13:49 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
