@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for luigi:2.7.8

'There are 2 referenced Helm Charts
artifact "mysql:1.6.7\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tolemarkus\n\t\tviglesiasce\n====\n\tKeywords: \n\t\tmysql\n\t\tdatabase\n\t\tsql" as mysql_1_6_7 #Aqua
artifact "luigi:2.7.8\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tluigi\n\t\tscheduler\n\t\tdependency graph\n\t\tweb\n\t\ttask management\n\t\thadoop\n\t\tspark\n\t\tkubernetes job manager" as luigi_2_7_8 #Aqua

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\naxiom/docker-luigi\n====\n2.7.2-alpine" as axiom_docker_luigi_2_7_2_alpine #LightCoral
usecase "Image\n====\nDocker Hub\n====\nmysql\n====\n5.7.30" as mysql_5_7_30 #Aqua

'Chart Dependencies
luigi_2_7_8--[#green]-|>mysql_1_6_7
mysql_1_6_7--[#orange]-|>mysql_5_7_30
luigi_2_7_8--[#orange]-|>axiom_docker_luigi_2_7_2_alpine

center footer Generated on 2022/05/13 16:42:26 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
