@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for mcrouter:1.0.3

'There are 2 referenced Helm Charts
artifact "memcached:3.1.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tgtaylor\n\t\tolemarkus\n\t\tkennethaasan\n====\n\tKeywords: \n\t\tmemcached\n\t\tcache" as memcached_3_1_0 #DarkSeaGreen
artifact "mcrouter:1.0.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: jphalip\n====\n\tKeywords: " as mcrouter_1_0_3 #Aqua

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nmemcached\n====\n1.5.19-alpine" as memcached_1_5_19_alpine #DarkSeaGreen

'Chart Dependencies
mcrouter_1_0_3--[#green]-|>memcached_3_1_0
memcached_3_1_0--[#orange]-|>memcached_1_5_19_alpine

center footer Generated on 2022/05/13 16:44:08 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
