@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for metallb:0.12.0

'There is one referenced Helm Chart
artifact "metallb:0.12.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: danderson\n====\n\tKeywords: \n\t\tload-balancer\n\t\tbalancer\n\t\tlb\n\t\tbgp\n\t\tarp\n\t\tvrrp\n\t\tvip" as metallb_0_12_0 #GoldenRod

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nmetallb/controller\n====\nv0.8.1" as metallb_controller_v0_8_1 #Coral

'Chart Dependencies
metallb_0_12_0--[#orange]-|>metallb_controller_v0_8_1

center footer Generated on 2022/05/22 16:26:17 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
