@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for metrics-server:2.11.1

'There is one referenced Helm Chart
artifact "metrics-server:2.11.1\n====\n\tmetrics-server\n====\n\t2.11.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: olemarkus, kennethaasan\n====\n\tKeywords: metrics-server" as metrics_server_2_11_1 #Cyan

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tk8s.gcr.io/metrics-server-amd64\n====\n\tv0.3.6" as k8s_gcr_io_metrics_server_amd64_v0_3_6 #DarkSeaGreen

'Chart Dependencies
metrics_server_2_11_1--[#orange]-|>k8s_gcr_io_metrics_server_amd64_v0_3_6

center footer Generated on 2020/04/21 20:31:20 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
