@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for minecraft:1.2.2

'There is one referenced Helm Chart
artifact "minecraft:1.2.2\n====\n\tminecraft\n====\n\t1.2.2\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: gtaylor, billimek, itzg\n====\n\tKeywords: game\nserver" as minecraft_1_2_2 #Khaki

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/04/26 13:52:59 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
