@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for moodle:7.2.8

'There are 2 referenced Helm Charts
artifact "mariadb:7.3.12\n====\n\tmariadb\n====\n\t7.3.12\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: mariadb\nmysql\ndatabase\nsql\nprometheus" as mariadb_7_3_12 #DarkTurquoise
artifact "moodle:7.2.8\n====\n\tmoodle\n====\n\t7.2.8\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: \n====\n\tKeywords: moodle\nlearning\nphp" as moodle_7_2_8 #Gainsboro

'There are 2 referenced Docker Images
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/moodle:3.8.2-debian-10-r0\n====\n\t3.8.2-debian-10-r0" as docker_io_bitnami_moodle_3_8_2_debian_10_r0 #CadetBlue
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/mariadb:10.3.22-debian-10-r27\n====\n\t10.3.22-debian-10-r27" as docker_io_bitnami_mariadb_10_3_22_debian_10_r27 #DarkGoldenRod

'Chart Dependencies
moodle_7_2_8--[#green]-|>mariadb_7_3_12
mariadb_7_3_12--[#orange]-|>docker_io_bitnami_mariadb_10_3_22_debian_10_r27
moodle_7_2_8--[#orange]-|>docker_io_bitnami_moodle_3_8_2_debian_10_r0

center footer Generated on 2020/04/26 13:53:24 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
