@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for msoms:0.2.0

'There is one referenced Helm Chart
artifact "msoms:0.2.0\n====\n\tmsoms\n====\n\t0.2.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: Sambit Mishra, Keiko Harada\n====\n\tKeywords: monitoring\nalerting\nmetric\nevent\nlogging" as msoms_0_2_0 #LightSeaGreen

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2020/04/21 20:31:54 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
