@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for mssql-linux:0.11.3

'There is one referenced Helm Chart
artifact "mssql-linux:0.11.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tthomasliddledba\n\t\twinromulus\n====\n\tKeywords: " as mssql_linux_0_11_3 #Gold

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nmicrosoft/mssql-server-linux\n====\n2017-CU5" as microsoft_mssql_server_linux_2017_CU5 #LightBlue

'Chart Dependencies
mssql_linux_0_11_3--[#orange]-|>microsoft_mssql_server_linux_2017_CU5

center footer Generated on 2022/05/13 16:47:09 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
