@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for namerd:0.2.0

'There is one referenced Helm Chart
artifact "namerd:0.2.0\n====\n\tnamerd\n====\n\t0.2.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: Sean Knox\n====\n\tKeywords: " as namerd_0_2_0 #Gainsboro

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tbuoyantio/namerd\n====\n\t0.9.1" as buoyantio_namerd_0_9_1 #AliceBlue

'Chart Dependencies
namerd_0_2_0--[#orange]-|>buoyantio_namerd_0_9_1

center footer Generated on 2020/04/26 13:53:47 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
