@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for nats:4.3.6

'There is one referenced Helm Chart
artifact "nats:4.3.6\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tnats\n\t\tmessaging\n\t\taddressing\n\t\tdiscovery" as nats_4_3_6 #AliceBlue

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/nats:2.1.4-debian-10-r24\n====\n2.1.4-debian-10-r24" as docker_io_bitnami_nats_2_1_4_debian_10_r24 #Cornsilk

'Chart Dependencies
nats_4_3_6--[#orange]-|>docker_io_bitnami_nats_2_1_4_debian_10_r24

center footer Generated on 2022/05/07 20:20:21 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
