@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for newrelic-infrastructure:0.13.36

'There is one referenced Helm Chart
artifact "newrelic-infrastructure:0.13.36\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tinfrastructure\n\t\tnewrelic\n\t\tmonitoring" as newrelic_infrastructure_0_13_36 #Gold

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/13 16:48:18 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
