@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for nginx-lego:0.3.0

'There is one referenced Helm Chart
artifact "nginx-lego:0.3.0\n====\n\tnginx-lego\n====\n\t0.3.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: Jack Zampolin\n====\n\tKeywords: kube-lego\nnginx-ingress-controller\nnginx\nletsencrypt" as nginx_lego_0_3_0 #FloralWhite

'There are 2 referenced Docker Images
usecase "Image\n====\n\tgcr.io\n====\n\tgoogle_containers/nginx-ingress-controller:0.8.3\n====\n\t0.8.3" as gcr_io_google_containers_nginx_ingress_controller_0_8_3 #Bisque
usecase "Image\n====\n\tgcr.io\n====\n\tgoogle_containers/defaultbackend:1.0\n====\n\t1.0" as gcr_io_google_containers_defaultbackend_1_0 #DodgerBlue

'Chart Dependencies
nginx_lego_0_3_0--[#orange]-|>gcr_io_google_containers_defaultbackend_1_0
nginx_lego_0_3_0--[#orange]-|>gcr_io_google_containers_nginx_ingress_controller_0_8_3

center footer Generated on 2020/04/26 13:54:31 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
