@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for node-red:1.4.2

'There is one referenced Helm Chart
artifact "node-red:1.4.2\n====\n\tnode-red\n====\n\t1.4.2\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: billimek, batazor\n====\n\tKeywords: nodered\nnode-red" as node_red_1_4_2 #GhostWhite

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tnodered/node-red\n====\n\t1.0.4-12-minimal" as nodered_node_red_1_0_4_12_minimal #GreenYellow

'Chart Dependencies
node_red_1_4_2--[#orange]-|>nodered_node_red_1_0_4_12_minimal

center footer Generated on 2020/04/21 20:33:01 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
