@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for node-problem-detector:1.8.2

'There is one referenced Helm Chart
artifact "node-problem-detector:1.8.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tmax-rocket-internet\n\t\tRandom-Liu\n\t\tandyxning\n\t\twangzhen127\n====\n\tKeywords: \n\t\tnode\n\t\tproblem\n\t\tdetector\n\t\tmonitoring" as node_problem_detector_1_8_2 #Ivory

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/07 20:22:13 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
