@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for openldap:1.2.7

'There is one referenced Helm Chart
artifact "openldap:1.2.7\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tldap\n\t\topenldap" as openldap_1_2_7 #LightBlue

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nosixia/openldap\n====\n1.2.4" as osixia_openldap_1_2_4 #CadetBlue

'Chart Dependencies
openldap_1_2_7--[#orange]-|>osixia_openldap_1_2_4

center footer Generated on 2022/05/22 16:33:15 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
