@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for openebs:1.11.0

'There is one referenced Helm Chart
artifact "openebs:1.11.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tkmova\n\t\tprateekpandey14\n====\n\tKeywords: \n\t\tcloud-native-storage\n\t\tblock-storage\n\t\tiSCSI\n\t\tstorage" as openebs_1_11_0 #GreenYellow

'There are 7 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nopenebs/snapshot-controller\n====\n1.11.0" as openebs_snapshot_controller_1_11_0 #LightSteelBlue
usecase "Image\n====\nDocker Hub\n====\nopenebs/m-apiserver\n====\n1.11.0" as openebs_m_apiserver_1_11_0 #Cyan
usecase "Image\n====\nDocker Hub\n====\nopenebs/snapshot-provisioner\n====\n1.11.0" as openebs_snapshot_provisioner_1_11_0 #LightGreen
usecase "Image\n====\nDocker Hub\n====\nopenebs/node-disk-operator-amd64\n====\n0.6.0" as openebs_node_disk_operator_amd64_0_6_0 #AntiqueWhite
usecase "Image\n====\nDocker Hub\n====\nopenebs/admission-server\n====\n1.11.0" as openebs_admission_server_1_11_0 #LightGreen
usecase "Image\n====\nDocker Hub\n====\nopenebs/openebs-k8s-provisioner\n====\n1.11.0" as openebs_openebs_k8s_provisioner_1_11_0 #LightGrey
usecase "Image\n====\nDocker Hub\n====\nopenebs/provisioner-localpv\n====\n1.11.0" as openebs_provisioner_localpv_1_11_0 #DodgerBlue

'Chart Dependencies
openebs_1_11_0--[#orange]-|>openebs_openebs_k8s_provisioner_1_11_0
openebs_1_11_0--[#orange]-|>openebs_snapshot_controller_1_11_0
openebs_1_11_0--[#orange]-|>openebs_snapshot_provisioner_1_11_0
openebs_1_11_0--[#orange]-|>openebs_node_disk_operator_amd64_0_6_0
openebs_1_11_0--[#orange]-|>openebs_provisioner_localpv_1_11_0
openebs_1_11_0--[#orange]-|>openebs_m_apiserver_1_11_0
openebs_1_11_0--[#orange]-|>openebs_admission_server_1_11_0

center footer Generated on 2022/05/22 16:32:52 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
