@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for orangehrm:7.0.10

'There are 2 referenced Helm Charts
artifact "orangehrm:7.0.10\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\torangehrm\n\t\thttp\n\t\thttps\n\t\tweb\n\t\tapplication\n\t\tphp\n\t\thuman resources" as orangehrm_7_0_10 #Cyan
artifact "mariadb:7.3.14\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_7_3_14 #DarkTurquoise

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.3.22-debian-10-r44\n====\n10.3.22-debian-10-r44" as docker_io_bitnami_mariadb_10_3_22_debian_10_r44 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/orangehrm:4.3.4-0-debian-10-r30\n====\n4.3.4-0-debian-10-r30" as docker_io_bitnami_orangehrm_4_3_4_0_debian_10_r30 #Bisque

'Chart Dependencies
orangehrm_7_0_10--[#green]-|>mariadb_7_3_14
orangehrm_7_0_10--[#orange]-|>docker_io_bitnami_orangehrm_4_3_4_0_debian_10_r30
mariadb_7_3_14--[#orange]-|>docker_io_bitnami_mariadb_10_3_22_debian_10_r44

center footer Generated on 2022/05/13 16:52:07 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
