@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for parse:10.3.10

'There are 2 referenced Helm Charts
artifact "mongodb:7.8.10\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmongodb\n\t\tdatabase\n\t\tnosql\n\t\tcluster\n\t\treplicaset\n\t\treplication" as mongodb_7_8_10 #GreenYellow
artifact "parse:10.3.10\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tparse\n\t\tbackend\n\t\tserverless\n\t\tplatform\n\t\tmbaas\n\t\tmobile" as parse_10_3_10 #LightSeaGreen

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/parse:3.10.0-debian-10-r47\n====\n3.10.0-debian-10-r47" as docker_io_bitnami_parse_3_10_0_debian_10_r47 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/mongodb:4.2.4-debian-10-r3\n====\n4.2.4-debian-10-r3" as docker_io_bitnami_mongodb_4_2_4_debian_10_r3 #Bisque

'Chart Dependencies
parse_10_3_10--[#green]-|>mongodb_7_8_10
mongodb_7_8_10--[#orange]-|>docker_io_bitnami_mongodb_4_2_4_debian_10_r3
parse_10_3_10--[#orange]-|>docker_io_bitnami_parse_3_10_0_debian_10_r47

center footer Generated on 2022/05/13 16:53:07 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
