@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for phabricator:9.0.12

'There are 2 referenced Helm Charts
artifact "phabricator:9.0.12\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tphabricator\n\t\thttp\n\t\thttps\n\t\tweb\n\t\tapplication\n\t\tcollaboration\n\t\tproject management\n\t\tbug tracking\n\t\tcode review\n\t\twiki\n\t\tgit\n\t\tmercurial\n\t\tsubversion" as phabricator_9_0_12 #Chartreuse
artifact "mariadb:7.3.12\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_7_3_12 #DarkTurquoise

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.3.22-debian-10-r27\n====\n10.3.22-debian-10-r27" as docker_io_bitnami_mariadb_10_3_22_debian_10_r27 #DarkGoldenRod

'Chart Dependencies
phabricator_9_0_12--[#green]-|>mariadb_7_3_12
mariadb_7_3_12--[#orange]-|>docker_io_bitnami_mariadb_10_3_22_debian_10_r27

center footer Generated on 2022/05/30 23:17:22 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
