@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for prometheus-mysql-exporter:0.5.1

'There is one referenced Helm Chart
artifact "prometheus-mysql-exporter:0.5.1\n====\n\tprometheus-mysql-exporter\n====\n\t0.5.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: juanchimienti, monotek\n====\n\tKeywords: " as prometheus_mysql_exporter_0_5_1 #DodgerBlue

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tprom/mysqld-exporter\n====\n\tv0.11.0" as prom_mysqld_exporter_v0_11_0 #DarkSalmon

'Chart Dependencies
prometheus_mysql_exporter_0_5_1--[#orange]-|>prom_mysqld_exporter_v0_11_0

center footer Generated on 2020/03/16 17:27:32 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
