@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for prometheus-rabbitmq-exporter:0.5.6

'There is one referenced Helm Chart
artifact "prometheus-rabbitmq-exporter:0.5.6\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: " as prometheus_rabbitmq_exporter_0_5_6 #Khaki

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nkbudde/rabbitmq-exporter\n====\nv0.29.0" as kbudde_rabbitmq_exporter_v0_29_0 #Gainsboro

'Chart Dependencies
prometheus_rabbitmq_exporter_0_5_6--[#orange]-|>kbudde_rabbitmq_exporter_v0_29_0

center footer Generated on 2022/05/30 23:22:24 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
