@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for prometheus:11.1.1

'There are 2 referenced Helm Charts
artifact "kube-state-metrics:2.7.2\n====\n\tkube-state-metrics\n====\n\t2.7.2\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: fiunchinho, tariq1890, mrueg\n====\n\tKeywords: metric\nmonitoring\nprometheus\nkubernetes" as kube_state_metrics_2_7_2 #Gainsboro
artifact "prometheus:11.1.1\n====\n\tprometheus\n====\n\t11.1.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: gianrubio, zanhsieh\n====\n\tKeywords: " as prometheus_11_1_1 #DarkGoldenRod

'There are 4 referenced Docker Images
usecase "Image\n====\n\tDocker Hub\n====\n\tprom/alertmanager\n====\n\tv0.20.0" as prom_alertmanager_v0_20_0 #Beige
usecase "Image\n====\n\tDocker Hub\n====\n\tprom/pushgateway\n====\n\tv1.0.1" as prom_pushgateway_v1_0_1 #Lavender
usecase "Image\n====\n\tquay.io\n====\n\tcoreos/kube-state-metrics:v1.9.5\n====\n\tv1.9.5" as quay_io_coreos_kube_state_metrics_v1_9_5 #LightGrey
usecase "Image\n====\n\tDocker Hub\n====\n\tjimmidyson/configmap-reload\n====\n\tv0.3.0" as jimmidyson_configmap_reload_v0_3_0 #LightGray

'Chart Dependencies
prometheus_11_1_1--[#green]-|>kube_state_metrics_2_7_2
kube_state_metrics_2_7_2--[#orange]-|>quay_io_coreos_kube_state_metrics_v1_9_5
prometheus_11_1_1--[#orange]-|>prom_pushgateway_v1_0_1
prometheus_11_1_1--[#orange]-|>jimmidyson_configmap_reload_v0_3_0
prometheus_11_1_1--[#orange]-|>prom_alertmanager_v0_20_0

center footer Generated on 2020/04/21 20:35:20 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
