@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for prometheus-consul-exporter:0.1.5

'There is one referenced Helm Chart
artifact "prometheus-consul-exporter:0.1.5\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: timm088\n====\n\tKeywords: \n\t\tmetrics\n\t\tconsul\n\t\tmonitoring" as prometheus_consul_exporter_0_1_5 #CornflowerBlue

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nprom/consul-exporter\n====\nv0.4.0" as prom_consul_exporter_v0_4_0 #Fuchsia

'Chart Dependencies
prometheus_consul_exporter_0_1_5--[#orange]-|>prom_consul_exporter_v0_4_0

center footer Generated on 2022/05/22 16:38:29 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
