@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for prometheus-pushgateway:1.4.3

'There is one referenced Helm Chart
artifact "prometheus-pushgateway:1.4.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tpushgateway\n\t\tprometheus" as prometheus_pushgateway_1_4_3 #LightGreen

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nprom/pushgateway\n====\nv1.2.0" as prom_pushgateway_v1_2_0 #Lavender

'Chart Dependencies
prometheus_pushgateway_1_4_3--[#orange]-|>prom_pushgateway_v1_2_0

center footer Generated on 2022/05/22 16:40:18 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
