@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for redis-ha:4.4.3

'There is one referenced Helm Chart
artifact "redis-ha:4.4.3\n====\n\tredis-ha\n====\n\t4.4.3\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: ssalaues, dandydeveloper\n====\n\tKeywords: redis\nkeyvalue\ndatabase" as redis_ha_4_4_3 #IndianRed

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tredis\n====\n\t5.0.6-alpine" as redis_5_0_6_alpine #LightSeaGreen

'Chart Dependencies
redis_ha_4_4_3--[#orange]-|>redis_5_0_6_alpine

center footer Generated on 2020/04/26 13:58:44 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
