@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for redis:10.5.6

'There is one referenced Helm Chart
artifact "redis:10.5.6\n====\n\tredis\n====\n\t10.5.6\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: Bitnami, desaintmartin\n====\n\tKeywords: redis\nkeyvalue\ndatabase" as redis_10_5_6 #LightSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/redis:5.0.7-debian-10-r32\n====\n\t5.0.7-debian-10-r32" as docker_io_bitnami_redis_5_0_7_debian_10_r32 #Azure

'Chart Dependencies
redis_10_5_6--[#orange]-|>docker_io_bitnami_redis_5_0_7_debian_10_r32

center footer Generated on 2020/04/26 13:58:39 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
