@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for redmine:14.1.11

'There are 2 referenced Helm Charts
artifact "mariadb:7.3.10\n====\n\tmariadb\n====\n\t7.3.10\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: mariadb\nmysql\ndatabase\nsql\nprometheus" as mariadb_7_3_10 #DarkTurquoise
artifact "redmine:14.1.11\n====\n\tredmine\n====\n\t14.1.11\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: \n====\n\tKeywords: redmine\nproject management\nwww\nhttp\nweb\napplication\nruby\nrails" as redmine_14_1_11 #Gainsboro

'There are 2 referenced Docker Images
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/redmine:4.1.0-debian-10-r25\n====\n\t4.1.0-debian-10-r25" as docker_io_bitnami_redmine_4_1_0_debian_10_r25 #Chartreuse
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/mariadb:10.3.22-debian-10-r17\n====\n\t10.3.22-debian-10-r17" as docker_io_bitnami_mariadb_10_3_22_debian_10_r17 #DarkGoldenRod

'Chart Dependencies
redmine_14_1_11--[#green]-|>mariadb_7_3_10
mariadb_7_3_10--[#orange]-|>docker_io_bitnami_mariadb_10_3_22_debian_10_r17
redmine_14_1_11--[#orange]-|>docker_io_bitnami_redmine_4_1_0_debian_10_r25

center footer Generated on 2020/03/16 17:28:38 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
