@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for risk-advisor:2.0.5

'There is one referenced Helm Chart
artifact "risk-advisor:2.0.5\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tpposkrobko\n\t\tPrytu\n\t\tGraczykowskiMichal\n\t\tjackmax\n====\n\tKeywords: " as risk_advisor_2_0_5 #Darkorange

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\npposkrobko/risk-advisor\n====\nv1.0.0" as pposkrobko_risk_advisor_v1_0_0 #LawnGreen

'Chart Dependencies
risk_advisor_2_0_5--[#orange]-|>pposkrobko_risk_advisor_v1_0_0

center footer Generated on 2022/05/13 17:01:22 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
