@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for schema-registry-ui:0.4.0

'There is one referenced Helm Chart
artifact "schema-registry-ui:0.4.0\n====\n\tschema-registry-ui\n====\n\t0.4.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: cristian04\n====\n\tKeywords: confluent\nschema-registry-ui\nKafka\navro\nschema-registry" as schema_registry_ui_0_4_0 #AntiqueWhite

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tlandoop/schema-registry-ui\n====\n\t0.9.5" as landoop_schema_registry_ui_0_9_5 #AliceBlue

'Chart Dependencies
schema_registry_ui_0_4_0--[#orange]-|>landoop_schema_registry_ui_0_9_5

center footer Generated on 2020/04/26 13:59:25 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
