@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for signalfx-agent:0.3.1

'There is one referenced Helm Chart
artifact "signalfx-agent:0.3.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tmonitoring\n\t\talerting\n\t\tmetrics\n\t\tstats" as signalfx_agent_0_3_1 #AntiqueWhite

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/30 23:28:47 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
