@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for spark-history-server:1.4.3

'There are 2 referenced Helm Charts
artifact "nfs:0.1.0\n====\n\tType: application\n====\n\tRepo: Unknown Repo URL\n====\n\tMaintainers: yuchaoran2011\n====\n\tKeywords: nfs" as nfs_0_1_0 #LightSteelBlue
artifact "spark-history-server:1.4.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tspark\n\t\thistory-server" as spark_history_server_1_4_3 #Cyan

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nk8s.gcr.io/volume-nfs\n====\n0.8" as k8s_gcr_io_volume_nfs_0_8 #LightGreen
usecase "Image\n====\nDocker Hub\n====\nlightbend/spark-history-server\n====\n2.4.0" as lightbend_spark_history_server_2_4_0 #DarkGoldenRod

'Chart Dependencies
spark_history_server_1_4_3--[#green]-|>nfs_0_1_0
nfs_0_1_0--[#orange]-|>k8s_gcr_io_volume_nfs_0_8
spark_history_server_1_4_3--[#orange]-|>lightbend_spark_history_server_2_4_0

center footer Generated on 2022/05/07 20:37:24 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
