@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for stash:0.5.2

'There is one referenced Helm Chart
artifact "stash:0.5.2\n====\n\tstash\n====\n\t0.5.2\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: appscode\n====\n\tKeywords: " as stash_0_5_2 #LightSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tappscode/stash\n====\n\t0.7.0-rc.1" as appscode_stash_0_7_0_rc_1 #FloralWhite

'Chart Dependencies
stash_0_5_2--[#orange]-|>appscode_stash_0_7_0_rc_1

center footer Generated on 2020/04/26 14:01:11 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
