@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for swift:0.6.2

'There is one referenced Helm Chart
artifact "swift:0.6.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: appscode\n====\n\tKeywords: " as swift_0_6_2 #LightSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nappscode/swift\n====\n0.7.3" as appscode_swift_0_7_3 #FloralWhite

'Chart Dependencies
swift_0_6_2--[#orange]-|>appscode_swift_0_7_3

center footer Generated on 2022/05/22 16:50:49 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
