@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for sysdig:1.7.14

'There is one referenced Helm Chart
artifact "sysdig:1.7.14\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tlachie83\n\t\tbencer\n\t\tnestorsalceda\n====\n\tKeywords: \n\t\tmonitoring\n\t\tsecurity\n\t\talerting\n\t\tmetric\n\t\ttroubleshooting\n\t\trun-time" as sysdig_1_7_14 #GreenYellow

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/22 16:51:07 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
