@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for uchiwa:1.0.1

'There are 3 referenced Helm Charts
artifact "uchiwa:1.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: sstarcher\n====\n\tKeywords: \n\t\tuchiwa\n\t\tsensu\n\t\tmonitoring" as uchiwa_1_0_1 #HoneyDew
artifact "redis:0.4.5\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_0_4_5 #LightSeaGreen
artifact "sensu:0.1.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: Shane Starcher\n====\n\tKeywords: \n\t\tsensu\n\t\tmonitoring" as sensu_0_1_2 #Aqua

'There are 3 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nsstarcher/uchiwa\n====\n0.22" as sstarcher_uchiwa_0_22 #LightGreen
usecase "Image\n====\nDocker Hub\n====\nbitnami/redis\n====\n3.2.6-r2" as bitnami_redis_3_2_6_r2 #Khaki
usecase "Image\n====\nDocker Hub\n====\nsstarcher/sensu\n====\n0.28" as sstarcher_sensu_0_28 #GreenYellow

'Chart Dependencies
uchiwa_1_0_1--[#green]-|>sensu_0_1_2
sensu_0_1_2--[#green]-|>redis_0_4_5
uchiwa_1_0_1--[#orange]-|>sstarcher_uchiwa_0_22
redis_0_4_5--[#orange]-|>bitnami_redis_3_2_6_r2
sensu_0_1_2--[#orange]-|>sstarcher_sensu_0_28

center footer Generated on 2022/05/22 16:52:51 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
