@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for unifi:0.7.0

'There is one referenced Helm Chart
artifact "unifi:0.7.0\n====\n\tunifi\n====\n\t0.7.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: billimek, mcronce\n====\n\tKeywords: ubiquiti\nunifi\nmongodb" as unifi_0_7_0 #LightSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tjacobalberty/unifi\n====\n\t5.12.35" as jacobalberty_unifi_5_12_35 #Azure

'Chart Dependencies
unifi_0_7_0--[#orange]-|>jacobalberty_unifi_5_12_35

center footer Generated on 2020/04/26 14:02:43 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
