@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for verdaccio:0.7.5

'There is one referenced Helm Chart
artifact "verdaccio:0.7.5\n====\n\tverdaccio\n====\n\t0.7.5\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: etiennetremel\n====\n\tKeywords: npm\nnodejs" as verdaccio_0_7_5 #LightGray

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tverdaccio/verdaccio\n====\n\t3.11.6" as verdaccio_verdaccio_3_11_6 #Lavender

'Chart Dependencies
verdaccio_0_7_5--[#orange]-|>verdaccio_verdaccio_3_11_6

center footer Generated on 2020/03/16 17:32:15 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
