@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for wordpress:9.0.2

'There are 2 referenced Helm Charts
artifact "mariadb:7.3.12\n====\n\tmariadb\n====\n\t7.3.12\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: mariadb\nmysql\ndatabase\nsql\nprometheus" as mariadb_7_3_12 #DarkTurquoise
artifact "wordpress:9.0.2\n====\n\twordpress\n====\n\t9.0.2\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: \n====\n\tKeywords: wordpress\ncms\nblog\nhttp\nweb\napplication\nphp" as wordpress_9_0_2 #GreenYellow

'There are 2 referenced Docker Images
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/wordpress:5.3.2-debian-10-r32\n====\n\t5.3.2-debian-10-r32" as docker_io_bitnami_wordpress_5_3_2_debian_10_r32 #Darkorange
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/mariadb:10.3.22-debian-10-r27\n====\n\t10.3.22-debian-10-r27" as docker_io_bitnami_mariadb_10_3_22_debian_10_r27 #DarkGoldenRod

'Chart Dependencies
wordpress_9_0_2--[#green]-|>mariadb_7_3_12
mariadb_7_3_12--[#orange]-|>docker_io_bitnami_mariadb_10_3_22_debian_10_r27
wordpress_9_0_2--[#orange]-|>docker_io_bitnami_wordpress_5_3_2_debian_10_r32

center footer Generated on 2020/03/16 17:32:41 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
