@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for airflow:12.2.3

'There are 4 referenced Helm Charts
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "airflow:12.2.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tapache\n\t\tairflow\n\t\tworkflow\n\t\tdag" as airflow_12_2_3 #FloralWhite
artifact "postgresql:11.1.22\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_1_22 #LightSteelBlue
artifact "redis:16.8.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_16_8_7 #LightSeaGreen

'There are 5 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/airflow-scheduler:2.2.5-debian-10-r15\n====\n2.2.5-debian-10-r15" as docker_io_bitnami_airflow_scheduler_2_2_5_debian_10_r15 #LightCyan
usecase "Image\n====\ndocker.io\n====\nbitnami/redis:6.2.6-debian-10-r192\n====\n6.2.6-debian-10-r192" as docker_io_bitnami_redis_6_2_6_debian_10_r192 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.2.0-debian-10-r70\n====\n14.2.0-debian-10-r70" as docker_io_bitnami_postgresql_14_2_0_debian_10_r70 #DarkSalmon
usecase "Image\n====\ndocker.io\n====\nbitnami/airflow-worker:2.2.5-debian-10-r15\n====\n2.2.5-debian-10-r15" as docker_io_bitnami_airflow_worker_2_2_5_debian_10_r15 #AntiqueWhite
usecase "Image\n====\ndocker.io\n====\nbitnami/airflow:2.2.5-debian-10-r16\n====\n2.2.5-debian-10-r16" as docker_io_bitnami_airflow_2_2_5_debian_10_r16 #LightGoldenRodYellow

'Chart Dependencies
airflow_12_2_3--[#green]-|>postgresql_11_1_22
postgresql_11_1_22--[#green]-|>common_1_13_0
airflow_12_2_3--[#green]-|>redis_16_8_7
redis_16_8_7--[#green]-|>common_1_13_0
airflow_12_2_3--[#green]-|>common_1_13_0
airflow_12_2_3--[#orange]-|>docker_io_bitnami_airflow_2_2_5_debian_10_r16
airflow_12_2_3--[#orange]-|>docker_io_bitnami_airflow_scheduler_2_2_5_debian_10_r15
airflow_12_2_3--[#orange]-|>docker_io_bitnami_airflow_worker_2_2_5_debian_10_r15
postgresql_11_1_22--[#orange]-|>docker_io_bitnami_postgresql_14_2_0_debian_10_r70
redis_16_8_7--[#orange]-|>docker_io_bitnami_redis_6_2_6_debian_10_r192

center footer Generated on 2022/05/13 06:18:09 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
