@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for apache:9.1.18

'There are 2 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "apache:9.1.18\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tapache\n\t\thttp\n\t\thttps\n\t\twww\n\t\tweb\n\t\treverse proxy" as apache_9_1_18 #Ivory

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/apache:2.4.54-debian-11-r23\n====\n2.4.54-debian-11-r23" as docker_io_bitnami_apache_2_4_54_debian_11_r23 #AntiqueWhite

'Chart Dependencies
apache_9_1_18--[#green]-|>common_1_16_1
apache_9_1_18--[#orange]-|>docker_io_bitnami_apache_2_4_54_debian_11_r23

center footer Generated on 2022/08/12 01:36:30 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
