@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for argo-cd:3.2.4

'There are 3 referenced Helm Charts
artifact "common:1.13.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_1 #DarkSeaGreen
artifact "redis:16.9.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_16_9_3 #LightSeaGreen
artifact "argo-cd:3.2.4\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tContinuous delivery\n\t\tContinuous deployment\n\t\tDevops\n\t\tKubernetes" as argo_cd_3_2_4 #Ivory

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/redis:6.2.7-debian-10-r0\n====\n6.2.7-debian-10-r0" as docker_io_bitnami_redis_6_2_7_debian_10_r0 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/redis:6.2.7-debian-10-r15\n====\n6.2.7-debian-10-r15" as docker_io_bitnami_redis_6_2_7_debian_10_r15 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/argo-cd:2.3.3-debian-10-r32\n====\n2.3.3-debian-10-r32" as docker_io_bitnami_argo_cd_2_3_3_debian_10_r32 #Aqua

'Chart Dependencies
argo_cd_3_2_4--[#green]-|>common_1_13_1
argo_cd_3_2_4--[#green]-|>redis_16_9_3
redis_16_9_3--[#green]-|>common_1_13_1
redis_16_9_3--[#orange]-|>docker_io_bitnami_redis_6_2_7_debian_10_r0
redis_16_9_3--[#orange]-|>docker_io_bitnami_redis_6_2_7_debian_10_r15
argo_cd_3_2_4--[#orange]-|>docker_io_bitnami_argo_cd_2_3_3_debian_10_r32

center footer Generated on 2022/05/15 12:19:53 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
