@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for argo-workflows:2.3.10

'There are 4 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "mysql:9.2.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tcluster\n\t\thigh availability" as mysql_9_2_6 #Aqua
artifact "postgresql:11.6.26\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_6_26 #LightSteelBlue
artifact "argo-workflows:2.3.10\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tDevops\n\t\tKubernetes\n\t\tJobs\n\t\tContinuous delivery\n\t\tContinous deployment" as argo_workflows_2_3_10 #LavenderBlush

'There are 4 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mysql:8.0.30-debian-11-r6\n====\n8.0.30-debian-11-r6" as docker_io_bitnami_mysql_8_0_30_debian_11_r6 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/argo-workflow-controller:3.3.8-scratch-r5\n====\n3.3.8-scratch-r5" as docker_io_bitnami_argo_workflow_controller_3_3_8_scratch_r5 #Chocolate
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.4.0-debian-11-r23\n====\n14.4.0-debian-11-r23" as docker_io_bitnami_postgresql_14_4_0_debian_11_r23 #DarkSalmon
usecase "Image\n====\ndocker.io\n====\nbitnami/argo-workflow-cli:3.3.9-scratch-r0\n====\n3.3.9-scratch-r0" as docker_io_bitnami_argo_workflow_cli_3_3_9_scratch_r0 #DarkSeaGreen

'Chart Dependencies
argo_workflows_2_3_10--[#green]-|>common_1_16_1
argo_workflows_2_3_10--[#green]-|>postgresql_11_6_26
postgresql_11_6_26--[#green]-|>common_1_16_1
argo_workflows_2_3_10--[#green]-|>mysql_9_2_6
mysql_9_2_6--[#green]-|>common_1_16_1
mysql_9_2_6--[#orange]-|>docker_io_bitnami_mysql_8_0_30_debian_11_r6
postgresql_11_6_26--[#orange]-|>docker_io_bitnami_postgresql_14_4_0_debian_11_r23
argo_workflows_2_3_10--[#orange]-|>docker_io_bitnami_argo_workflow_controller_3_3_8_scratch_r5
argo_workflows_2_3_10--[#orange]-|>docker_io_bitnami_argo_workflow_cli_3_3_9_scratch_r0

center footer Generated on 2022/08/12 01:37:04 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
