@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for argo-workflows:1.1.14

'There are 4 referenced Helm Charts
artifact "common:1.13.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_1 #DarkSeaGreen
artifact "argo-workflows:1.1.14\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tDevops\n\t\tKubernetes\n\t\tJobs\n\t\tContinuous delivery\n\t\tContinous deployment" as argo_workflows_1_1_14 #LavenderBlush
artifact "mysql:8.9.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tcluster\n\t\thigh availability" as mysql_8_9_6 #Aqua
artifact "postgresql:11.1.26\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_1_26 #LightSteelBlue

'There are 4 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/argo-workflow-cli:3.3.5-scratch-r0\n====\n3.3.5-scratch-r0" as docker_io_bitnami_argo_workflow_cli_3_3_5_scratch_r0 #DarkSeaGreen
usecase "Image\n====\ndocker.io\n====\nbitnami/argo-workflow-controller:3.3.5-scratch-r0\n====\n3.3.5-scratch-r0" as docker_io_bitnami_argo_workflow_controller_3_3_5_scratch_r0 #Chocolate
usecase "Image\n====\ndocker.io\n====\nbitnami/mysql:8.0.29-debian-10-r2\n====\n8.0.29-debian-10-r2" as docker_io_bitnami_mysql_8_0_29_debian_10_r2 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.2.0-debian-10-r85\n====\n14.2.0-debian-10-r85" as docker_io_bitnami_postgresql_14_2_0_debian_10_r85 #DarkSalmon

'Chart Dependencies
argo_workflows_1_1_14--[#green]-|>postgresql_11_1_26
postgresql_11_1_26--[#green]-|>common_1_13_1
argo_workflows_1_1_14--[#green]-|>common_1_13_1
argo_workflows_1_1_14--[#green]-|>mysql_8_9_6
mysql_8_9_6--[#green]-|>common_1_13_1
argo_workflows_1_1_14--[#orange]-|>docker_io_bitnami_argo_workflow_cli_3_3_5_scratch_r0
argo_workflows_1_1_14--[#orange]-|>docker_io_bitnami_argo_workflow_controller_3_3_5_scratch_r0
mysql_8_9_6--[#orange]-|>docker_io_bitnami_mysql_8_0_29_debian_10_r2
postgresql_11_1_26--[#orange]-|>docker_io_bitnami_postgresql_14_2_0_debian_10_r85

center footer Generated on 2022/05/13 06:19:10 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
