@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for bitnami-common:0.0.5

'There is one referenced Helm Chart
artifact "bitnami-common:0.0.5\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\thelper\n\t\ttemplate\n\t\tbitnami\n\t\tbroker\n\t\tservice\n\t\tcatalog" as bitnami_common_0_0_5 #Aquamarine

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/06/02 03:07:22 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
