@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for cassandra:9.1.23

'There are 2 referenced Helm Charts
artifact "cassandra:9.1.23\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcassandra\n\t\tdatabase\n\t\tnosql" as cassandra_9_1_23 #Gainsboro
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/cassandra:4.0.4-debian-10-r3\n====\n4.0.4-debian-10-r3" as docker_io_bitnami_cassandra_4_0_4_debian_10_r3 #Khaki

'Chart Dependencies
cassandra_9_1_23--[#green]-|>common_1_14_1
cassandra_9_1_23--[#orange]-|>docker_io_bitnami_cassandra_4_0_4_debian_10_r3

center footer Generated on 2022/05/22 15:23:38 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
