@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for cert-manager:0.4.17

'There are 2 referenced Helm Charts
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "cert-manager:0.4.17\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tgo\n\t\tsecurity\n\t\ttls\n\t\tcertificate" as cert_manager_0_4_17 #Cornsilk

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/cert-manager-webhook:1.8.0-debian-10-r12\n====\n1.8.0-debian-10-r12" as docker_io_bitnami_cert_manager_webhook_1_8_0_debian_10_r12 #AntiqueWhite
usecase "Image\n====\ndocker.io\n====\nbitnami/cainjector:1.8.0-debian-10-r13\n====\n1.8.0-debian-10-r13" as docker_io_bitnami_cainjector_1_8_0_debian_10_r13 #LemonChiffon
usecase "Image\n====\ndocker.io\n====\nbitnami/cert-manager:1.8.0-debian-10-r13\n====\n1.8.0-debian-10-r13" as docker_io_bitnami_cert_manager_1_8_0_debian_10_r13 #Gold

'Chart Dependencies
cert_manager_0_4_17--[#green]-|>common_1_13_0
cert_manager_0_4_17--[#orange]-|>docker_io_bitnami_cert_manager_webhook_1_8_0_debian_10_r12
cert_manager_0_4_17--[#orange]-|>docker_io_bitnami_cainjector_1_8_0_debian_10_r13
cert_manager_0_4_17--[#orange]-|>docker_io_bitnami_cert_manager_1_8_0_debian_10_r13

center footer Generated on 2022/05/13 06:20:14 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
