@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for concourse:1.0.16

'There are 3 referenced Helm Charts
artifact "concourse:1.0.16\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tconcourse\n\t\tci\n\t\tcd\n\t\thttp\n\t\tweb\n\t\tapplication" as concourse_1_0_16 #GreenYellow
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "postgresql:11.1.20\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_1_20 #LightSteelBlue

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.2.0-debian-10-r67\n====\n14.2.0-debian-10-r67" as docker_io_bitnami_postgresql_14_2_0_debian_10_r67 #DarkSalmon

'Chart Dependencies
concourse_1_0_16--[#green]-|>common_1_13_0
concourse_1_0_16--[#green]-|>postgresql_11_1_20
postgresql_11_1_20--[#green]-|>common_1_13_0
postgresql_11_1_20--[#orange]-|>docker_io_bitnami_postgresql_14_2_0_debian_10_r67

center footer Generated on 2022/05/07 15:22:36 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
