@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for contour:9.0.1

'There are 2 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "contour:9.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tcellebyte\n\t\tBitnami\n====\n\tKeywords: \n\t\tingress\n\t\tenvoy\n\t\tcontour" as contour_9_0_1 #DodgerBlue

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/contour:1.22.0-debian-11-r1\n====\n1.22.0-debian-11-r1" as docker_io_bitnami_contour_1_22_0_debian_11_r1 #CornflowerBlue

'Chart Dependencies
contour_9_0_1--[#green]-|>common_1_16_1
contour_9_0_1--[#orange]-|>docker_io_bitnami_contour_1_22_0_debian_11_r1

center footer Generated on 2022/08/12 01:38:53 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
