@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for contour-operator:2.0.0

'There are 2 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "contour-operator:2.0.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcontour\n\t\toperator\n\t\tingress\n\t\tenvoy" as contour_operator_2_0_0 #Bisque

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/contour-operator:1.22.0-scratch-r0\n====\n1.22.0-scratch-r0" as docker_io_bitnami_contour_operator_1_22_0_scratch_r0 #Khaki

'Chart Dependencies
contour_operator_2_0_0--[#green]-|>common_1_16_1
contour_operator_2_0_0--[#orange]-|>docker_io_bitnami_contour_operator_1_22_0_scratch_r0

center footer Generated on 2022/08/12 01:39:07 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
