@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for contour:7.8.0

'There are 2 referenced Helm Charts
artifact "contour:7.8.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tcellebyte\n\t\tBitnami\n====\n\tKeywords: \n\t\tingress\n\t\tenvoy\n\t\tcontour" as contour_7_8_0 #DodgerBlue
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/contour:1.20.1-debian-10-r53\n====\n1.20.1-debian-10-r53" as docker_io_bitnami_contour_1_20_1_debian_10_r53 #CornflowerBlue

'Chart Dependencies
contour_7_8_0--[#green]-|>common_1_13_0
contour_7_8_0--[#orange]-|>docker_io_bitnami_contour_1_20_1_debian_10_r53

center footer Generated on 2022/05/15 12:22:31 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
