@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for dataplatform-bp2:12.0.2

'There are 10 referenced Helm Charts
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "spark:5.9.8\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tapache\n\t\tspark" as spark_5_9_8 #LightSeaGreen
artifact "kube-state-metrics:2.2.14\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tprometheus\n\t\tkube-state-metrics\n\t\tmonitoring" as kube_state_metrics_2_2_14 #Gainsboro
artifact "kafka:16.2.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tkafka\n\t\tzookeeper\n\t\tstreaming\n\t\tproducer\n\t\tconsumer" as kafka_16_2_3 #Aqua
artifact "dataplatform-bp2:12.0.2\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tdataplatform\n\t\tkafka\n\t\tspark\n\t\telasticsearch\n\t\tlogstash\n\t\tkibana\n\t\tzookeeper\n\t\tapache\n\t\ttanzuobservability\n\t\twavefront" as dataplatform_bp2_12_0_2 #BurlyWood
artifact "zookeeper:9.0.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: zookeeper" as zookeeper_9_0_3 #LemonChiffon
artifact "logstash:3.8.8\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tlogstash\n\t\tlogging\n\t\telk" as logstash_3_8_8 #Aqua
artifact "wavefront:3.3.2\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmetric\n\t\tmonitoring\n\t\tobservability\n\t\talerting" as wavefront_3_3_2 #LavenderBlush
artifact "kibana:9.3.15\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tkibana\n\t\tanalytics\n\t\tmonitoring\n\t\tmetrics\n\t\tlogs" as kibana_9_3_15 #GhostWhite
artifact "elasticsearch:17.9.24\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: elasticsearch" as elasticsearch_17_9_24 #Aquamarine

'There are 9 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/logstash:7.17.2-debian-10-r5\n====\n7.17.2-debian-10-r5" as docker_io_bitnami_logstash_7_17_2_debian_10_r5 #Beige
usecase "Image\n====\ndocker.io\n====\nbitnami/elasticsearch:7.17.2-debian-10-r3\n====\n7.17.2-debian-10-r3" as docker_io_bitnami_elasticsearch_7_17_2_debian_10_r3 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/zookeeper:3.8.0-debian-10-r16\n====\n3.8.0-debian-10-r16" as docker_io_bitnami_zookeeper_3_8_0_debian_10_r16 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/spark:3.2.1-debian-10-r64\n====\n3.2.1-debian-10-r64" as docker_io_bitnami_spark_3_2_1_debian_10_r64 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/kube-state-metrics:2.4.2-debian-10-r18\n====\n2.4.2-debian-10-r18" as docker_io_bitnami_kube_state_metrics_2_4_2_debian_10_r18 #CornflowerBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/kafka:3.1.0-debian-10-r68\n====\n3.1.0-debian-10-r68" as docker_io_bitnami_kafka_3_1_0_debian_10_r68 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/wavefront-proxy:11.0.0-debian-10-r4\n====\n11.0.0-debian-10-r4" as docker_io_bitnami_wavefront_proxy_11_0_0_debian_10_r4 #Cyan
usecase "Image\n====\ndocker.io\n====\nbitnami/dataplatform-exporter:1.0.1-scratch-r22\n====\n1.0.1-scratch-r22" as docker_io_bitnami_dataplatform_exporter_1_0_1_scratch_r22 #Fuchsia
usecase "Image\n====\ndocker.io\n====\nbitnami/dataplatform-emitter:1.0.1-scratch-r26\n====\n1.0.1-scratch-r26" as docker_io_bitnami_dataplatform_emitter_1_0_1_scratch_r26 #DarkSalmon

'Chart Dependencies
dataplatform_bp2_12_0_2--[#green]-|>kafka_16_2_3
kafka_16_2_3--[#green]-|>zookeeper_9_0_3
zookeeper_9_0_3--[#green]-|>common_1_13_0
kafka_16_2_3--[#green]-|>common_1_13_0
dataplatform_bp2_12_0_2--[#green]-|>wavefront_3_3_2
wavefront_3_3_2--[#green]-|>kube_state_metrics_2_2_14
kube_state_metrics_2_2_14--[#green]-|>common_1_13_0
wavefront_3_3_2--[#green]-|>common_1_13_0
dataplatform_bp2_12_0_2--[#green]-|>spark_5_9_8
spark_5_9_8--[#green]-|>common_1_13_0
dataplatform_bp2_12_0_2--[#green]-|>elasticsearch_17_9_24
elasticsearch_17_9_24--[#green]-|>common_1_13_0
elasticsearch_17_9_24--[#green]-|>kibana_9_3_15
kibana_9_3_15--[#green]-|>common_1_13_0
dataplatform_bp2_12_0_2--[#green]-|>logstash_3_8_8
logstash_3_8_8--[#green]-|>common_1_13_0
dataplatform_bp2_12_0_2--[#green]-|>common_1_13_0
spark_5_9_8--[#orange]-|>docker_io_bitnami_spark_3_2_1_debian_10_r64
kube_state_metrics_2_2_14--[#orange]-|>docker_io_bitnami_kube_state_metrics_2_4_2_debian_10_r18
kafka_16_2_3--[#orange]-|>docker_io_bitnami_kafka_3_1_0_debian_10_r68
dataplatform_bp2_12_0_2--[#orange]-|>docker_io_bitnami_dataplatform_emitter_1_0_1_scratch_r26
dataplatform_bp2_12_0_2--[#orange]-|>docker_io_bitnami_dataplatform_exporter_1_0_1_scratch_r22
zookeeper_9_0_3--[#orange]-|>docker_io_bitnami_zookeeper_3_8_0_debian_10_r16
logstash_3_8_8--[#orange]-|>docker_io_bitnami_logstash_7_17_2_debian_10_r5
wavefront_3_3_2--[#orange]-|>docker_io_bitnami_wavefront_proxy_11_0_0_debian_10_r4
elasticsearch_17_9_24--[#orange]-|>docker_io_bitnami_elasticsearch_7_17_2_debian_10_r3

center footer Generated on 2022/06/15 22:19:24 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
