@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for discourse:7.3.5

'There are 4 referenced Helm Charts
artifact "discourse:7.3.5\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tpaulczar\n\t\tlucaprete\n====\n\tKeywords: \n\t\tcommunity\n\t\tforum" as discourse_7_3_5 #LightSeaGreen
artifact "postgresql:11.6.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_6_6 #LightSteelBlue
artifact "redis:16.12.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_16_12_1 #LightSeaGreen
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/redis:6.2.7-debian-11-r3\n====\n6.2.7-debian-11-r3" as docker_io_bitnami_redis_6_2_7_debian_11_r3 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.3.0-debian-11-r3\n====\n14.3.0-debian-11-r3" as docker_io_bitnami_postgresql_14_3_0_debian_11_r3 #DarkSalmon

'Chart Dependencies
discourse_7_3_5--[#green]-|>postgresql_11_6_6
postgresql_11_6_6--[#green]-|>common_1_16_0
discourse_7_3_5--[#green]-|>common_1_16_0
discourse_7_3_5--[#green]-|>redis_16_12_1
redis_16_12_1--[#green]-|>common_1_16_0
postgresql_11_6_6--[#orange]-|>docker_io_bitnami_postgresql_14_3_0_debian_11_r3
redis_16_12_1--[#orange]-|>docker_io_bitnami_redis_6_2_7_debian_11_r3

center footer Generated on 2022/06/15 22:20:00 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
