@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for dokuwiki:12.5.9

'There are 2 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "dokuwiki:12.5.9\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tdokuwiki\n\t\twiki\n\t\thttp\n\t\tweb\n\t\tapplication\n\t\tphp" as dokuwiki_12_5_9 #Gainsboro

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/dokuwiki:20200729.0.0-debian-11-r21\n====\n20200729.0.0-debian-11-r21" as docker_io_bitnami_dokuwiki_20200729_0_0_debian_11_r21 #GoldenRod

'Chart Dependencies
dokuwiki_12_5_9--[#green]-|>common_1_16_1
dokuwiki_12_5_9--[#orange]-|>docker_io_bitnami_dokuwiki_20200729_0_0_debian_11_r21

center footer Generated on 2022/08/12 01:41:09 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
