@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for ejbca:5.1.13

'There are 3 referenced Helm Charts
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "ejbca:5.1.13\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tejbca\n\t\tca\n\t\tpki\n\t\tcertificate" as ejbca_5_1_13 #LightSeaGreen
artifact "mariadb:10.5.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_10_5_1 #DarkTurquoise

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.5.15-debian-10-r62\n====\n10.5.15-debian-10-r62" as docker_io_bitnami_mariadb_10_5_15_debian_10_r62 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/ejbca:7.4.3-2-debian-10-r144\n====\n7.4.3-2-debian-10-r144" as docker_io_bitnami_ejbca_7_4_3_2_debian_10_r144 #Azure

'Chart Dependencies
ejbca_5_1_13--[#green]-|>mariadb_10_5_1
mariadb_10_5_1--[#green]-|>common_1_13_0
ejbca_5_1_13--[#green]-|>common_1_13_0
ejbca_5_1_13--[#orange]-|>docker_io_bitnami_ejbca_7_4_3_2_debian_10_r144
mariadb_10_5_1--[#orange]-|>docker_io_bitnami_mariadb_10_5_15_debian_10_r62

center footer Generated on 2022/05/13 06:24:02 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
