@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for ejbca:6.0.1

'There are 3 referenced Helm Charts
artifact "ejbca:6.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tejbca\n\t\tca\n\t\tpki\n\t\tcertificate" as ejbca_6_0_1 #LightSeaGreen
artifact "mariadb:11.0.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_0_0 #DarkTurquoise
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.7-debian-10-r62\n====\n10.6.7-debian-10-r62" as docker_io_bitnami_mariadb_10_6_7_debian_10_r62 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/ejbca:7.4.3-2-debian-10-r146\n====\n7.4.3-2-debian-10-r146" as docker_io_bitnami_ejbca_7_4_3_2_debian_10_r146 #Azure

'Chart Dependencies
ejbca_6_0_1--[#green]-|>mariadb_11_0_0
mariadb_11_0_0--[#green]-|>common_1_13_0
ejbca_6_0_1--[#green]-|>common_1_13_0
ejbca_6_0_1--[#orange]-|>docker_io_bitnami_ejbca_7_4_3_2_debian_10_r146
mariadb_11_0_0--[#orange]-|>docker_io_bitnami_mariadb_10_6_7_debian_10_r62

center footer Generated on 2022/05/07 15:25:49 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
