@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for elasticsearch:18.2.3

'There are 3 referenced Helm Charts
artifact "elasticsearch:18.2.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: elasticsearch" as elasticsearch_18_2_3 #Aquamarine
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen
artifact "kibana:10.1.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tkibana\n\t\tanalytics\n\t\tmonitoring\n\t\tmetrics\n\t\tlogs" as kibana_10_1_7 #GhostWhite

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/elasticsearch:8.2.1-debian-10-r1\n====\n8.2.1-debian-10-r1" as docker_io_bitnami_elasticsearch_8_2_1_debian_10_r1 #Azure

'Chart Dependencies
elasticsearch_18_2_3--[#green]-|>kibana_10_1_7
kibana_10_1_7--[#green]-|>common_1_14_1
elasticsearch_18_2_3--[#green]-|>common_1_14_1
elasticsearch_18_2_3--[#orange]-|>docker_io_bitnami_elasticsearch_8_2_1_debian_10_r1

center footer Generated on 2022/06/02 03:11:54 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
