@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for elasticsearch:18.2.13

'There are 3 referenced Helm Charts
artifact "elasticsearch:18.2.13\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: elasticsearch" as elasticsearch_18_2_13 #Aquamarine
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen
artifact "kibana:10.1.11\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tkibana\n\t\tanalytics\n\t\tmonitoring\n\t\tmetrics\n\t\tlogs" as kibana_10_1_11 #GhostWhite

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/elasticsearch:8.2.3-debian-11-r0\n====\n8.2.3-debian-11-r0" as docker_io_bitnami_elasticsearch_8_2_3_debian_11_r0 #Azure

'Chart Dependencies
elasticsearch_18_2_13--[#green]-|>kibana_10_1_11
kibana_10_1_11--[#green]-|>common_1_16_0
elasticsearch_18_2_13--[#green]-|>common_1_16_0
elasticsearch_18_2_13--[#orange]-|>docker_io_bitnami_elasticsearch_8_2_3_debian_11_r0

center footer Generated on 2022/06/15 22:20:42 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
