@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for etcd:8.2.6

'There are 2 referenced Helm Charts
artifact "etcd:8.2.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tetcd\n\t\tcluster\n\t\tdatabase\n\t\tcache\n\t\tkey-value" as etcd_8_2_6 #AliceBlue
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/etcd:3.5.4-debian-11-r3\n====\n3.5.4-debian-11-r3" as docker_io_bitnami_etcd_3_5_4_debian_11_r3 #Cornsilk

'Chart Dependencies
etcd_8_2_6--[#green]-|>common_1_16_0
etcd_8_2_6--[#orange]-|>docker_io_bitnami_etcd_3_5_4_debian_11_r3

center footer Generated on 2022/06/15 22:21:34 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
