@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for geode:0.4.18

'There are 2 referenced Helm Charts
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "geode:0.4.18\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tapache\n\t\tgeode\n\t\tdatabase" as geode_0_4_18 #Aqua

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/geode:1.14.4-debian-10-r20\n====\n1.14.4-debian-10-r20" as docker_io_bitnami_geode_1_14_4_debian_10_r20 #LightPink

'Chart Dependencies
geode_0_4_18--[#green]-|>common_1_13_0
geode_0_4_18--[#orange]-|>docker_io_bitnami_geode_1_14_4_debian_10_r20

center footer Generated on 2022/05/13 06:25:59 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
