@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for grafana-tempo:1.2.3

'There are 4 referenced Helm Charts
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen
artifact "grafana-tempo:1.2.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tgrafana\n\t\ttracing\n\t\tmetrics\n\t\tinfrastructure" as grafana_tempo_1_2_3 #Ivory
artifact "memcached:6.1.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmemcached\n\t\tcache" as memcached_6_1_1 #DarkSeaGreen

'There are 4 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo-vulture:1.4.1-debian-11-r0\n====\n1.4.1-debian-11-r0" as docker_io_bitnami_grafana_tempo_vulture_1_4_1_debian_11_r0 #Beige
usecase "Image\n====\ndocker.io\n====\nbitnami/memcached:1.6.15-debian-10-r50\n====\n1.6.15-debian-10-r50" as docker_io_bitnami_memcached_1_6_15_debian_10_r50 #CadetBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo:1.4.1-debian-11-r0\n====\n1.4.1-debian-11-r0" as docker_io_bitnami_grafana_tempo_1_4_1_debian_11_r0 #Gainsboro
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo-query:1.4.1-debian-11-r0\n====\n1.4.1-debian-11-r0" as docker_io_bitnami_grafana_tempo_query_1_4_1_debian_11_r0 #LightGrey

'Chart Dependencies
grafana_tempo_1_2_3--[#green]-|>common_1_16_0
grafana_tempo_1_2_3--[#green]-|>memcached_6_1_1
memcached_6_1_1--[#green]-|>common_1_14_1
grafana_tempo_1_2_3--[#orange]-|>docker_io_bitnami_grafana_tempo_vulture_1_4_1_debian_11_r0
grafana_tempo_1_2_3--[#orange]-|>docker_io_bitnami_grafana_tempo_query_1_4_1_debian_11_r0
grafana_tempo_1_2_3--[#orange]-|>docker_io_bitnami_grafana_tempo_1_4_1_debian_11_r0
memcached_6_1_1--[#orange]-|>docker_io_bitnami_memcached_1_6_15_debian_10_r50

center footer Generated on 2022/06/15 22:23:51 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
