@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for grafana-tempo:1.1.4

'There are 4 referenced Helm Charts
artifact "common:1.13.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_1 #DarkSeaGreen
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "memcached:6.0.17\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmemcached\n\t\tcache" as memcached_6_0_17 #DarkSeaGreen
artifact "grafana-tempo:1.1.4\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tgrafana\n\t\ttracing\n\t\tmetrics\n\t\tinfrastructure" as grafana_tempo_1_1_4 #Ivory

'There are 4 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo-vulture:1.4.0-debian-10-r3\n====\n1.4.0-debian-10-r3" as docker_io_bitnami_grafana_tempo_vulture_1_4_0_debian_10_r3 #Beige
usecase "Image\n====\ndocker.io\n====\nbitnami/memcached:1.6.15-debian-10-r20\n====\n1.6.15-debian-10-r20" as docker_io_bitnami_memcached_1_6_15_debian_10_r20 #CadetBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo:1.4.0-debian-10-r0\n====\n1.4.0-debian-10-r0" as docker_io_bitnami_grafana_tempo_1_4_0_debian_10_r0 #Gainsboro
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo-query:1.4.0-debian-10-r3\n====\n1.4.0-debian-10-r3" as docker_io_bitnami_grafana_tempo_query_1_4_0_debian_10_r3 #LightGrey

'Chart Dependencies
grafana_tempo_1_1_4--[#green]-|>memcached_6_0_17
memcached_6_0_17--[#green]-|>common_1_13_0
grafana_tempo_1_1_4--[#green]-|>common_1_13_1
memcached_6_0_17--[#orange]-|>docker_io_bitnami_memcached_1_6_15_debian_10_r20
grafana_tempo_1_1_4--[#orange]-|>docker_io_bitnami_grafana_tempo_1_4_0_debian_10_r0
grafana_tempo_1_1_4--[#orange]-|>docker_io_bitnami_grafana_tempo_query_1_4_0_debian_10_r3
grafana_tempo_1_1_4--[#orange]-|>docker_io_bitnami_grafana_tempo_vulture_1_4_0_debian_10_r3

center footer Generated on 2022/05/13 06:26:54 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
