@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for grafana-tempo:1.1.3

'There are 3 referenced Helm Charts
artifact "memcached:6.0.16\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmemcached\n\t\tcache" as memcached_6_0_16 #DarkSeaGreen
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "grafana-tempo:1.1.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tgrafana\n\t\ttracing\n\t\tmetrics\n\t\tinfrastructure" as grafana_tempo_1_1_3 #Ivory

'There are 4 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo-query:1.3.2-debian-10-r55\n====\n1.3.2-debian-10-r55" as docker_io_bitnami_grafana_tempo_query_1_3_2_debian_10_r55 #LightGrey
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo:1.3.2-debian-10-r52\n====\n1.3.2-debian-10-r52" as docker_io_bitnami_grafana_tempo_1_3_2_debian_10_r52 #Gainsboro
usecase "Image\n====\ndocker.io\n====\nbitnami/memcached:1.6.15-debian-10-r20\n====\n1.6.15-debian-10-r20" as docker_io_bitnami_memcached_1_6_15_debian_10_r20 #CadetBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo-vulture:1.3.2-debian-10-r57\n====\n1.3.2-debian-10-r57" as docker_io_bitnami_grafana_tempo_vulture_1_3_2_debian_10_r57 #Beige

'Chart Dependencies
grafana_tempo_1_1_3--[#green]-|>memcached_6_0_16
memcached_6_0_16--[#green]-|>common_1_13_0
grafana_tempo_1_1_3--[#green]-|>common_1_13_0
memcached_6_0_16--[#orange]-|>docker_io_bitnami_memcached_1_6_15_debian_10_r20
grafana_tempo_1_1_3--[#orange]-|>docker_io_bitnami_grafana_tempo_vulture_1_3_2_debian_10_r57
grafana_tempo_1_1_3--[#orange]-|>docker_io_bitnami_grafana_tempo_query_1_3_2_debian_10_r55
grafana_tempo_1_1_3--[#orange]-|>docker_io_bitnami_grafana_tempo_1_3_2_debian_10_r52

center footer Generated on 2022/05/13 06:27:01 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
