@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for grafana-tempo:1.1.10

'There are 3 referenced Helm Charts
artifact "memcached:6.0.22\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmemcached\n\t\tcache" as memcached_6_0_22 #DarkSeaGreen
artifact "grafana-tempo:1.1.10\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tgrafana\n\t\ttracing\n\t\tmetrics\n\t\tinfrastructure" as grafana_tempo_1_1_10 #Ivory
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen

'There are 4 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/memcached:1.6.15-debian-10-r50\n====\n1.6.15-debian-10-r50" as docker_io_bitnami_memcached_1_6_15_debian_10_r50 #CadetBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo:1.4.1-debian-10-r17\n====\n1.4.1-debian-10-r17" as docker_io_bitnami_grafana_tempo_1_4_1_debian_10_r17 #Gainsboro
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo-vulture:1.4.1-debian-10-r18\n====\n1.4.1-debian-10-r18" as docker_io_bitnami_grafana_tempo_vulture_1_4_1_debian_10_r18 #Beige
usecase "Image\n====\ndocker.io\n====\nbitnami/grafana-tempo-query:1.4.1-debian-10-r18\n====\n1.4.1-debian-10-r18" as docker_io_bitnami_grafana_tempo_query_1_4_1_debian_10_r18 #LightGrey

'Chart Dependencies
grafana_tempo_1_1_10--[#green]-|>common_1_14_1
grafana_tempo_1_1_10--[#green]-|>memcached_6_0_22
memcached_6_0_22--[#green]-|>common_1_14_1
memcached_6_0_22--[#orange]-|>docker_io_bitnami_memcached_1_6_15_debian_10_r50
grafana_tempo_1_1_10--[#orange]-|>docker_io_bitnami_grafana_tempo_vulture_1_4_1_debian_10_r18
grafana_tempo_1_1_10--[#orange]-|>docker_io_bitnami_grafana_tempo_query_1_4_1_debian_10_r18
grafana_tempo_1_1_10--[#orange]-|>docker_io_bitnami_grafana_tempo_1_4_1_debian_10_r17

center footer Generated on 2022/05/30 22:09:00 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
