@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for harbor:13.1.3

'There are 4 referenced Helm Charts
artifact "redis:16.9.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_16_9_7 #LightSeaGreen
artifact "postgresql:11.2.4\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_2_4 #LightSteelBlue
artifact "harbor:13.1.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tdocker\n\t\tregistry\n\t\tvulnerability\n\t\tscan" as harbor_13_1_3 #GreenYellow
artifact "common:1.14.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_0 #DarkSeaGreen

'There are 12 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/harbor-jobservice:2.5.0-debian-10-r30\n====\n2.5.0-debian-10-r30" as docker_io_bitnami_harbor_jobservice_2_5_0_debian_10_r30 #Ivory
usecase "Image\n====\ndocker.io\n====\nbitnami/chartmuseum:0.14.0-debian-10-r105\n====\n0.14.0-debian-10-r105" as docker_io_bitnami_chartmuseum_0_14_0_debian_10_r105 #LawnGreen
usecase "Image\n====\ndocker.io\n====\nbitnami/harbor-notary-server:2.5.0-debian-10-r38\n====\n2.5.0-debian-10-r38" as docker_io_bitnami_harbor_notary_server_2_5_0_debian_10_r38 #LightSkyBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/harbor-registryctl:2.5.0-debian-10-r38\n====\n2.5.0-debian-10-r38" as docker_io_bitnami_harbor_registryctl_2_5_0_debian_10_r38 #Cyan
usecase "Image\n====\ndocker.io\n====\nbitnami/harbor-portal:2.5.0-debian-10-r38\n====\n2.5.0-debian-10-r38" as docker_io_bitnami_harbor_portal_2_5_0_debian_10_r38 #Ivory
usecase "Image\n====\ndocker.io\n====\nbitnami/harbor-registry:2.5.0-debian-10-r38\n====\n2.5.0-debian-10-r38" as docker_io_bitnami_harbor_registry_2_5_0_debian_10_r38 #DarkSeaGreen
usecase "Image\n====\ndocker.io\n====\nbitnami/harbor-adapter-trivy:2.5.0-debian-10-r39\n====\n2.5.0-debian-10-r39" as docker_io_bitnami_harbor_adapter_trivy_2_5_0_debian_10_r39 #LavenderBlush
usecase "Image\n====\ndocker.io\n====\nbitnami/harbor-core:2.5.0-debian-10-r39\n====\n2.5.0-debian-10-r39" as docker_io_bitnami_harbor_core_2_5_0_debian_10_r39 #Darkorange
usecase "Image\n====\ndocker.io\n====\nbitnami/redis:6.2.7-debian-10-r20\n====\n6.2.7-debian-10-r20" as docker_io_bitnami_redis_6_2_7_debian_10_r20 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/harbor-notary-signer:2.5.0-debian-10-r38\n====\n2.5.0-debian-10-r38" as docker_io_bitnami_harbor_notary_signer_2_5_0_debian_10_r38 #AntiqueWhite
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:13.7.0-debian-10-r6\n====\n13.7.0-debian-10-r6" as docker_io_bitnami_postgresql_13_7_0_debian_10_r6 #DarkSalmon
usecase "Image\n====\ndocker.io\n====\nbitnami/nginx:1.21.6-debian-10-r112\n====\n1.21.6-debian-10-r112" as docker_io_bitnami_nginx_1_21_6_debian_10_r112 #LightPink

'Chart Dependencies
harbor_13_1_3--[#green]-|>redis_16_9_7
redis_16_9_7--[#green]-|>common_1_14_0
harbor_13_1_3--[#green]-|>common_1_14_0
harbor_13_1_3--[#green]-|>postgresql_11_2_4
postgresql_11_2_4--[#green]-|>common_1_14_0
redis_16_9_7--[#orange]-|>docker_io_bitnami_redis_6_2_7_debian_10_r20
postgresql_11_2_4--[#orange]-|>docker_io_bitnami_postgresql_13_7_0_debian_10_r6
harbor_13_1_3--[#orange]-|>docker_io_bitnami_harbor_jobservice_2_5_0_debian_10_r30
harbor_13_1_3--[#orange]-|>docker_io_bitnami_chartmuseum_0_14_0_debian_10_r105
harbor_13_1_3--[#orange]-|>docker_io_bitnami_harbor_adapter_trivy_2_5_0_debian_10_r39
harbor_13_1_3--[#orange]-|>docker_io_bitnami_nginx_1_21_6_debian_10_r112
harbor_13_1_3--[#orange]-|>docker_io_bitnami_harbor_portal_2_5_0_debian_10_r38
harbor_13_1_3--[#orange]-|>docker_io_bitnami_harbor_notary_server_2_5_0_debian_10_r38
harbor_13_1_3--[#orange]-|>docker_io_bitnami_harbor_registry_2_5_0_debian_10_r38
harbor_13_1_3--[#orange]-|>docker_io_bitnami_harbor_registryctl_2_5_0_debian_10_r38
harbor_13_1_3--[#orange]-|>docker_io_bitnami_harbor_notary_signer_2_5_0_debian_10_r38
harbor_13_1_3--[#orange]-|>docker_io_bitnami_harbor_core_2_5_0_debian_10_r39

center footer Generated on 2022/05/22 15:31:34 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
