@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for jasperreports:14.0.1

'There are 3 referenced Helm Charts
artifact "mariadb:11.0.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_0_0 #DarkTurquoise
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "jasperreports:14.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tbusiness intelligence\n\t\tjava\n\t\tjasper\n\t\treporting\n\t\tanalytic\n\t\tvisualization" as jasperreports_14_0_1 #LightGrey

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/jasperreports:8.0.0-debian-10-r33\n====\n8.0.0-debian-10-r33" as docker_io_bitnami_jasperreports_8_0_0_debian_10_r33 #LawnGreen
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.7-debian-10-r62\n====\n10.6.7-debian-10-r62" as docker_io_bitnami_mariadb_10_6_7_debian_10_r62 #DarkGoldenRod

'Chart Dependencies
jasperreports_14_0_1--[#green]-|>common_1_13_0
jasperreports_14_0_1--[#green]-|>mariadb_11_0_0
mariadb_11_0_0--[#green]-|>common_1_13_0
mariadb_11_0_0--[#orange]-|>docker_io_bitnami_mariadb_10_6_7_debian_10_r62
jasperreports_14_0_1--[#orange]-|>docker_io_bitnami_jasperreports_8_0_0_debian_10_r33

center footer Generated on 2022/05/07 15:30:14 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
