@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for jasperreports:14.1.16

'There are 3 referenced Helm Charts
artifact "mariadb:11.1.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_1_6 #DarkTurquoise
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "jasperreports:14.1.16\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tbusiness intelligence\n\t\tjava\n\t\tjasper\n\t\treporting\n\t\tanalytic\n\t\tvisualization" as jasperreports_14_1_16 #LightGrey

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.8-debian-11-r23\n====\n10.6.8-debian-11-r23" as docker_io_bitnami_mariadb_10_6_8_debian_11_r23 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/jasperreports:8.0.2-debian-11-r21\n====\n8.0.2-debian-11-r21" as docker_io_bitnami_jasperreports_8_0_2_debian_11_r21 #LawnGreen

'Chart Dependencies
jasperreports_14_1_16--[#green]-|>mariadb_11_1_6
mariadb_11_1_6--[#green]-|>common_1_16_1
jasperreports_14_1_16--[#green]-|>common_1_16_1
mariadb_11_1_6--[#orange]-|>docker_io_bitnami_mariadb_10_6_8_debian_11_r23
jasperreports_14_1_16--[#orange]-|>docker_io_bitnami_jasperreports_8_0_2_debian_11_r21

center footer Generated on 2022/08/12 01:46:57 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
