@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for jupyterhub:1.3.0

'There are 3 referenced Helm Charts
artifact "jupyterhub:1.3.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tpython\n\t\tscientific" as jupyterhub_1_3_0 #DarkGoldenRod
artifact "common:1.14.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_0 #DarkSeaGreen
artifact "postgresql:11.2.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_2_1 #LightSteelBlue

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/configurable-http-proxy:4.5.1-debian-10-r81\n====\n4.5.1-debian-10-r81" as docker_io_bitnami_configurable_http_proxy_4_5_1_debian_10_r81 #LightSteelBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/jupyterhub:1.5.0-debian-10-r169\n====\n1.5.0-debian-10-r169" as docker_io_bitnami_jupyterhub_1_5_0_debian_10_r169 #DarkSalmon
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.3.0-debian-10-r1\n====\n14.3.0-debian-10-r1" as docker_io_bitnami_postgresql_14_3_0_debian_10_r1 #DarkSalmon

'Chart Dependencies
jupyterhub_1_3_0--[#green]-|>postgresql_11_2_1
postgresql_11_2_1--[#green]-|>common_1_14_0
jupyterhub_1_3_0--[#green]-|>common_1_14_0
jupyterhub_1_3_0--[#orange]-|>docker_io_bitnami_configurable_http_proxy_4_5_1_debian_10_r81
jupyterhub_1_3_0--[#orange]-|>docker_io_bitnami_jupyterhub_1_5_0_debian_10_r169
postgresql_11_2_1--[#orange]-|>docker_io_bitnami_postgresql_14_3_0_debian_10_r1

center footer Generated on 2022/05/30 22:11:46 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
