@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kube-prometheus:6.13.2

'There are 5 referenced Helm Charts
artifact "kube-prometheus:6.13.2\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tprometheus\n\t\talertmanager\n\t\toperator\n\t\tmonitoring" as kube_prometheus_6_13_2 #LightSalmon
artifact "common:1.14.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_0 #DarkSeaGreen
artifact "kube-state-metrics:2.2.22\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tprometheus\n\t\tkube-state-metrics\n\t\tmonitoring" as kube_state_metrics_2_2_22 #Gainsboro
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen
artifact "node-exporter:2.4.15\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tprometheus\n\t\tnode-exporter\n\t\tmonitoring" as node_exporter_2_4_15 #Aqua

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/prometheus-operator:0.56.2-debian-10-r10\n====\n0.56.2-debian-10-r10" as docker_io_bitnami_prometheus_operator_0_56_2_debian_10_r10 #IndianRed
usecase "Image\n====\ndocker.io\n====\nbitnami/kube-state-metrics:2.4.2-debian-10-r70\n====\n2.4.2-debian-10-r70" as docker_io_bitnami_kube_state_metrics_2_4_2_debian_10_r70 #CornflowerBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/blackbox-exporter:0.20.0-debian-10-r63\n====\n0.20.0-debian-10-r63" as docker_io_bitnami_blackbox_exporter_0_20_0_debian_10_r63 #DarkSeaGreen

'Chart Dependencies
kube_prometheus_6_13_2--[#green]-|>node_exporter_2_4_15
node_exporter_2_4_15--[#green]-|>common_1_14_0
kube_prometheus_6_13_2--[#green]-|>kube_state_metrics_2_2_22
kube_state_metrics_2_2_22--[#green]-|>common_1_14_0
kube_prometheus_6_13_2--[#green]-|>common_1_14_1
kube_prometheus_6_13_2--[#orange]-|>docker_io_bitnami_blackbox_exporter_0_20_0_debian_10_r63
kube_prometheus_6_13_2--[#orange]-|>docker_io_bitnami_prometheus_operator_0_56_2_debian_10_r10
kube_state_metrics_2_2_22--[#orange]-|>docker_io_bitnami_kube_state_metrics_2_4_2_debian_10_r70

center footer Generated on 2022/05/22 15:34:39 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
