@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kubernetes-event-exporter:1.4.18

'There are 2 referenced Helm Charts
artifact "kubernetes-event-exporter:1.4.18\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\talerting\n\t\tevent exporting\n\t\tevents\n\t\tkubernetes events\n\t\tmonitoring\n\t\tobservability" as kubernetes_event_exporter_1_4_18 #BlanchedAlmond
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/kubernetes-event-exporter:0.11.0-debian-11-r21\n====\n0.11.0-debian-11-r21" as docker_io_bitnami_kubernetes_event_exporter_0_11_0_debian_11_r21 #CornflowerBlue

'Chart Dependencies
kubernetes_event_exporter_1_4_18--[#green]-|>common_1_16_1
kubernetes_event_exporter_1_4_18--[#orange]-|>docker_io_bitnami_kubernetes_event_exporter_0_11_0_debian_11_r21

center footer Generated on 2022/08/12 01:50:21 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
