@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kubeapps:10.0.6

'There are 4 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "kubeapps:10.0.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\thelm\n\t\tdashboard\n\t\tservice catalog\n\t\tdeployment" as kubeapps_10_0_6 #FloralWhite
artifact "postgresql:11.6.25\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_6_25 #LightSteelBlue
artifact "redis:17.0.8\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_17_0_8 #LightSeaGreen

'There are 7 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.4.0-debian-11-r21\n====\n14.4.0-debian-11-r21" as docker_io_bitnami_postgresql_14_4_0_debian_11_r21 #DarkSalmon
usecase "Image\n====\ndocker.io\n====\nbitnami/kubeapps-kubeops:2.4.6-scratch-r4\n====\n2.4.6-scratch-r4" as docker_io_bitnami_kubeapps_kubeops_2_4_6_scratch_r4 #LightSeaGreen
usecase "Image\n====\ndocker.io\n====\nbitnami/kubeapps-apprepository-controller:2.4.6-scratch-r4\n====\n2.4.6-scratch-r4" as docker_io_bitnami_kubeapps_apprepository_controller_2_4_6_scratch_r4 #Fuchsia
usecase "Image\n====\ndocker.io\n====\nbitnami/kubeapps-dashboard:2.4.6-debian-11-r16\n====\n2.4.6-debian-11-r16" as docker_io_bitnami_kubeapps_dashboard_2_4_6_debian_11_r16 #CadetBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/kubeapps-apis:2.4.6-debian-11-r18\n====\n2.4.6-debian-11-r18" as docker_io_bitnami_kubeapps_apis_2_4_6_debian_11_r18 #LightGrey
usecase "Image\n====\ndocker.io\n====\nbitnami/redis:7.0.4-debian-11-r9\n====\n7.0.4-debian-11-r9" as docker_io_bitnami_redis_7_0_4_debian_11_r9 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/nginx:1.23.1-debian-11-r7\n====\n1.23.1-debian-11-r7" as docker_io_bitnami_nginx_1_23_1_debian_11_r7 #LightPink

'Chart Dependencies
kubeapps_10_0_6--[#green]-|>postgresql_11_6_25
postgresql_11_6_25--[#green]-|>common_1_16_1
kubeapps_10_0_6--[#green]-|>common_1_16_1
kubeapps_10_0_6--[#green]-|>redis_17_0_8
redis_17_0_8--[#green]-|>common_1_16_1
kubeapps_10_0_6--[#orange]-|>docker_io_bitnami_kubeapps_apprepository_controller_2_4_6_scratch_r4
kubeapps_10_0_6--[#orange]-|>docker_io_bitnami_nginx_1_23_1_debian_11_r7
kubeapps_10_0_6--[#orange]-|>docker_io_bitnami_kubeapps_apis_2_4_6_debian_11_r18
kubeapps_10_0_6--[#orange]-|>docker_io_bitnami_kubeapps_dashboard_2_4_6_debian_11_r16
kubeapps_10_0_6--[#orange]-|>docker_io_bitnami_kubeapps_kubeops_2_4_6_scratch_r4
postgresql_11_6_25--[#orange]-|>docker_io_bitnami_postgresql_14_4_0_debian_11_r21
redis_17_0_8--[#orange]-|>docker_io_bitnami_redis_7_0_4_debian_11_r9

center footer Generated on 2022/08/12 01:50:02 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
