@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for logstash:5.0.16

'There are 2 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "logstash:5.0.16\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tlogstash\n\t\tlogging\n\t\telk" as logstash_5_0_16 #Aqua

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/logstash:8.3.3-debian-11-r2\n====\n8.3.3-debian-11-r2" as docker_io_bitnami_logstash_8_3_3_debian_11_r2 #Beige

'Chart Dependencies
logstash_5_0_16--[#green]-|>common_1_16_1
logstash_5_0_16--[#orange]-|>docker_io_bitnami_logstash_8_3_3_debian_11_r2

center footer Generated on 2022/08/12 01:50:46 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
