@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for magento:20.1.4

'There are 6 referenced Helm Charts
artifact "magento:20.1.4\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmagento\n\t\te-commerce\n\t\thttp\n\t\tweb\n\t\tphp" as magento_20_1_4 #HotPink
artifact "mariadb:11.0.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_0_7 #DarkTurquoise
artifact "elasticsearch:18.1.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: elasticsearch" as elasticsearch_18_1_6 #Aquamarine
artifact "common:1.14.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_0 #DarkSeaGreen
artifact "kibana:10.1.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tkibana\n\t\tanalytics\n\t\tmonitoring\n\t\tmetrics\n\t\tlogs" as kibana_10_1_3 #GhostWhite
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/elasticsearch:7.17.3-debian-10-r27\n====\n7.17.3-debian-10-r27" as docker_io_bitnami_elasticsearch_7_17_3_debian_10_r27 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.4.25-debian-10-r0\n====\n10.4.25-debian-10-r0" as docker_io_bitnami_mariadb_10_4_25_debian_10_r0 #DarkGoldenRod

'Chart Dependencies
magento_20_1_4--[#green]-|>elasticsearch_18_1_6
elasticsearch_18_1_6--[#green]-|>common_1_14_1
elasticsearch_18_1_6--[#green]-|>kibana_10_1_3
kibana_10_1_3--[#green]-|>common_1_14_0
magento_20_1_4--[#green]-|>common_1_14_1
magento_20_1_4--[#green]-|>mariadb_11_0_7
mariadb_11_0_7--[#green]-|>common_1_14_1
mariadb_11_0_7--[#orange]-|>docker_io_bitnami_mariadb_10_4_25_debian_10_r0
elasticsearch_18_1_6--[#orange]-|>docker_io_bitnami_elasticsearch_7_17_3_debian_10_r27

center footer Generated on 2022/06/02 03:20:53 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
