@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for metallb:3.0.4

'There are 2 referenced Helm Charts
artifact "metallb:3.0.4\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tcellebyte\n\t\tBitnami\n====\n\tKeywords: \n\t\tload-balancer\n\t\tbalancer\n\t\tlb\n\t\tbgp\n\t\tarp\n\t\tvrrp\n\t\tvip" as metallb_3_0_4 #GoldenRod
artifact "common:1.14.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_0 #DarkSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/metallb-controller:0.12.1-debian-10-r87\n====\n0.12.1-debian-10-r87" as docker_io_bitnami_metallb_controller_0_12_1_debian_10_r87 #Khaki

'Chart Dependencies
metallb_3_0_4--[#green]-|>common_1_14_0
metallb_3_0_4--[#orange]-|>docker_io_bitnami_metallb_controller_0_12_1_debian_10_r87

center footer Generated on 2022/05/30 22:17:11 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
