@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for mongodb:12.1.18

'There are 2 referenced Helm Charts
artifact "mongodb:12.1.18\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmongodb\n\t\tdatabase\n\t\tnosql\n\t\tcluster\n\t\treplicaset\n\t\treplication" as mongodb_12_1_18 #GreenYellow
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/mongodb:5.0.9-debian-10-r0\n====\n5.0.9-debian-10-r0" as docker_io_bitnami_mongodb_5_0_9_debian_10_r0 #Bisque

'Chart Dependencies
mongodb_12_1_18--[#green]-|>common_1_14_1
mongodb_12_1_18--[#orange]-|>docker_io_bitnami_mongodb_5_0_9_debian_10_r0

center footer Generated on 2022/06/15 22:31:14 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
