@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for mongodb-sharded:4.0.21

'There are 2 referenced Helm Charts
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "mongodb-sharded:4.0.21\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmongodb\n\t\tdatabase\n\t\tnosql\n\t\tcluster\n\t\treplicaset\n\t\treplication" as mongodb_sharded_4_0_21 #GhostWhite

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/mongodb-sharded:4.4.13-debian-10-r50\n====\n4.4.13-debian-10-r50" as docker_io_bitnami_mongodb_sharded_4_4_13_debian_10_r50 #Beige

'Chart Dependencies
mongodb_sharded_4_0_21--[#green]-|>common_1_13_0
mongodb_sharded_4_0_21--[#orange]-|>docker_io_bitnami_mongodb_sharded_4_4_13_debian_10_r50

center footer Generated on 2022/05/13 06:35:21 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
