@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for nats:7.3.4

'There are 2 referenced Helm Charts
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen
artifact "nats:7.3.4\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tnats\n\t\tmessaging\n\t\taddressing\n\t\tdiscovery" as nats_7_3_4 #AliceBlue

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/nats:2.8.4-debian-11-r0\n====\n2.8.4-debian-11-r0" as docker_io_bitnami_nats_2_8_4_debian_11_r0 #Cornsilk

'Chart Dependencies
nats_7_3_4--[#green]-|>common_1_16_0
nats_7_3_4--[#orange]-|>docker_io_bitnami_nats_2_8_4_debian_11_r0

center footer Generated on 2022/06/15 22:32:11 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
