@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for nginx-ingress-controller:9.2.8

'There are 2 referenced Helm Charts
artifact "nginx-ingress-controller:9.2.8\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tingress\n\t\tnginx\n\t\thttp\n\t\tweb\n\t\twww\n\t\treverse proxy" as nginx_ingress_controller_9_2_8 #Azure
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/nginx-ingress-controller:1.2.1-debian-11-r0\n====\n1.2.1-debian-11-r0" as docker_io_bitnami_nginx_ingress_controller_1_2_1_debian_11_r0 #Coral
usecase "Image\n====\ndocker.io\n====\nbitnami/nginx:1.21.6-debian-11-r0\n====\n1.21.6-debian-11-r0" as docker_io_bitnami_nginx_1_21_6_debian_11_r0 #LightPink

'Chart Dependencies
nginx_ingress_controller_9_2_8--[#green]-|>common_1_16_0
nginx_ingress_controller_9_2_8--[#orange]-|>docker_io_bitnami_nginx_1_21_6_debian_11_r0
nginx_ingress_controller_9_2_8--[#orange]-|>docker_io_bitnami_nginx_ingress_controller_1_2_1_debian_11_r0

center footer Generated on 2022/06/15 22:32:38 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
