@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for odoo:21.2.9

'There are 3 referenced Helm Charts
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "odoo:21.2.9\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\todoo\n\t\tcrm\n\t\twww\n\t\thttp\n\t\tweb" as odoo_21_2_9 #LightSteelBlue
artifact "postgresql:11.1.22\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_1_22 #LightSteelBlue

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/odoo:15.0.20220410-debian-10-r11\n====\n15.0.20220410-debian-10-r11" as docker_io_bitnami_odoo_15_0_20220410_debian_10_r11 #LavenderBlush
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.2.0-debian-10-r70\n====\n14.2.0-debian-10-r70" as docker_io_bitnami_postgresql_14_2_0_debian_10_r70 #DarkSalmon

'Chart Dependencies
odoo_21_2_9--[#green]-|>postgresql_11_1_22
postgresql_11_1_22--[#green]-|>common_1_13_0
odoo_21_2_9--[#green]-|>common_1_13_0
odoo_21_2_9--[#orange]-|>docker_io_bitnami_odoo_15_0_20220410_debian_10_r11
postgresql_11_1_22--[#orange]-|>docker_io_bitnami_postgresql_14_2_0_debian_10_r70

center footer Generated on 2022/05/14 14:15:19 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
