@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for parse:18.1.4

'There are 4 referenced Helm Charts
artifact "common:1.14.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_0 #DarkSeaGreen
artifact "parse:18.1.4\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tparse\n\t\tbackend\n\t\tserverless\n\t\tplatform\n\t\tmbaas\n\t\tmobile" as parse_18_1_4 #LightSeaGreen
artifact "mongodb:12.1.9\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmongodb\n\t\tdatabase\n\t\tnosql\n\t\tcluster\n\t\treplicaset\n\t\treplication" as mongodb_12_1_9 #GreenYellow
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mongodb:5.0.8-debian-10-r23\n====\n5.0.8-debian-10-r23" as docker_io_bitnami_mongodb_5_0_8_debian_10_r23 #Bisque
usecase "Image\n====\ndocker.io\n====\nbitnami/parse:5.2.1-debian-10-r19\n====\n5.2.1-debian-10-r19" as docker_io_bitnami_parse_5_2_1_debian_10_r19 #Azure

'Chart Dependencies
parse_18_1_4--[#green]-|>mongodb_12_1_9
mongodb_12_1_9--[#green]-|>common_1_14_0
parse_18_1_4--[#green]-|>common_1_14_1
parse_18_1_4--[#orange]-|>docker_io_bitnami_parse_5_2_1_debian_10_r19
mongodb_12_1_9--[#orange]-|>docker_io_bitnami_mongodb_5_0_8_debian_10_r23

center footer Generated on 2022/05/30 22:22:22 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
