@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for parse:18.1.10

'There are 4 referenced Helm Charts
artifact "mongodb:12.1.16\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmongodb\n\t\tdatabase\n\t\tnosql\n\t\tcluster\n\t\treplicaset\n\t\treplication" as mongodb_12_1_16 #GreenYellow
artifact "parse:18.1.10\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tparse\n\t\tbackend\n\t\tserverless\n\t\tplatform\n\t\tmbaas\n\t\tmobile" as parse_18_1_10 #LightSeaGreen
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mongodb:5.0.9-debian-10-r0\n====\n5.0.9-debian-10-r0" as docker_io_bitnami_mongodb_5_0_9_debian_10_r0 #Bisque
usecase "Image\n====\ndocker.io\n====\nbitnami/parse:5.2.1-debian-11-r0\n====\n5.2.1-debian-11-r0" as docker_io_bitnami_parse_5_2_1_debian_11_r0 #Azure

'Chart Dependencies
parse_18_1_10--[#green]-|>common_1_16_0
parse_18_1_10--[#green]-|>mongodb_12_1_16
mongodb_12_1_16--[#green]-|>common_1_14_1
mongodb_12_1_16--[#orange]-|>docker_io_bitnami_mongodb_5_0_9_debian_10_r0
parse_18_1_10--[#orange]-|>docker_io_bitnami_parse_5_2_1_debian_11_r0

center footer Generated on 2022/06/15 22:34:55 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
