@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for phpbb:11.0.23

'There are 3 referenced Helm Charts
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "mariadb:10.5.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_10_5_1 #DarkTurquoise
artifact "phpbb:11.0.23\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tphpbb\n\t\tforum\n\t\thttp\n\t\tphp" as phpbb_11_0_23 #Aqua

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/phpbb:3.3.7-debian-10-r33\n====\n3.3.7-debian-10-r33" as docker_io_bitnami_phpbb_3_3_7_debian_10_r33 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.5.15-debian-10-r62\n====\n10.5.15-debian-10-r62" as docker_io_bitnami_mariadb_10_5_15_debian_10_r62 #DarkGoldenRod

'Chart Dependencies
phpbb_11_0_23--[#green]-|>common_1_13_0
phpbb_11_0_23--[#green]-|>mariadb_10_5_1
mariadb_10_5_1--[#green]-|>common_1_13_0
mariadb_10_5_1--[#orange]-|>docker_io_bitnami_mariadb_10_5_15_debian_10_r62
phpbb_11_0_23--[#orange]-|>docker_io_bitnami_phpbb_3_3_7_debian_10_r33

center footer Generated on 2022/05/07 15:42:06 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
