@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for phpbb:12.2.15

'There are 3 referenced Helm Charts
artifact "mariadb:11.1.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_1_6 #DarkTurquoise
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "phpbb:12.2.15\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tphpbb\n\t\tforum\n\t\thttp\n\t\tphp" as phpbb_12_2_15 #Aqua

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.8-debian-11-r23\n====\n10.6.8-debian-11-r23" as docker_io_bitnami_mariadb_10_6_8_debian_11_r23 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/phpbb:3.3.8-debian-11-r13\n====\n3.3.8-debian-11-r13" as docker_io_bitnami_phpbb_3_3_8_debian_11_r13 #LightPink

'Chart Dependencies
phpbb_12_2_15--[#green]-|>mariadb_11_1_6
mariadb_11_1_6--[#green]-|>common_1_16_1
phpbb_12_2_15--[#green]-|>common_1_16_1
mariadb_11_1_6--[#orange]-|>docker_io_bitnami_mariadb_10_6_8_debian_11_r23
phpbb_12_2_15--[#orange]-|>docker_io_bitnami_phpbb_3_3_8_debian_11_r13

center footer Generated on 2022/08/12 01:57:08 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
