@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for postgresql:11.1.27

'There are 2 referenced Helm Charts
artifact "common:1.13.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_1 #DarkSeaGreen
artifact "postgresql:11.1.27\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_1_27 #LightSteelBlue

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.2.0-debian-10-r87\n====\n14.2.0-debian-10-r87" as docker_io_bitnami_postgresql_14_2_0_debian_10_r87 #DarkSalmon

'Chart Dependencies
postgresql_11_1_27--[#green]-|>common_1_13_1
postgresql_11_1_27--[#orange]-|>docker_io_bitnami_postgresql_14_2_0_debian_10_r87

center footer Generated on 2022/05/13 06:40:17 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
