@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for pytorch:2.4.4

'There are 2 referenced Helm Charts
artifact "common:1.14.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_0 #DarkSeaGreen
artifact "pytorch:2.4.4\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tpytorch\n\t\tpython\n\t\tmachine\n\t\tlearning" as pytorch_2_4_4 #LightSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/pytorch:1.11.0-debian-10-r54\n====\n1.11.0-debian-10-r54" as docker_io_bitnami_pytorch_1_11_0_debian_10_r54 #Coral

'Chart Dependencies
pytorch_2_4_4--[#green]-|>common_1_14_0
pytorch_2_4_4--[#orange]-|>docker_io_bitnami_pytorch_1_11_0_debian_10_r54

center footer Generated on 2022/05/22 15:44:50 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
