@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for redis-cluster:7.5.2

'There are 2 referenced Helm Charts
artifact "common:1.13.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_1 #DarkSeaGreen
artifact "redis-cluster:7.5.2\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_cluster_7_5_2 #Ivory

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/redis-cluster:6.2.7-debian-10-r0\n====\n6.2.7-debian-10-r0" as docker_io_bitnami_redis_cluster_6_2_7_debian_10_r0 #LightCyan

'Chart Dependencies
redis_cluster_7_5_2--[#green]-|>common_1_13_1
redis_cluster_7_5_2--[#orange]-|>docker_io_bitnami_redis_cluster_6_2_7_debian_10_r0

center footer Generated on 2022/05/07 15:44:33 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
