@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for redis:16.9.8

'There are 2 referenced Helm Charts
artifact "redis:16.9.8\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_16_9_8 #LightSeaGreen
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/redis:6.2.7-debian-10-r21\n====\n6.2.7-debian-10-r21" as docker_io_bitnami_redis_6_2_7_debian_10_r21 #Azure

'Chart Dependencies
redis_16_9_8--[#green]-|>common_1_14_1
redis_16_9_8--[#orange]-|>docker_io_bitnami_redis_6_2_7_debian_10_r21

center footer Generated on 2022/05/22 15:45:35 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
