@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for redmine:20.0.1

'There are 4 referenced Helm Charts
artifact "mariadb:11.0.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_0_0 #DarkTurquoise
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "postgresql:11.1.22\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_1_22 #LightSteelBlue
artifact "redmine:20.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tredmine\n\t\tproject management\n\t\twww\n\t\thttp\n\t\tweb\n\t\tapplication\n\t\truby\n\t\trails" as redmine_20_0_1 #Gainsboro

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.7-debian-10-r62\n====\n10.6.7-debian-10-r62" as docker_io_bitnami_mariadb_10_6_7_debian_10_r62 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.2.0-debian-10-r70\n====\n14.2.0-debian-10-r70" as docker_io_bitnami_postgresql_14_2_0_debian_10_r70 #DarkSalmon
usecase "Image\n====\ndocker.io\n====\nbitnami/redmine:5.0.0-debian-10-r4\n====\n5.0.0-debian-10-r4" as docker_io_bitnami_redmine_5_0_0_debian_10_r4 #Chartreuse

'Chart Dependencies
redmine_20_0_1--[#green]-|>common_1_13_0
redmine_20_0_1--[#green]-|>mariadb_11_0_0
mariadb_11_0_0--[#green]-|>common_1_13_0
redmine_20_0_1--[#green]-|>postgresql_11_1_22
postgresql_11_1_22--[#green]-|>common_1_13_0
mariadb_11_0_0--[#orange]-|>docker_io_bitnami_mariadb_10_6_7_debian_10_r62
postgresql_11_1_22--[#orange]-|>docker_io_bitnami_postgresql_14_2_0_debian_10_r70
redmine_20_0_1--[#orange]-|>docker_io_bitnami_redmine_5_0_0_debian_10_r4

center footer Generated on 2022/05/15 12:45:32 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
