@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for redmine:20.2.19

'There are 4 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "postgresql:11.6.26\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_6_26 #LightSteelBlue
artifact "mariadb:11.1.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_1_7 #DarkTurquoise
artifact "redmine:20.2.19\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tredmine\n\t\tproject management\n\t\twww\n\t\thttp\n\t\tweb\n\t\tapplication\n\t\truby\n\t\trails" as redmine_20_2_19 #Gainsboro

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.4.0-debian-11-r23\n====\n14.4.0-debian-11-r23" as docker_io_bitnami_postgresql_14_4_0_debian_11_r23 #DarkSalmon
usecase "Image\n====\ndocker.io\n====\nbitnami/redmine:5.0.2-debian-11-r17\n====\n5.0.2-debian-11-r17" as docker_io_bitnami_redmine_5_0_2_debian_11_r17 #Chartreuse
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.8-debian-11-r25\n====\n10.6.8-debian-11-r25" as docker_io_bitnami_mariadb_10_6_8_debian_11_r25 #DarkGoldenRod

'Chart Dependencies
redmine_20_2_19--[#green]-|>common_1_16_1
redmine_20_2_19--[#green]-|>postgresql_11_6_26
postgresql_11_6_26--[#green]-|>common_1_16_1
redmine_20_2_19--[#green]-|>mariadb_11_1_7
mariadb_11_1_7--[#green]-|>common_1_16_1
postgresql_11_6_26--[#orange]-|>docker_io_bitnami_postgresql_14_4_0_debian_11_r23
mariadb_11_1_7--[#orange]-|>docker_io_bitnami_mariadb_10_6_8_debian_11_r25
redmine_20_2_19--[#orange]-|>docker_io_bitnami_redmine_5_0_2_debian_11_r17

center footer Generated on 2022/08/12 01:59:27 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
