@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for schema-registry:4.0.4

'There are 4 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "kafka:18.0.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tkafka\n\t\tzookeeper\n\t\tstreaming\n\t\tproducer\n\t\tconsumer" as kafka_18_0_7 #Aqua
artifact "schema-registry:4.0.4\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tschema-registry\n\t\tconfluent\n\t\tkafka\n\t\tzookeeper\n\t\tstreaming" as schema_registry_4_0_4 #AliceBlue
artifact "zookeeper:10.0.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: zookeeper" as zookeeper_10_0_6 #LemonChiffon

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/zookeeper:3.8.0-debian-11-r24\n====\n3.8.0-debian-11-r24" as docker_io_bitnami_zookeeper_3_8_0_debian_11_r24 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/kafka:3.2.1-debian-11-r2\n====\n3.2.1-debian-11-r2" as docker_io_bitnami_kafka_3_2_1_debian_11_r2 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/schema-registry:7.1.3-debian-11-r11\n====\n7.1.3-debian-11-r11" as docker_io_bitnami_schema_registry_7_1_3_debian_11_r11 #HotPink

'Chart Dependencies
schema_registry_4_0_4--[#green]-|>common_1_16_1
schema_registry_4_0_4--[#green]-|>kafka_18_0_7
kafka_18_0_7--[#green]-|>common_1_16_1
kafka_18_0_7--[#green]-|>zookeeper_10_0_6
zookeeper_10_0_6--[#green]-|>common_1_16_1
kafka_18_0_7--[#orange]-|>docker_io_bitnami_kafka_3_2_1_debian_11_r2
schema_registry_4_0_4--[#orange]-|>docker_io_bitnami_schema_registry_7_1_3_debian_11_r11
zookeeper_10_0_6--[#orange]-|>docker_io_bitnami_zookeeper_3_8_0_debian_11_r24

center footer Generated on 2022/08/12 01:59:46 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
