@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for sealed-secrets:1.0.7

'There are 2 referenced Helm Charts
artifact "sealed-secrets:1.0.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tsecrets\n\t\tsealed-secrets" as sealed_secrets_1_0_7 #HotPink
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/sealed-secrets:0.18.0-scratch-r1\n====\n0.18.0-scratch-r1" as docker_io_bitnami_sealed_secrets_0_18_0_scratch_r1 #CadetBlue

'Chart Dependencies
sealed_secrets_1_0_7--[#green]-|>common_1_16_0
sealed_secrets_1_0_7--[#orange]-|>docker_io_bitnami_sealed_secrets_0_18_0_scratch_r1

center footer Generated on 2022/06/15 22:37:40 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
