@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for solr:5.1.7

'There are 3 referenced Helm Charts
artifact "zookeeper:9.2.5\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: zookeeper" as zookeeper_9_2_5 #LemonChiffon
artifact "solr:5.1.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tsolr\n\t\tzookeeper\n\t\tapache" as solr_5_1_7 #AliceBlue
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/zookeeper:3.8.0-debian-11-r3\n====\n3.8.0-debian-11-r3" as docker_io_bitnami_zookeeper_3_8_0_debian_11_r3 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/solr:9.0.0-debian-11-r4\n====\n9.0.0-debian-11-r4" as docker_io_bitnami_solr_9_0_0_debian_11_r4 #Cornsilk

'Chart Dependencies
solr_5_1_7--[#green]-|>common_1_16_0
solr_5_1_7--[#green]-|>zookeeper_9_2_5
zookeeper_9_2_5--[#green]-|>common_1_16_0
zookeeper_9_2_5--[#orange]-|>docker_io_bitnami_zookeeper_3_8_0_debian_11_r3
solr_5_1_7--[#orange]-|>docker_io_bitnami_solr_9_0_0_debian_11_r4

center footer Generated on 2022/06/15 22:37:49 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
