@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for sonarqube:1.0.14

'There are 4 referenced Helm Charts
artifact "common:1.13.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_1 #DarkSeaGreen
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "postgresql:11.1.25\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_1_25 #LightSteelBlue
artifact "sonarqube:1.0.14\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tsonarqube\n\t\tcode-quality\n\t\tcode-review\n\t\tstatic-analysis" as sonarqube_1_0_14 #Azure

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.2.0-debian-10-r77\n====\n14.2.0-debian-10-r77" as docker_io_bitnami_postgresql_14_2_0_debian_10_r77 #DarkSalmon
usecase "Image\n====\ndocker.io\n====\nbitnami/sonarqube:9.4.0-debian-10-r0\n====\n9.4.0-debian-10-r0" as docker_io_bitnami_sonarqube_9_4_0_debian_10_r0 #CornflowerBlue

'Chart Dependencies
sonarqube_1_0_14--[#green]-|>postgresql_11_1_25
postgresql_11_1_25--[#green]-|>common_1_13_0
sonarqube_1_0_14--[#green]-|>common_1_13_1
postgresql_11_1_25--[#orange]-|>docker_io_bitnami_postgresql_14_2_0_debian_10_r77
sonarqube_1_0_14--[#orange]-|>docker_io_bitnami_sonarqube_9_4_0_debian_10_r0

center footer Generated on 2022/05/13 06:43:10 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
