@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for sonarqube:1.4.6

'There are 3 referenced Helm Charts
artifact "postgresql:11.6.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_6_6 #LightSteelBlue
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen
artifact "sonarqube:1.4.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tsonarqube\n\t\tcode-quality\n\t\tcode-review\n\t\tstatic-analysis" as sonarqube_1_4_6 #Azure

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/sonarqube:9.5.0-debian-11-r0\n====\n9.5.0-debian-11-r0" as docker_io_bitnami_sonarqube_9_5_0_debian_11_r0 #CornflowerBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.3.0-debian-11-r3\n====\n14.3.0-debian-11-r3" as docker_io_bitnami_postgresql_14_3_0_debian_11_r3 #DarkSalmon

'Chart Dependencies
sonarqube_1_4_6--[#green]-|>common_1_16_0
sonarqube_1_4_6--[#green]-|>postgresql_11_6_6
postgresql_11_6_6--[#green]-|>common_1_16_0
postgresql_11_6_6--[#orange]-|>docker_io_bitnami_postgresql_14_3_0_debian_11_r3
sonarqube_1_4_6--[#orange]-|>docker_io_bitnami_sonarqube_9_5_0_debian_11_r0

center footer Generated on 2022/08/12 02:00:41 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
