@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for sonarqube:1.2.3

'There are 4 referenced Helm Charts
artifact "sonarqube:1.2.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tsonarqube\n\t\tcode-quality\n\t\tcode-review\n\t\tstatic-analysis" as sonarqube_1_2_3 #Azure
artifact "common:1.14.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_0 #DarkSeaGreen
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen
artifact "postgresql:11.2.5\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_2_5 #LightSteelBlue

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.3.0-debian-10-r7\n====\n14.3.0-debian-10-r7" as docker_io_bitnami_postgresql_14_3_0_debian_10_r7 #DarkSalmon
usecase "Image\n====\ndocker.io\n====\nbitnami/sonarqube:9.4.0-debian-10-r19\n====\n9.4.0-debian-10-r19" as docker_io_bitnami_sonarqube_9_4_0_debian_10_r19 #CornflowerBlue

'Chart Dependencies
sonarqube_1_2_3--[#green]-|>postgresql_11_2_5
postgresql_11_2_5--[#green]-|>common_1_14_0
sonarqube_1_2_3--[#green]-|>common_1_14_1
sonarqube_1_2_3--[#orange]-|>docker_io_bitnami_sonarqube_9_4_0_debian_10_r19
postgresql_11_2_5--[#orange]-|>docker_io_bitnami_postgresql_14_3_0_debian_10_r7

center footer Generated on 2022/05/22 15:46:35 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
