@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for sonarqube:1.0.12

'There are 3 referenced Helm Charts
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "postgresql:11.1.22\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_11_1_22 #LightSteelBlue
artifact "sonarqube:1.0.12\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tsonarqube\n\t\tcode-quality\n\t\tcode-review\n\t\tstatic-analysis" as sonarqube_1_0_12 #Azure

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/sonarqube:9.3.0-debian-10-r61\n====\n9.3.0-debian-10-r61" as docker_io_bitnami_sonarqube_9_3_0_debian_10_r61 #CornflowerBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:14.2.0-debian-10-r70\n====\n14.2.0-debian-10-r70" as docker_io_bitnami_postgresql_14_2_0_debian_10_r70 #DarkSalmon

'Chart Dependencies
sonarqube_1_0_12--[#green]-|>common_1_13_0
sonarqube_1_0_12--[#green]-|>postgresql_11_1_22
postgresql_11_1_22--[#green]-|>common_1_13_0
postgresql_11_1_22--[#orange]-|>docker_io_bitnami_postgresql_14_2_0_debian_10_r70
sonarqube_1_0_12--[#orange]-|>docker_io_bitnami_sonarqube_9_3_0_debian_10_r61

center footer Generated on 2022/05/15 12:46:07 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
