@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for spark:6.1.2

'There are 2 referenced Helm Charts
artifact "spark:6.1.2\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tapache\n\t\tspark" as spark_6_1_2 #LightSeaGreen
artifact "common:1.14.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_0 #DarkSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/spark:3.2.1-debian-10-r105\n====\n3.2.1-debian-10-r105" as docker_io_bitnami_spark_3_2_1_debian_10_r105 #Azure

'Chart Dependencies
spark_6_1_2--[#green]-|>common_1_14_0
spark_6_1_2--[#orange]-|>docker_io_bitnami_spark_3_2_1_debian_10_r105

center footer Generated on 2022/06/02 03:31:55 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
