@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for spring-cloud-dataflow:12.0.5

'There are 7 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "kafka:18.0.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tkafka\n\t\tzookeeper\n\t\tstreaming\n\t\tproducer\n\t\tconsumer" as kafka_18_0_3 #Aqua
artifact "spring-cloud-dataflow:12.0.5\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tspring-cloud\n\t\tdataflow\n\t\tskipper\n\t\tspring" as spring_cloud_dataflow_12_0_5 #IndianRed
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen
artifact "rabbitmq:10.1.16\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\trabbitmq\n\t\tmessage queue\n\t\tAMQP" as rabbitmq_10_1_16 #Aqua
artifact "mariadb:11.1.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_1_1 #DarkTurquoise
artifact "zookeeper:10.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: zookeeper" as zookeeper_10_0_1 #LemonChiffon

'There are 6 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/kafka:3.2.0-debian-11-r12\n====\n3.2.0-debian-11-r12" as docker_io_bitnami_kafka_3_2_0_debian_11_r12 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/zookeeper:3.8.0-debian-11-r11\n====\n3.8.0-debian-11-r11" as docker_io_bitnami_zookeeper_3_8_0_debian_11_r11 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/spring-cloud-skipper:2.8.4-debian-11-r23\n====\n2.8.4-debian-11-r23" as docker_io_bitnami_spring_cloud_skipper_2_8_4_debian_11_r23 #GhostWhite
usecase "Image\n====\ndocker.io\n====\nbitnami/spring-cloud-dataflow:2.9.4-debian-11-r22\n====\n2.9.4-debian-11-r22" as docker_io_bitnami_spring_cloud_dataflow_2_9_4_debian_11_r22 #CadetBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.8-debian-11-r9\n====\n10.6.8-debian-11-r9" as docker_io_bitnami_mariadb_10_6_8_debian_11_r9 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/rabbitmq:3.10.6-debian-11-r5\n====\n3.10.6-debian-11-r5" as docker_io_bitnami_rabbitmq_3_10_6_debian_11_r5 #Beige

'Chart Dependencies
spring_cloud_dataflow_12_0_5--[#green]-|>mariadb_11_1_1
mariadb_11_1_1--[#green]-|>common_1_16_0
spring_cloud_dataflow_12_0_5--[#green]-|>kafka_18_0_3
kafka_18_0_3--[#green]-|>zookeeper_10_0_1
zookeeper_10_0_1--[#green]-|>common_1_16_0
kafka_18_0_3--[#green]-|>common_1_16_0
spring_cloud_dataflow_12_0_5--[#green]-|>common_1_16_1
spring_cloud_dataflow_12_0_5--[#green]-|>rabbitmq_10_1_16
rabbitmq_10_1_16--[#green]-|>common_1_16_1
kafka_18_0_3--[#orange]-|>docker_io_bitnami_kafka_3_2_0_debian_11_r12
spring_cloud_dataflow_12_0_5--[#orange]-|>docker_io_bitnami_spring_cloud_dataflow_2_9_4_debian_11_r22
spring_cloud_dataflow_12_0_5--[#orange]-|>docker_io_bitnami_spring_cloud_skipper_2_8_4_debian_11_r23
rabbitmq_10_1_16--[#orange]-|>docker_io_bitnami_rabbitmq_3_10_6_debian_11_r5
mariadb_11_1_1--[#orange]-|>docker_io_bitnami_mariadb_10_6_8_debian_11_r9
zookeeper_10_0_1--[#orange]-|>docker_io_bitnami_zookeeper_3_8_0_debian_11_r11

center footer Generated on 2022/08/12 02:01:22 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
