@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for spring-cloud-dataflow:11.0.1

'There are 6 referenced Helm Charts
artifact "rabbitmq:10.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\trabbitmq\n\t\tmessage queue\n\t\tAMQP" as rabbitmq_10_0_1 #Aqua
artifact "kafka:17.1.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tkafka\n\t\tzookeeper\n\t\tstreaming\n\t\tproducer\n\t\tconsumer" as kafka_17_1_0 #Aqua
artifact "zookeeper:9.1.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: zookeeper" as zookeeper_9_1_6 #LemonChiffon
artifact "spring-cloud-dataflow:11.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tspring-cloud\n\t\tdataflow\n\t\tskipper\n\t\tspring" as spring_cloud_dataflow_11_0_1 #IndianRed
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen
artifact "mariadb:11.0.8\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_0_8 #DarkTurquoise

'There are 6 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/spring-cloud-skipper:2.8.4-debian-10-r48\n====\n2.8.4-debian-10-r48" as docker_io_bitnami_spring_cloud_skipper_2_8_4_debian_10_r48 #GhostWhite
usecase "Image\n====\ndocker.io\n====\nbitnami/zookeeper:3.8.0-debian-10-r64\n====\n3.8.0-debian-10-r64" as docker_io_bitnami_zookeeper_3_8_0_debian_10_r64 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/spring-cloud-dataflow:2.9.4-debian-10-r36\n====\n2.9.4-debian-10-r36" as docker_io_bitnami_spring_cloud_dataflow_2_9_4_debian_10_r36 #CadetBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.8-debian-10-r0\n====\n10.6.8-debian-10-r0" as docker_io_bitnami_mariadb_10_6_8_debian_10_r0 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/rabbitmq:3.10.2-debian-10-r7\n====\n3.10.2-debian-10-r7" as docker_io_bitnami_rabbitmq_3_10_2_debian_10_r7 #Beige
usecase "Image\n====\ndocker.io\n====\nbitnami/kafka:3.2.0-debian-10-r4\n====\n3.2.0-debian-10-r4" as docker_io_bitnami_kafka_3_2_0_debian_10_r4 #LightPink

'Chart Dependencies
spring_cloud_dataflow_11_0_1--[#green]-|>mariadb_11_0_8
mariadb_11_0_8--[#green]-|>common_1_14_1
spring_cloud_dataflow_11_0_1--[#green]-|>rabbitmq_10_0_1
rabbitmq_10_0_1--[#green]-|>common_1_14_1
spring_cloud_dataflow_11_0_1--[#green]-|>kafka_17_1_0
kafka_17_1_0--[#green]-|>common_1_14_1
kafka_17_1_0--[#green]-|>zookeeper_9_1_6
zookeeper_9_1_6--[#green]-|>common_1_14_1
spring_cloud_dataflow_11_0_1--[#green]-|>common_1_14_1
rabbitmq_10_0_1--[#orange]-|>docker_io_bitnami_rabbitmq_3_10_2_debian_10_r7
kafka_17_1_0--[#orange]-|>docker_io_bitnami_kafka_3_2_0_debian_10_r4
zookeeper_9_1_6--[#orange]-|>docker_io_bitnami_zookeeper_3_8_0_debian_10_r64
spring_cloud_dataflow_11_0_1--[#orange]-|>docker_io_bitnami_spring_cloud_skipper_2_8_4_debian_10_r48
spring_cloud_dataflow_11_0_1--[#orange]-|>docker_io_bitnami_spring_cloud_dataflow_2_9_4_debian_10_r36
mariadb_11_0_8--[#orange]-|>docker_io_bitnami_mariadb_10_6_8_debian_10_r0

center footer Generated on 2022/06/02 03:32:03 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
