@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for spring-cloud-dataflow:8.0.1

'There are 6 referenced Helm Charts
artifact "spring-cloud-dataflow:8.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tspring-cloud\n\t\tdataflow\n\t\tskipper\n\t\tspring" as spring_cloud_dataflow_8_0_1 #IndianRed
artifact "mariadb:11.0.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_0_0 #DarkTurquoise
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "rabbitmq:8.32.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\trabbitmq\n\t\tmessage queue\n\t\tAMQP" as rabbitmq_8_32_0 #Aqua
artifact "kafka:16.2.7\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tkafka\n\t\tzookeeper\n\t\tstreaming\n\t\tproducer\n\t\tconsumer" as kafka_16_2_7 #Aqua
artifact "zookeeper:9.0.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: zookeeper" as zookeeper_9_0_6 #LemonChiffon

'There are 6 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/zookeeper:3.8.0-debian-10-r34\n====\n3.8.0-debian-10-r34" as docker_io_bitnami_zookeeper_3_8_0_debian_10_r34 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/rabbitmq:3.9.15-debian-10-r6\n====\n3.9.15-debian-10-r6" as docker_io_bitnami_rabbitmq_3_9_15_debian_10_r6 #Beige
usecase "Image\n====\ndocker.io\n====\nbitnami/kafka:3.1.0-debian-10-r85\n====\n3.1.0-debian-10-r85" as docker_io_bitnami_kafka_3_1_0_debian_10_r85 #LightPink
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.7-debian-10-r62\n====\n10.6.7-debian-10-r62" as docker_io_bitnami_mariadb_10_6_7_debian_10_r62 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/spring-cloud-dataflow:2.9.4-debian-10-r14\n====\n2.9.4-debian-10-r14" as docker_io_bitnami_spring_cloud_dataflow_2_9_4_debian_10_r14 #CadetBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/spring-cloud-skipper:2.8.4-debian-10-r16\n====\n2.8.4-debian-10-r16" as docker_io_bitnami_spring_cloud_skipper_2_8_4_debian_10_r16 #GhostWhite

'Chart Dependencies
spring_cloud_dataflow_8_0_1--[#green]-|>common_1_13_0
spring_cloud_dataflow_8_0_1--[#green]-|>rabbitmq_8_32_0
rabbitmq_8_32_0--[#green]-|>common_1_13_0
spring_cloud_dataflow_8_0_1--[#green]-|>mariadb_11_0_0
mariadb_11_0_0--[#green]-|>common_1_13_0
spring_cloud_dataflow_8_0_1--[#green]-|>kafka_16_2_7
kafka_16_2_7--[#green]-|>common_1_13_0
kafka_16_2_7--[#green]-|>zookeeper_9_0_6
zookeeper_9_0_6--[#green]-|>common_1_13_0
spring_cloud_dataflow_8_0_1--[#orange]-|>docker_io_bitnami_spring_cloud_skipper_2_8_4_debian_10_r16
spring_cloud_dataflow_8_0_1--[#orange]-|>docker_io_bitnami_spring_cloud_dataflow_2_9_4_debian_10_r14
mariadb_11_0_0--[#orange]-|>docker_io_bitnami_mariadb_10_6_7_debian_10_r62
rabbitmq_8_32_0--[#orange]-|>docker_io_bitnami_rabbitmq_3_9_15_debian_10_r6
kafka_16_2_7--[#orange]-|>docker_io_bitnami_kafka_3_1_0_debian_10_r85
zookeeper_9_0_6--[#orange]-|>docker_io_bitnami_zookeeper_3_8_0_debian_10_r34

center footer Generated on 2022/05/13 06:43:52 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
