@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for sugarcrm:1.0.5

'There are 2 referenced Helm Charts
artifact "mariadb:0.7.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql" as mariadb_0_7_0 #DarkTurquoise
artifact "sugarcrm:1.0.5\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tsugarcrm\n\t\tCRM" as sugarcrm_1_0_5 #LightGrey

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nbitnami/mariadb\n====\n10.1.23-r2" as bitnami_mariadb_10_1_23_r2 #LightGray

'Chart Dependencies
sugarcrm_1_0_5--[#green]-|>mariadb_0_7_0
mariadb_0_7_0--[#orange]-|>bitnami_mariadb_10_1_23_r2

center footer Generated on 2022/05/15 12:46:58 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
