@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for suitecrm:11.1.13

'There are 3 referenced Helm Charts
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "mariadb:11.1.2\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_1_2 #DarkTurquoise
artifact "suitecrm:11.1.13\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tsuitecrm\n\t\tcrm\n\t\thttp\n\t\tweb\n\t\tphp" as suitecrm_11_1_13 #LightGreen

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.8-debian-11-r20\n====\n10.6.8-debian-11-r20" as docker_io_bitnami_mariadb_10_6_8_debian_11_r20 #DarkGoldenRod

'Chart Dependencies
suitecrm_11_1_13--[#green]-|>mariadb_11_1_2
mariadb_11_1_2--[#green]-|>common_1_16_1
suitecrm_11_1_13--[#green]-|>common_1_16_1
mariadb_11_1_2--[#orange]-|>docker_io_bitnami_mariadb_10_6_8_debian_11_r20

center footer Generated on 2022/08/12 02:01:35 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
