@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for thanos:10.3.5

'There are 3 referenced Helm Charts
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "minio:11.2.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tminio\n\t\tstorage\n\t\tobject-storage\n\t\ts3\n\t\tcluster" as minio_11_2_6 #Aqua
artifact "thanos:10.3.5\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tanalytics\n\t\tmonitoring\n\t\tprometheus\n\t\tthanos" as thanos_10_3_5 #HoneyDew

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/thanos:0.25.2-scratch-r2\n====\n0.25.2-scratch-r2" as docker_io_bitnami_thanos_0_25_2_scratch_r2 #LavenderBlush
usecase "Image\n====\ndocker.io\n====\nbitnami/minio:2022.4.1-debian-10-r5\n====\n2022.4.1-debian-10-r5" as docker_io_bitnami_minio_2022_4_1_debian_10_r5 #LightPink

'Chart Dependencies
thanos_10_3_5--[#green]-|>common_1_13_0
thanos_10_3_5--[#green]-|>minio_11_2_6
minio_11_2_6--[#green]-|>common_1_13_0
minio_11_2_6--[#orange]-|>docker_io_bitnami_minio_2022_4_1_debian_10_r5
thanos_10_3_5--[#orange]-|>docker_io_bitnami_thanos_0_25_2_scratch_r2

center footer Generated on 2022/05/07 15:47:47 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
