@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for wavefront-prometheus-storage-adapter:2.0.8

'There are 5 referenced Helm Charts
artifact "kube-state-metrics:3.1.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tprometheus\n\t\tkube-state-metrics\n\t\tmonitoring" as kube_state_metrics_3_1_1 #Gainsboro
artifact "wavefront-prometheus-storage-adapter:2.0.8\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\talerting\n\t\tadapter\n\t\tmetrics\n\t\tmonitoring\n\t\tobservability\n\t\twavefront" as wavefront_prometheus_storage_adapter_2_0_8 #DarkSalmon
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen
artifact "wavefront:4.0.5\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmetric\n\t\tmonitoring\n\t\tobservability\n\t\talerting" as wavefront_4_0_5 #LavenderBlush
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/kube-state-metrics:2.5.0-debian-11-r9\n====\n2.5.0-debian-11-r9" as docker_io_bitnami_kube_state_metrics_2_5_0_debian_11_r9 #CornflowerBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/wavefront-prometheus-storage-adapter:1.0.5-debian-11-r22\n====\n1.0.5-debian-11-r22" as docker_io_bitnami_wavefront_prometheus_storage_adapter_1_0_5_debian_11_r22 #LemonChiffon
usecase "Image\n====\ndocker.io\n====\nbitnami/wavefront-proxy:11.3.0-debian-11-r10\n====\n11.3.0-debian-11-r10" as docker_io_bitnami_wavefront_proxy_11_3_0_debian_11_r10 #Cyan

'Chart Dependencies
wavefront_prometheus_storage_adapter_2_0_8--[#green]-|>common_1_16_1
wavefront_prometheus_storage_adapter_2_0_8--[#green]-|>wavefront_4_0_5
wavefront_4_0_5--[#green]-|>common_1_16_1
wavefront_4_0_5--[#green]-|>kube_state_metrics_3_1_1
kube_state_metrics_3_1_1--[#green]-|>common_1_16_0
kube_state_metrics_3_1_1--[#orange]-|>docker_io_bitnami_kube_state_metrics_2_5_0_debian_11_r9
wavefront_prometheus_storage_adapter_2_0_8--[#orange]-|>docker_io_bitnami_wavefront_prometheus_storage_adapter_1_0_5_debian_11_r22
wavefront_4_0_5--[#orange]-|>docker_io_bitnami_wavefront_proxy_11_3_0_debian_11_r10

center footer Generated on 2022/08/12 02:03:22 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
