@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for wavefront-adapter-for-istio:1.1.1

'There are 4 referenced Helm Charts
artifact "kube-state-metrics:2.2.17\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tprometheus\n\t\tkube-state-metrics\n\t\tmonitoring" as kube_state_metrics_2_2_17 #Gainsboro
artifact "wavefront:3.4.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmetric\n\t\tmonitoring\n\t\tobservability\n\t\talerting" as wavefront_3_4_0 #LavenderBlush
artifact "common:1.13.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_13_0 #DarkSeaGreen
artifact "wavefront-adapter-for-istio:1.1.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\talerting\n\t\tadapter\n\t\tistio\n\t\tmetrics\n\t\tmonitoring\n\t\tobservability\n\t\twavefront" as wavefront_adapter_for_istio_1_1_1 #HoneyDew

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/kube-state-metrics:2.4.2-debian-10-r28\n====\n2.4.2-debian-10-r28" as docker_io_bitnami_kube_state_metrics_2_4_2_debian_10_r28 #CornflowerBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/wavefront-proxy:11.0.0-debian-10-r17\n====\n11.0.0-debian-10-r17" as docker_io_bitnami_wavefront_proxy_11_0_0_debian_10_r17 #Cyan
usecase "Image\n====\ndocker.io\n====\nbitnami/wavefront-adapter-for-istio:0.1.5-debian-10-r364\n====\n0.1.5-debian-10-r364" as docker_io_bitnami_wavefront_adapter_for_istio_0_1_5_debian_10_r364 #LightSkyBlue

'Chart Dependencies
wavefront_adapter_for_istio_1_1_1--[#green]-|>common_1_13_0
wavefront_adapter_for_istio_1_1_1--[#green]-|>wavefront_3_4_0
wavefront_3_4_0--[#green]-|>common_1_13_0
wavefront_3_4_0--[#green]-|>kube_state_metrics_2_2_17
kube_state_metrics_2_2_17--[#green]-|>common_1_13_0
kube_state_metrics_2_2_17--[#orange]-|>docker_io_bitnami_kube_state_metrics_2_4_2_debian_10_r28
wavefront_3_4_0--[#orange]-|>docker_io_bitnami_wavefront_proxy_11_0_0_debian_10_r17
wavefront_adapter_for_istio_1_1_1--[#orange]-|>docker_io_bitnami_wavefront_adapter_for_istio_0_1_5_debian_10_r364

center footer Generated on 2022/05/15 12:49:10 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
