@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for wavefront-prometheus-storage-adapter:2.0.3

'There are 5 referenced Helm Charts
artifact "wavefront-prometheus-storage-adapter:2.0.3\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\talerting\n\t\tadapter\n\t\tmetrics\n\t\tmonitoring\n\t\tobservability\n\t\twavefront" as wavefront_prometheus_storage_adapter_2_0_3 #DarkSalmon
artifact "kube-state-metrics:3.0.0\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tprometheus\n\t\tkube-state-metrics\n\t\tmonitoring" as kube_state_metrics_3_0_0 #Gainsboro
artifact "common:1.16.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_0 #DarkSeaGreen
artifact "common:1.14.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_14_1 #DarkSeaGreen
artifact "wavefront:4.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmetric\n\t\tmonitoring\n\t\tobservability\n\t\talerting" as wavefront_4_0_1 #LavenderBlush

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/wavefront-proxy:11.1.0-debian-10-r13\n====\n11.1.0-debian-10-r13" as docker_io_bitnami_wavefront_proxy_11_1_0_debian_10_r13 #Cyan
usecase "Image\n====\ndocker.io\n====\nbitnami/kube-state-metrics:2.4.2-debian-10-r72\n====\n2.4.2-debian-10-r72" as docker_io_bitnami_kube_state_metrics_2_4_2_debian_10_r72 #CornflowerBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/wavefront-prometheus-storage-adapter:1.0.5-debian-11-r0\n====\n1.0.5-debian-11-r0" as docker_io_bitnami_wavefront_prometheus_storage_adapter_1_0_5_debian_11_r0 #LemonChiffon

'Chart Dependencies
wavefront_prometheus_storage_adapter_2_0_3--[#green]-|>common_1_16_0
wavefront_prometheus_storage_adapter_2_0_3--[#green]-|>wavefront_4_0_1
wavefront_4_0_1--[#green]-|>kube_state_metrics_3_0_0
kube_state_metrics_3_0_0--[#green]-|>common_1_14_1
wavefront_4_0_1--[#green]-|>common_1_14_1
wavefront_prometheus_storage_adapter_2_0_3--[#orange]-|>docker_io_bitnami_wavefront_prometheus_storage_adapter_1_0_5_debian_11_r0
kube_state_metrics_3_0_0--[#orange]-|>docker_io_bitnami_kube_state_metrics_2_4_2_debian_10_r72
wavefront_4_0_1--[#orange]-|>docker_io_bitnami_wavefront_proxy_11_1_0_debian_10_r13

center footer Generated on 2022/06/15 22:40:43 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
