@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for wordpress:15.0.15

'There are 4 referenced Helm Charts
artifact "memcached:6.1.10\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmemcached\n\t\tcache" as memcached_6_1_10 #DarkSeaGreen
artifact "mariadb:11.1.6\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_11_1_6 #DarkTurquoise
artifact "wordpress:15.0.15\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tapplication\n\t\tblog\n\t\tcms\n\t\thttp\n\t\tphp\n\t\tweb\n\t\twordpress" as wordpress_15_0_15 #GreenYellow
artifact "common:1.16.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_16_1 #DarkSeaGreen

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/memcached:1.6.16-debian-11-r1\n====\n1.6.16-debian-11-r1" as docker_io_bitnami_memcached_1_6_16_debian_11_r1 #CadetBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/wordpress:6.0.1-debian-11-r11\n====\n6.0.1-debian-11-r11" as docker_io_bitnami_wordpress_6_0_1_debian_11_r11 #Darkorange
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.6.8-debian-11-r23\n====\n10.6.8-debian-11-r23" as docker_io_bitnami_mariadb_10_6_8_debian_11_r23 #DarkGoldenRod

'Chart Dependencies
wordpress_15_0_15--[#green]-|>common_1_16_1
wordpress_15_0_15--[#green]-|>mariadb_11_1_6
mariadb_11_1_6--[#green]-|>common_1_16_1
wordpress_15_0_15--[#green]-|>memcached_6_1_10
memcached_6_1_10--[#green]-|>common_1_16_1
memcached_6_1_10--[#orange]-|>docker_io_bitnami_memcached_1_6_16_debian_11_r1
mariadb_11_1_6--[#orange]-|>docker_io_bitnami_mariadb_10_6_8_debian_11_r23
wordpress_15_0_15--[#orange]-|>docker_io_bitnami_wordpress_6_0_1_debian_11_r11

center footer Generated on 2022/08/12 02:03:44 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
