@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-process-application:7.1.0-M7

'There are 9 referenced Helm Charts
artifact "rabbitmq-ha:1.38.1\n====\n\trabbitmq-ha\n====\n\t1.38.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: steven-sheehy\n====\n\tKeywords: rabbitmq\nmessage queue\nAMQP\nAMQPS\nMQTT\nSTOMP" as rabbitmq_ha_1_38_1 #Chocolate
artifact "common:1.1.36\n====\n\tcommon\n====\n\t1.1.36\n====\n\thttps://activiti.github.io/activiti-cloud-helm-charts\n====\n\tMaintainers: \n====\n\tKeywords: " as common_1_1_36 #DarkSeaGreen
artifact "alfresco-process-application:7.1.0-M7\n====\n\talfresco-process-application\n====\n\t7.1.0-M7\n====\n\thttps://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: \n====\n\tKeywords: process\nalfresco\nactiviti\nalfresco activiti enterprise" as alfresco_process_application_7_1_0_M7 #LightSeaGreen
artifact "common:1.1.28\n====\n\tcommon\n====\n\t1.1.28\n====\n\thttps://activiti.github.io/activiti-cloud-helm-charts\n====\n\tMaintainers: \n====\n\tKeywords: " as common_1_1_28 #DarkSeaGreen
artifact "alfresco-adf-app:2.1.4\n====\n\talfresco-adf-app\n====\n\t2.1.4\n====\n\thttps://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: alfresco\nadf\nalfresco development framework\ncontent\ncontent services\nalfresco content services\nprocess\nprocess services\nalfresco process services\nactiviti\nactiviti enterprise\nalfresco activiti enterprise" as alfresco_adf_app_2_1_4 #Fuchsia
artifact "postgresql:3.11.3\n====\n\tpostgresql\n====\n\t3.11.3\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: Bitnami, desaintmartin\n====\n\tKeywords: postgresql\npostgres\ndatabase\nsql\nreplication\ncluster" as postgresql_3_11_3 #LightSteelBlue
artifact "runtime-bundle:7.1.834\n====\n\truntime-bundle\n====\n\t7.1.834\n====\n\thttps://activiti.github.io/activiti-cloud-helm-charts\n====\n\tMaintainers: \n====\n\tKeywords: " as runtime_bundle_7_1_834 #Cyan
artifact "activiti-cloud-query:7.1.834\n====\n\tactiviti-cloud-query\n====\n\t7.1.834\n====\n\thttps://activiti.github.io/activiti-cloud-helm-charts\n====\n\tMaintainers: \n====\n\tKeywords: " as activiti_cloud_query_7_1_834 #Darkorange
artifact "activiti-cloud-connector:7.1.834\n====\n\tactiviti-cloud-connector\n====\n\t7.1.834\n====\n\thttps://activiti.github.io/activiti-cloud-helm-charts\n====\n\tMaintainers: \n====\n\tKeywords: " as activiti_cloud_connector_7_1_834 #Ivory

'There are 6 referenced Docker Images
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/postgresql:10.7.0\n====\n\t10.7.0" as docker_io_bitnami_postgresql_10_7_0 #DarkSalmon
usecase "Image\n====\n\tquay.io\n====\n\talfresco/alfresco-adf-app:latest\n====\n\tlatest" as quay_io_alfresco_alfresco_adf_app_latest #Cornsilk
usecase "Image\n====\n\tquay.io\n====\n\talfresco/alfresco-process-runtime-bundle-service:develop\n====\n\tdevelop" as quay_io_alfresco_alfresco_process_runtime_bundle_service_develop #Coral
usecase "Image\n====\n\tquay.io\n====\n\talfresco/alfresco-process-query-service:develop\n====\n\tdevelop" as quay_io_alfresco_alfresco_process_query_service_develop #DarkSeaGreen
usecase "Image\n====\n\tdocker.io\n====\n\tactiviti/activiti-cloud-connector:7.1.834\n====\n\t7.1.834" as docker_io_activiti_activiti_cloud_connector_7_1_834 #HotPink
usecase "Image\n====\n\tDocker Hub\n====\n\trabbitmq\n====\n\t3.8.0-alpine" as rabbitmq_3_8_0_alpine #Aqua

'Chart Dependencies
alfresco_process_application_7_1_0_M7--[#green]-|>postgresql_3_11_3
alfresco_process_application_7_1_0_M7--[#green]-|>activiti_cloud_query_7_1_834
activiti_cloud_query_7_1_834--[#green]-|>common_1_1_36
alfresco_process_application_7_1_0_M7--[#green]-|>alfresco_adf_app_2_1_4
alfresco_adf_app_2_1_4--[#green]-|>common_1_1_28
alfresco_process_application_7_1_0_M7--[#green]-|>rabbitmq_ha_1_38_1
alfresco_process_application_7_1_0_M7--[#green]-|>runtime_bundle_7_1_834
runtime_bundle_7_1_834--[#green]-|>common_1_1_36
alfresco_process_application_7_1_0_M7--[#green]-|>activiti_cloud_connector_7_1_834
activiti_cloud_connector_7_1_834--[#green]-|>common_1_1_36
rabbitmq_ha_1_38_1--[#orange]-|>rabbitmq_3_8_0_alpine
alfresco_adf_app_2_1_4--[#orange]-|>quay_io_alfresco_alfresco_adf_app_latest
postgresql_3_11_3--[#orange]-|>docker_io_bitnami_postgresql_10_7_0
runtime_bundle_7_1_834--[#orange]-|>quay_io_alfresco_alfresco_process_runtime_bundle_service_develop
activiti_cloud_query_7_1_834--[#orange]-|>quay_io_alfresco_alfresco_process_query_service_develop
activiti_cloud_connector_7_1_834--[#orange]-|>docker_io_activiti_activiti_cloud_connector_7_1_834

center footer Generated on 2020/04/26 13:00:44 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
