@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-dbp-connector-service:0.1.0

'There is one referenced Helm Chart
artifact "alfresco-dbp-connector-service:0.1.0\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: \n====\n\tKeywords: " as alfresco_dbp_connector_service_0_1_0 #LightPink

'There is one referenced Docker Image
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-dbp-connector-service:0.5.0-SNAPSHOT\n====\n0.5.0-SNAPSHOT" as quay_io_alfresco_alfresco_dbp_connector_service_0_5_0_SNAPSHOT #AntiqueWhite

'Chart Dependencies
alfresco_dbp_connector_service_0_1_0--[#orange]-|>quay_io_alfresco_alfresco_dbp_connector_service_0_5_0_SNAPSHOT

center footer Generated on 2022/05/15 11:38:41 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
