@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-infrastructure:5.2.1

'There are 7 referenced Helm Charts
artifact "alfresco-infrastructure:5.2.1\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: \n====\n\tKeywords: " as alfresco_infrastructure_5_2_1 #Cornsilk
artifact "postgresql:6.3.13\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_6_3_13 #LightSteelBlue
artifact "alfresco-event-gateway:0.1.2\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: \n\t\talfresco\n\t\tevents\n\t\tgateway" as alfresco_event_gateway_0_1_2 #Chartreuse
artifact "alfresco-identity-service:2.0.1\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: \n\t\talfresco\n\t\tkeycloak\n\t\tidentity-service" as alfresco_identity_service_2_0_1 #Chartreuse
artifact "keycloak:6.0.0\n====\n\tType: application\n====\n\tRepo: https://codecentric.github.io/helm-charts\n====\n\tMaintainers: \n\t\tunguiculus\n\t\tthomasdarimont\n====\n\tKeywords: \n\t\tsso\n\t\tidm\n\t\topenid connect\n\t\tsaml\n\t\tkerberos\n\t\tldap" as keycloak_6_0_0 #LightBlue
artifact "nginx-ingress:0.14.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tjackzampolin\n\t\tmgoodness\n\t\tchancez\n====\n\tKeywords: \n\t\tingress\n\t\tnginx" as nginx_ingress_0_14_0 #DarkSalmon
artifact "activemq:1.1.1\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tactivemq\n\t\tmessage broker" as activemq_1_1_1 #LightBlue

'There are 6 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nk8s.gcr.io/defaultbackend\n====\n1.3" as k8s_gcr_io_defaultbackend_1_3 #DarkSeaGreen
usecase "Image\n====\nDocker Hub\n====\nalfresco/alfresco-event-gateway\n====\n0.3-SNAPSHOT" as alfresco_alfresco_event_gateway_0_3_SNAPSHOT #LightSalmon
usecase "Image\n====\nquay.io\n====\nkubernetes-ingress-controller/nginx-ingress-controller:0.12.0\n====\n0.12.0" as quay_io_kubernetes_ingress_controller_nginx_ingress_controller_0_12_0 #LightSkyBlue
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-identity-service:1.3-A1\n====\n1.3-A1" as quay_io_alfresco_alfresco_identity_service_1_3_A1 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:11.5.0-debian-9-r60\n====\n11.5.0-debian-9-r60" as docker_io_bitnami_postgresql_11_5_0_debian_9_r60 #DarkSalmon
usecase "Image\n====\nDocker Hub\n====\nalfresco/alfresco-activemq\n====\n5.15.8-java-8-oracle-centos-7-87b15e37ce8b" as alfresco_alfresco_activemq_5_15_8_java_8_oracle_centos_7_87b15e37ce8b #Khaki

'Chart Dependencies
alfresco_infrastructure_5_2_1--[#green]-|>activemq_1_1_1
alfresco_infrastructure_5_2_1--[#green]-|>nginx_ingress_0_14_0
alfresco_infrastructure_5_2_1--[#green]-|>alfresco_event_gateway_0_1_2
alfresco_event_gateway_0_1_2--[#green]-|>activemq_1_1_1
alfresco_infrastructure_5_2_1--[#green]-|>alfresco_identity_service_2_0_1
alfresco_identity_service_2_0_1--[#green]-|>keycloak_6_0_0
keycloak_6_0_0--[#green]-|>postgresql_6_3_13
postgresql_6_3_13--[#orange]-|>docker_io_bitnami_postgresql_11_5_0_debian_9_r60
alfresco_event_gateway_0_1_2--[#orange]-|>alfresco_alfresco_event_gateway_0_3_SNAPSHOT
keycloak_6_0_0--[#orange]-|>quay_io_alfresco_alfresco_identity_service_1_3_A1
nginx_ingress_0_14_0--[#orange]-|>k8s_gcr_io_defaultbackend_1_3
nginx_ingress_0_14_0--[#orange]-|>quay_io_kubernetes_ingress_controller_nginx_ingress_controller_0_12_0
activemq_1_1_1--[#orange]-|>alfresco_alfresco_activemq_5_15_8_java_8_oracle_centos_7_87b15e37ce8b

center footer Generated on 2022/05/30 21:49:09 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
