@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-api-gateway:0.1.1

'There is one referenced Helm Chart
artifact "alfresco-api-gateway:0.1.1\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: " as alfresco_api_gateway_0_1_1 #BlanchedAlmond

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nalfresco/alfresco-api-gateway\n====\nlatest" as alfresco_alfresco_api_gateway_latest #Ivory

'Chart Dependencies
alfresco_api_gateway_0_1_1--[#orange]-|>alfresco_alfresco_api_gateway_latest

center footer Generated on 2022/05/30 21:17:26 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
