@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-template-service:0.1.0

'There is one referenced Helm Chart
artifact "alfresco-template-service:0.1.0\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: " as alfresco_template_service_0_1_0 #LightCyan

'There is one referenced Docker Image
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-template-service:latest\n====\nlatest" as quay_io_alfresco_alfresco_template_service_latest #LightGrey

'Chart Dependencies
alfresco_template_service_0_1_0--[#orange]-|>quay_io_alfresco_alfresco_template_service_latest

center footer Generated on 2022/05/15 11:45:44 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
