@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-activiti-cloud-registry:0.1.0

'There is one referenced Helm Chart
artifact "alfresco-activiti-cloud-registry:0.1.0\n====\n\talfresco-activiti-cloud-registry\n====\n\t0.1.0\n====\n\thttps://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: " as alfresco_activiti_cloud_registry_0_1_0 #LightSteelBlue

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tactiviti/activiti-cloud-registry\n====\n\tlatest" as activiti_activiti_cloud_registry_latest #CadetBlue

'Chart Dependencies
alfresco_activiti_cloud_registry_0_1_0--[#orange]-|>activiti_activiti_cloud_registry_latest

center footer Generated on 2020/04/26 12:58:39 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
