@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-adf-app:7.1.0-M11MOCK1

'There are 2 referenced Helm Charts
artifact "common:7.1.0-M11MOCK1\n====\n\tType: application\n====\n\tRepo: Unknown Repo URL\n====\n\tMaintainers: \n====\n\tKeywords: " as common_7_1_0_M11MOCK1 #DarkSeaGreen
artifact "alfresco-adf-app:7.1.0-M11MOCK1\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: \n\t\talfresco\n\t\tadf\n\t\talfresco development framework\n\t\tcontent\n\t\tcontent services\n\t\talfresco content services\n\t\tprocess\n\t\tprocess services\n\t\talfresco process services\n\t\tactiviti\n\t\tactiviti enterprise\n\t\talfresco activiti enterprise" as alfresco_adf_app_7_1_0_M11MOCK1 #Fuchsia

'There is one referenced Docker Image
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-adf-app:latest\n====\nlatest" as quay_io_alfresco_alfresco_adf_app_latest #Cornsilk

'Chart Dependencies
alfresco_adf_app_7_1_0_M11MOCK1--[#green]-|>common_7_1_0_M11MOCK1
alfresco_adf_app_7_1_0_M11MOCK1--[#orange]-|>quay_io_alfresco_alfresco_adf_app_latest

center footer Generated on 2022/05/22 13:03:19 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
