@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-process-infrastructure:22.2.0-mock1

'There are 10 referenced Helm Charts
artifact "common:1.4.1\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_4_1 #DarkSeaGreen
artifact "postgresql:9.1.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_9_1_1 #LightSteelBlue
artifact "alfresco-process-infrastructure:22.2.0-mock1\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tprocess\n\t\talfresco\n\t\tactiviti\n\t\talfresco activiti enterprise" as alfresco_process_infrastructure_22_2_0_mock1 #GoldenRod
artifact "alfresco-identity-service:5.0.0\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: \n\t\talfresco\n\t\tkeycloak\n\t\tidentity-service" as alfresco_identity_service_5_0_0 #Chartreuse
artifact "postgresql:10.3.13\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_10_3_13 #LightSteelBlue
artifact "keycloak:15.0.0\n====\n\tType: application\n====\n\tRepo: https://codecentric.github.io/helm-charts\n====\n\tMaintainers: \n\t\tunguiculus\n\t\tthomasdarimont\n====\n\tKeywords: \n\t\tsso\n\t\tidm\n\t\topenid connect\n\t\tsaml\n\t\tkerberos\n\t\tldap" as keycloak_15_0_0 #LightBlue
artifact "common:22.2.0-mock1\n====\n\tType: application\n====\n\tRepo: Unknown Repo URL\n====\n\tMaintainers: \n====\n\tKeywords: " as common_22_2_0_mock1 #DarkSeaGreen
artifact "rabbitmq:8.20.5\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\trabbitmq\n\t\tmessage queue\n\t\tAMQP" as rabbitmq_8_20_5 #Aqua
artifact "common:0.3.1\n====\n\tType: application\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_0_3_1 #DarkSeaGreen
artifact "common:1.8.0\n====\n\tType: library\n====\n\tRepo: https://charts.bitnami.com/bitnami\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tcommon\n\t\thelper\n\t\ttemplate\n\t\tfunction\n\t\tbitnami" as common_1_8_0 #DarkSeaGreen

'There are 4 referenced Docker Images
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-identity-service:1.6.0\n====\n1.6.0" as quay_io_alfresco_alfresco_identity_service_1_6_0 #Azure
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:11.11.0-debian-10-r31\n====\n11.11.0-debian-10-r31" as docker_io_bitnami_postgresql_11_11_0_debian_10_r31 #DarkSalmon
usecase "Image\n====\nDocker Hub\n====\ndocker.io/postgres\n====\n11.7" as docker_io_postgres_11_7 #LavenderBlush
usecase "Image\n====\ndocker.io\n====\nbitnami/rabbitmq:3.8.22-debian-10-r0\n====\n3.8.22-debian-10-r0" as docker_io_bitnami_rabbitmq_3_8_22_debian_10_r0 #Beige

'Chart Dependencies
alfresco_process_infrastructure_22_2_0_mock1--[#green]-|>alfresco_identity_service_5_0_0
alfresco_identity_service_5_0_0--[#green]-|>keycloak_15_0_0
keycloak_15_0_0--[#green]-|>postgresql_10_3_13
postgresql_10_3_13--[#green]-|>common_1_4_1
alfresco_process_infrastructure_22_2_0_mock1--[#green]-|>postgresql_9_1_1
postgresql_9_1_1--[#green]-|>common_0_3_1
alfresco_process_infrastructure_22_2_0_mock1--[#green]-|>rabbitmq_8_20_5
rabbitmq_8_20_5--[#green]-|>common_1_8_0
alfresco_process_infrastructure_22_2_0_mock1--[#green]-|>common_22_2_0_mock1
postgresql_9_1_1--[#orange]-|>docker_io_postgres_11_7
postgresql_10_3_13--[#orange]-|>docker_io_bitnami_postgresql_11_11_0_debian_10_r31
keycloak_15_0_0--[#orange]-|>quay_io_alfresco_alfresco_identity_service_1_6_0
rabbitmq_8_20_5--[#orange]-|>docker_io_bitnami_rabbitmq_3_8_22_debian_10_r0

center footer Generated on 2022/05/21 23:43:06 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
