@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for process-services-infrastructure:0.1.1

'There are 8 referenced Helm Charts
artifact "process-services-infrastructure:0.1.1\n====\n\tprocess-services-infrastructure\n====\n\t0.1.1\n====\n\thttps://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: \n====\n\tKeywords: " as process_services_infrastructure_0_1_1 #DarkTurquoise
artifact "keycloak:2.0.0\n====\n\tkeycloak\n====\n\t2.0.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: nexeck, unguiculus\n====\n\tKeywords: sso\nidm\nopenid connect\nsaml\nkerberos\nldap" as keycloak_2_0_0 #LightBlue
artifact "alfresco-identity-service:0.3.1\n====\n\talfresco-identity-service\n====\n\t0.3.1\n====\n\thttps://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: alfresco\nkeycloak\nidentity-service" as alfresco_identity_service_0_3_1 #Chartreuse
artifact "alfresco-infrastructure:2.0.0-SNAPSHOT\n====\n\talfresco-infrastructure\n====\n\t2.0.0-SNAPSHOT\n====\n\thttps://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: \n====\n\tKeywords: " as alfresco_infrastructure_2_0_0_SNAPSHOT #Cornsilk
artifact "activemq:0.1.0\n====\n\tactivemq\n====\n\t0.1.0\n====\n\thttps://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: \n====\n\tKeywords: " as activemq_0_1_0 #LightBlue
artifact "postgresql:0.12.0\n====\n\tpostgresql\n====\n\t0.12.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: databus23\n====\n\tKeywords: postgresql\npostgres\ndatabase\nsql" as postgresql_0_12_0 #LightSteelBlue
artifact "rabbitmq-ha:0.1.1\n====\n\trabbitmq-ha\n====\n\t0.1.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: etiennetremel\n====\n\tKeywords: rabbitmq\nmessage queue\nAMQP" as rabbitmq_ha_0_1_1 #Chocolate
artifact "nginx-ingress:0.14.0\n====\n\tnginx-ingress\n====\n\t0.14.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: jackzampolin, mgoodness, chancez\n====\n\tKeywords: ingress\nnginx" as nginx_ingress_0_14_0 #DarkSalmon

'There are 6 referenced Docker Images
usecase "Image\n====\n\tDocker Hub\n====\n\trabbitmq\n====\n\t3.7-alpine" as rabbitmq_3_7_alpine #Aqua
usecase "Image\n====\n\tDocker Hub\n====\n\tpostgres\n====\n\t9.6.2" as postgres_9_6_2 #Ivory
usecase "Image\n====\n\tDocker Hub\n====\n\tk8s.gcr.io/defaultbackend\n====\n\t1.3" as k8s_gcr_io_defaultbackend_1_3 #DarkSeaGreen
usecase "Image\n====\n\tDocker Hub\n====\n\twebcenter/activemq\n====\n\tlatest" as webcenter_activemq_latest #GhostWhite
usecase "Image\n====\n\tquay.io\n====\n\tkubernetes-ingress-controller/nginx-ingress-controller:0.12.0\n====\n\t0.12.0" as quay_io_kubernetes_ingress_controller_nginx_ingress_controller_0_12_0 #LightSkyBlue
usecase "Image\n====\n\tDocker Hub\n====\n\tjboss/keycloak\n====\n\t3.4.3.Final" as jboss_keycloak_3_4_3_Final #LemonChiffon

'Chart Dependencies
process_services_infrastructure_0_1_1--[#green]-|>alfresco_infrastructure_2_0_0_SNAPSHOT
alfresco_infrastructure_2_0_0_SNAPSHOT--[#green]-|>activemq_0_1_0
alfresco_infrastructure_2_0_0_SNAPSHOT--[#green]-|>rabbitmq_ha_0_1_1
alfresco_infrastructure_2_0_0_SNAPSHOT--[#green]-|>nginx_ingress_0_14_0
alfresco_infrastructure_2_0_0_SNAPSHOT--[#green]-|>alfresco_identity_service_0_3_1
alfresco_identity_service_0_3_1--[#green]-|>keycloak_2_0_0
keycloak_2_0_0--[#green]-|>postgresql_0_12_0
keycloak_2_0_0--[#orange]-|>jboss_keycloak_3_4_3_Final
activemq_0_1_0--[#orange]-|>webcenter_activemq_latest
postgresql_0_12_0--[#orange]-|>postgres_9_6_2
rabbitmq_ha_0_1_1--[#orange]-|>rabbitmq_3_7_alpine
nginx_ingress_0_14_0--[#orange]-|>k8s_gcr_io_defaultbackend_1_3
nginx_ingress_0_14_0--[#orange]-|>quay_io_kubernetes_ingress_controller_nginx_ingress_controller_0_12_0

center footer Generated on 2020/03/17 14:57:32 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
