@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for nuxeo-web-ui:0.0.1

'There is one referenced Helm Chart
artifact "nuxeo-web-ui:0.0.1\n====\n\tType: application\n====\n\tRepo: https://chartmuseum.platform.dev.nuxeo.com/\n====\n\tMaintainers: \n====\n\tKeywords: " as nuxeo_web_ui_0_0_1 #AntiqueWhite

'There is one referenced Docker Image
usecase "Image\n====\ndocker.packages.nuxeo.com\n====\nnuxeo/nuxeo-web-ui:3.0.0-SNAPSHOT\n====\n3.0.0-SNAPSHOT" as docker_packages_nuxeo_com_nuxeo_nuxeo_web_ui_3_0_0_SNAPSHOT #LightBlue

'Chart Dependencies
nuxeo_web_ui_0_0_1--[#orange]-|>docker_packages_nuxeo_com_nuxeo_nuxeo_web_ui_3_0_0_SNAPSHOT

center footer Generated on 2022/05/21 23:23:08 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
