@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for acs-engine-autoscaler:2.2.1

'There is one referenced Helm Chart
artifact "acs-engine-autoscaler:2.2.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tritazh\n\t\twbuchwalter\n====\n\tKeywords: " as acs_engine_autoscaler_2_2_1 #Lavender

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/06/15 22:42:02 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
