@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for auditbeat:1.1.0

'There is one referenced Helm Chart
artifact "auditbeat:1.1.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tcpanato\n\t\tmumoshu\n====\n\tKeywords: " as auditbeat_1_1_0 #LightPink

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/06/02 03:38:48 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
