@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for aws-iam-authenticator:0.1.5

'There is one referenced Helm Chart
artifact "aws-iam-authenticator:0.1.5\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: " as aws_iam_authenticator_0_1_5 #DarkSalmon

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/06/02 03:39:07 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
