@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for chronograf:1.0.3

'There is one referenced Helm Chart
artifact "chronograf:1.0.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: jackzampolin\n====\n\tKeywords: \n\t\tchronograf\n\t\tvisualizaion\n\t\ttimeseries" as chronograf_1_0_3 #DarkGoldenRod

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\ndocker.io/chronograf\n====\n1.7.11-alpine" as docker_io_chronograf_1_7_11_alpine #Cornsilk

'Chart Dependencies
chronograf_1_0_3--[#orange]-|>docker_io_chronograf_1_7_11_alpine

center footer Generated on 2022/06/02 03:41:33 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
