@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for cloudserver:1.0.4

'There are 3 referenced Helm Charts
artifact "cloudserver:1.0.4\n====\n\tcloudserver\n====\n\t1.0.4\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: ssalaues, tmacro\n====\n\tKeywords: " as cloudserver_1_0_4 #Cornsilk
artifact "redis-ha:3.0.0\n====\n\tredis-ha\n====\n\t3.0.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: ssalaues\n====\n\tKeywords: redis\nkeyvalue\ndatabase" as redis_ha_3_0_0 #IndianRed
artifact "mongodb-replicaset:3.6.4\n====\n\tmongodb-replicaset\n====\n\t3.6.4\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: foxish, unguiculus\n====\n\tKeywords: " as mongodb_replicaset_3_6_4 #Fuchsia

'There are 3 referenced Docker Images
usecase "Image\n====\n\tDocker Hub\n====\n\tzenko/cloudserver\n====\n\t8.1.5" as zenko_cloudserver_8_1_5 #CornflowerBlue
usecase "Image\n====\n\tDocker Hub\n====\n\tmongo\n====\n\t3.6" as mongo_3_6 #Aqua
usecase "Image\n====\n\tDocker Hub\n====\n\tredis\n====\n\t4.0.11-stretch" as redis_4_0_11_stretch #LightSeaGreen

'Chart Dependencies
cloudserver_1_0_4--[#green]-|>redis_ha_3_0_0
cloudserver_1_0_4--[#green]-|>mongodb_replicaset_3_6_4
cloudserver_1_0_4--[#orange]-|>zenko_cloudserver_8_1_5
redis_ha_3_0_0--[#orange]-|>redis_4_0_11_stretch
mongodb_replicaset_3_6_4--[#orange]-|>mongo_3_6

center footer Generated on 2020/04/26 13:42:38 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
