@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for cluster-overprovisioner:0.4.1

'There is one referenced Helm Chart
artifact "cluster-overprovisioner:0.4.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tcluster\n\t\tautoscaling\n\t\toverprovision\n\t\tcluster-autoscaler" as cluster_overprovisioner_0_4_1 #Gainsboro

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/06/15 22:46:37 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
