@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for dask:3.1.0

'There is one referenced Helm Chart
artifact "dask:3.1.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tdanielfrg\n\t\tmrocklin\n\t\tbeberg\n====\n\tKeywords: " as dask_3_1_0 #LightSteelBlue

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\ndaskdev/dask-notebook\n====\n1.1.5" as daskdev_dask_notebook_1_1_5 #CornflowerBlue
usecase "Image\n====\nDocker Hub\n====\ndaskdev/dask\n====\n1.1.5" as daskdev_dask_1_1_5 #LemonChiffon

'Chart Dependencies
dask_3_1_0--[#orange]-|>daskdev_dask_1_1_5
dask_3_1_0--[#orange]-|>daskdev_dask_notebook_1_1_5

center footer Generated on 2022/06/15 22:48:40 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
