@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for dex:2.15.1

'There is one referenced Helm Chart
artifact "dex:2.15.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tkfox1111\n\t\tsstarcher\n\t\trendhalver\n\t\tvi7\n====\n\tKeywords: \n\t\tdex\n\t\toidc" as dex_2_15_1 #LightSteelBlue

'There is one referenced Docker Image
usecase "Image\n====\nquay.io\n====\ndexidp/dex:v2.24.0\n====\nv2.24.0" as quay_io_dexidp_dex_v2_24_0 #DarkGoldenRod

'Chart Dependencies
dex_2_15_1--[#orange]-|>quay_io_dexidp_dex_v2_24_0

center footer Generated on 2022/06/02 03:45:40 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
