@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for distribution:0.4.3

'There are 3 referenced Helm Charts
artifact "distribution:0.4.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tdistribution\n\t\tjfrog" as distribution_0_4_3 #LawnGreen
artifact "redis:1.1.21\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: bitnami-bot\n====\n\tKeywords: \n\t\tredis\n\t\tkeyvalue\n\t\tdatabase" as redis_1_1_21 #LightSeaGreen
artifact "mongodb:2.0.5\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmongodb\n\t\tdatabase\n\t\tnosql" as mongodb_2_0_5 #GreenYellow

'There are 4 referenced Docker Images
usecase "Image\n====\ndocker.bintray.io\n====\njfrog/distribution-distribution:1.1.0\n====\n1.1.0" as docker_bintray_io_jfrog_distribution_distribution_1_1_0 #Beige
usecase "Image\n====\nDocker Hub\n====\nbitnami/redis\n====\n4.0.9-r0" as bitnami_redis_4_0_9_r0 #Khaki
usecase "Image\n====\ndocker.io\n====\nbitnami/mongodb:3.6.3\n====\n3.6.3" as docker_io_bitnami_mongodb_3_6_3 #Bisque
usecase "Image\n====\ndocker.bintray.io\n====\njfrog/distribution-distributor:1.1.0\n====\n1.1.0" as docker_bintray_io_jfrog_distribution_distributor_1_1_0 #Fuchsia

'Chart Dependencies
distribution_0_4_3--[#green]-|>mongodb_2_0_5
distribution_0_4_3--[#green]-|>redis_1_1_21
distribution_0_4_3--[#orange]-|>docker_bintray_io_jfrog_distribution_distribution_1_1_0
distribution_0_4_3--[#orange]-|>docker_bintray_io_jfrog_distribution_distributor_1_1_0
redis_1_1_21--[#orange]-|>bitnami_redis_4_0_9_r0
mongodb_2_0_5--[#orange]-|>docker_io_bitnami_mongodb_3_6_3

center footer Generated on 2022/08/12 02:12:33 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
