@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for docker-registry:1.9.4

'There is one referenced Helm Chart
artifact "docker-registry:1.9.4\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tjpds\n\t\trendhalver\n====\n\tKeywords: " as docker_registry_1_9_4 #BurlyWood

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nregistry\n====\n2.7.1" as registry_2_7_1 #Khaki

'Chart Dependencies
docker_registry_1_9_4--[#orange]-|>registry_2_7_1

center footer Generated on 2022/06/15 22:50:07 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
