@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for efs-provisioner:0.13.2

'There is one referenced Helm Chart
artifact "efs-provisioner:0.13.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: " as efs_provisioner_0_13_2 #Aqua

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/30 22:43:23 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
