@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for elasticsearch:1.32.3

'There is one referenced Helm Chart
artifact "elasticsearch:1.32.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tsimonswine\n\t\ticereval\n\t\trendhalver\n\t\tdesaintmartin\n\t\tKongZ\n\t\thectorj2f\n====\n\tKeywords: " as elasticsearch_1_32_3 #Aquamarine

'There is one referenced Docker Image
usecase "Image\n====\ndocker.elastic.co\n====\nelasticsearch/elasticsearch-oss:6.8.6\n====\n6.8.6" as docker_elastic_co_elasticsearch_elasticsearch_oss_6_8_6 #IndianRed

'Chart Dependencies
elasticsearch_1_32_3--[#orange]-|>docker_elastic_co_elasticsearch_elasticsearch_oss_6_8_6

center footer Generated on 2022/08/12 02:14:29 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
