@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for elasticsearch-exporter:3.6.0

'There is one referenced Helm Chart
artifact "elasticsearch-exporter:3.6.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tsvenmueller\n\t\tcaarlos0\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tmetrics\n\t\telasticsearch\n\t\tmonitoring" as elasticsearch_exporter_3_6_0 #Cornsilk

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\njustwatch/elasticsearch_exporter\n====\n1.1.0" as justwatch_elasticsearch_exporter_1_1_0 #HotPink

'Chart Dependencies
elasticsearch_exporter_3_6_0--[#orange]-|>justwatch_elasticsearch_exporter_1_1_0

center footer Generated on 2022/06/02 03:49:13 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
