@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for eventrouter:0.3.0

'There is one referenced Helm Chart
artifact "eventrouter:0.3.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: gianrubio\n====\n\tKeywords: eventrouter" as eventrouter_0_3_0 #Gold

'There is one referenced Docker Image
usecase "Image\n====\ngcr.io\n====\nheptio-images/eventrouter:v0.3\n====\nv0.3" as gcr_io_heptio_images_eventrouter_v0_3 #Cornsilk

'Chart Dependencies
eventrouter_0_3_0--[#orange]-|>gcr_io_heptio_images_eventrouter_v0_3

center footer Generated on 2022/08/12 02:15:31 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
