@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for fluent-bit:2.10.2

'There is one referenced Helm Chart
artifact "fluent-bit:2.10.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tkfox1111\n\t\tedsiper\n\t\thectorj2f\n====\n\tKeywords: \n\t\tlogging\n\t\tmonitoring\n\t\tfluent\n\t\tfluentd" as fluent_bit_2_10_2 #AntiqueWhite

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/08/12 02:16:32 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
