@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for gcp-night-king:1.0.3

'There is one referenced Helm Chart
artifact "gcp-night-king:1.0.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: itamaro\n====\n\tKeywords: " as gcp_night_king_1_0_3 #AliceBlue

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/06/02 03:53:17 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
