@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for graylog:1.6.9

'There are 3 referenced Helm Charts
artifact "mongodb-replicaset:3.11.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tunguiculus\n\t\tsteven-sheehy\n====\n\tKeywords: " as mongodb_replicaset_3_11_2 #Fuchsia
artifact "elasticsearch:1.32.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tsimonswine\n\t\ticereval\n\t\trendhalver\n\t\tdesaintmartin\n\t\tKongZ\n\t\thectorj2f\n====\n\tKeywords: " as elasticsearch_1_32_2 #Aquamarine
artifact "graylog:1.6.9\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: KongZ\n====\n\tKeywords: \n\t\tgraylog\n\t\tlogs\n\t\tsyslog\n\t\tgelf" as graylog_1_6_9 #LightGreen

'There are 3 referenced Docker Images
usecase "Image\n====\ndocker.elastic.co\n====\nelasticsearch/elasticsearch-oss:6.5.4\n====\n6.5.4" as docker_elastic_co_elasticsearch_elasticsearch_oss_6_5_4 #IndianRed
usecase "Image\n====\nDocker Hub\n====\ngraylog/graylog\n====\n3.1" as graylog_graylog_3_1 #FloralWhite
usecase "Image\n====\nDocker Hub\n====\nmongo\n====\n3.6" as mongo_3_6 #Aqua

'Chart Dependencies
graylog_1_6_9--[#green]-|>mongodb_replicaset_3_11_2
graylog_1_6_9--[#green]-|>elasticsearch_1_32_2
mongodb_replicaset_3_11_2--[#orange]-|>mongo_3_6
elasticsearch_1_32_2--[#orange]-|>docker_elastic_co_elasticsearch_elasticsearch_oss_6_5_4
graylog_1_6_9--[#orange]-|>graylog_graylog_3_1

center footer Generated on 2022/08/12 02:19:28 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
