@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for hoard:1.0.1

'There is one referenced Helm Chart
artifact "hoard:1.0.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tcompleatang\n\t\tgregdhill\n====\n\tKeywords: \n\t\ts3\n\t\taws\n\t\tgcp\n\t\tazure\n\t\tipfs\n\t\tenvelope encryption\n\t\tcontent addressable\n\t\tdistributed file storage" as hoard_1_0_1 #Aqua

'There is one referenced Docker Image
usecase "Image\n====\nquay.io\n====\nmonax/hoard:6.0.0\n====\n6.0.0" as quay_io_monax_hoard_6_0_0 #LightGreen

'Chart Dependencies
hoard_1_0_1--[#orange]-|>quay_io_monax_hoard_6_0_0

center footer Generated on 2022/06/15 22:58:35 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
