@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for ipfs:0.4.4

'There is one referenced Helm Chart
artifact "ipfs:0.4.4\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tipfs\n\t\tdistributed-web" as ipfs_0_4_4 #AliceBlue

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nipfs/go-ipfs\n====\nv0.4.22" as ipfs_go_ipfs_v0_4_22 #Khaki

'Chart Dependencies
ipfs_0_4_4--[#orange]-|>ipfs_go_ipfs_v0_4_22

center footer Generated on 2022/08/12 02:23:16 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
