@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for k8s-spot-termination-handler:1.4.11

'There is one referenced Helm Chart
artifact "k8s-spot-termination-handler:1.4.11\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tspot\n\t\ttermination" as k8s_spot_termination_handler_1_4_11 #FloralWhite

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/06/15 23:01:17 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
