@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for keycloak:4.10.0

'There are 2 referenced Helm Charts
artifact "keycloak:4.10.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tunguiculus\n\t\tthomasdarimont\n====\n\tKeywords: \n\t\tsso\n\t\tidm\n\t\topenid connect\n\t\tsaml\n\t\tkerberos\n\t\tldap" as keycloak_4_10_0 #LightBlue
artifact "postgresql:0.15.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: databus23\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql" as postgresql_0_15_0 #LightSteelBlue

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\npostgres\n====\n9.6.2" as postgres_9_6_2 #Ivory
usecase "Image\n====\nDocker Hub\n====\njboss/keycloak\n====\n5.0.0" as jboss_keycloak_5_0_0 #LemonChiffon

'Chart Dependencies
keycloak_4_10_0--[#green]-|>postgresql_0_15_0
keycloak_4_10_0--[#orange]-|>jboss_keycloak_5_0_0
postgresql_0_15_0--[#orange]-|>postgres_9_6_2

center footer Generated on 2022/08/12 02:25:48 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
