@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kubed:0.3.1

'There is one referenced Helm Chart
artifact "kubed:0.3.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: appscode\n====\n\tKeywords: " as kubed_0_3_1 #LightSeaGreen

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nappscode/kubed\n====\n0.4.0" as appscode_kubed_0_4_0 #FloralWhite

'Chart Dependencies
kubed_0_3_1--[#orange]-|>appscode_kubed_0_4_0

center footer Generated on 2022/08/12 02:27:46 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
