@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kube-slack:1.2.0

'There is one referenced Helm Chart
artifact "kube-slack:1.2.0\n====\n\tkube-slack\n====\n\t1.2.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: jstriebel\n====\n\tKeywords: kubernetes\nmonitoring\nslack" as kube_slack_1_2_0 #DarkSalmon

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\twillwill/kube-slack\n====\n\tv4.2.0" as willwill_kube_slack_v4_2_0 #LavenderBlush

'Chart Dependencies
kube_slack_1_2_0--[#orange]-|>willwill_kube_slack_v4_2_0

center footer Generated on 2020/03/16 17:21:27 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
