@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for kube-state-metrics:2.8.1

'There is one referenced Helm Chart
artifact "kube-state-metrics:2.8.1\n====\n\tkube-state-metrics\n====\n\t2.8.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: fiunchinho, tariq1890, mrueg\n====\n\tKeywords: metric\nmonitoring\nprometheus\nkubernetes" as kube_state_metrics_2_8_1 #Gainsboro

'There is one referenced Docker Image
usecase "Image\n====\n\tquay.io\n====\n\tcoreos/kube-state-metrics:v1.9.5\n====\n\tv1.9.5" as quay_io_coreos_kube_state_metrics_v1_9_5 #LightGrey

'Chart Dependencies
kube_state_metrics_2_8_1--[#orange]-|>quay_io_coreos_kube_state_metrics_v1_9_5

center footer Generated on 2020/04/21 20:28:55 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
