@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for mattermost-team-edition:3.1.1

'There are 2 referenced Helm Charts
artifact "mysql:0.10.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tolemarkus\n\t\tviglesiasce\n====\n\tKeywords: \n\t\tmysql\n\t\tdatabase\n\t\tsql" as mysql_0_10_1 #Aqua
artifact "mattermost-team-edition:3.1.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tcpanato\n\t\tjwilander\n====\n\tKeywords: \n\t\tmattermost\n\t\tcommunication\n\t\tteam collaboration" as mattermost_team_edition_3_1_1 #Bisque

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nmysql\n====\n5.7.14" as mysql_5_7_14 #Aqua
usecase "Image\n====\nDocker Hub\n====\nmattermost/mattermost-team-edition\n====\n5.9.0" as mattermost_mattermost_team_edition_5_9_0 #LawnGreen

'Chart Dependencies
mattermost_team_edition_3_1_1--[#green]-|>mysql_0_10_1
mysql_0_10_1--[#orange]-|>mysql_5_7_14
mattermost_team_edition_3_1_1--[#orange]-|>mattermost_mattermost_team_edition_5_9_0

center footer Generated on 2022/06/15 23:07:32 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
