@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for mediawiki:9.1.8

'There are 2 referenced Helm Charts
artifact "mariadb:7.3.10\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_7_3_10 #DarkTurquoise
artifact "mediawiki:9.1.8\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tmediawiki\n\t\twiki\n\t\thttp\n\t\tweb\n\t\tapplication\n\t\tphp" as mediawiki_9_1_8 #LightSteelBlue

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.3.22-debian-10-r17\n====\n10.3.22-debian-10-r17" as docker_io_bitnami_mariadb_10_3_22_debian_10_r17 #DarkGoldenRod

'Chart Dependencies
mediawiki_9_1_8--[#green]-|>mariadb_7_3_10
mariadb_7_3_10--[#orange]-|>docker_io_bitnami_mariadb_10_3_22_debian_10_r17

center footer Generated on 2022/06/15 23:07:54 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
