@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for metabase:0.10.6

'There is one referenced Helm Chart
artifact "metabase:0.10.6\n====\n\tmetabase\n====\n\t0.10.6\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: pmint93\n====\n\tKeywords: " as metabase_0_10_6 #Chartreuse

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tmetabase/metabase\n====\n\tv0.34.3" as metabase_metabase_v0_34_3 #GhostWhite

'Chart Dependencies
metabase_0_10_6--[#orange]-|>metabase_metabase_v0_34_3

center footer Generated on 2020/04/26 13:52:41 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
