@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for minecraft:1.2.5

'There is one referenced Helm Chart
artifact "minecraft:1.2.5\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tgame\n\t\tserver" as minecraft_1_2_5 #Khaki

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/06/15 23:09:01 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
