@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for mission-control:0.4.3

'There are 3 referenced Helm Charts
artifact "mission-control:0.4.3\n====\n\tmission-control\n====\n\t0.4.3\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: \n====\n\tKeywords: mission-control\njfrog" as mission_control_0_4_3 #IndianRed
artifact "elasticsearch:0.1.0\n====\n\telasticsearch\n====\n\t0.1.0\n====\n\thttps://kubernetes-charts-incubator.storage.googleapis.com\n====\n\tMaintainers: Christian Simon\n====\n\tKeywords: " as elasticsearch_0_1_0 #Aquamarine
artifact "mongodb:2.0.5\n====\n\tmongodb\n====\n\t2.0.5\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: mongodb\ndatabase\nnosql" as mongodb_2_0_5 #GreenYellow

'There are 2 referenced Docker Images
usecase "Image\n====\n\tdocker.bintray.io\n====\n\telasticsearch/elasticsearch:6.1.1\n====\n\t6.1.1" as docker_bintray_io_elasticsearch_elasticsearch_6_1_1 #LightGrey
usecase "Image\n====\n\tdocker.io\n====\n\tbitnami/mongodb:3.6.4\n====\n\t3.6.4" as docker_io_bitnami_mongodb_3_6_4 #Bisque

'Chart Dependencies
mission_control_0_4_3--[#green]-|>elasticsearch_0_1_0
mission_control_0_4_3--[#green]-|>mongodb_2_0_5
elasticsearch_0_1_0--[#orange]-|>docker_bintray_io_elasticsearch_elasticsearch_6_1_1
mongodb_2_0_5--[#orange]-|>docker_io_bitnami_mongodb_3_6_4

center footer Generated on 2020/04/26 13:53:08 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
