@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for mongodb-replicaset:3.13.1

'There is one referenced Helm Chart
artifact "mongodb-replicaset:3.13.1\n====\n\tmongodb-replicaset\n====\n\t3.13.1\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: unguiculus, steven-sheehy\n====\n\tKeywords: " as mongodb_replicaset_3_13_1 #Fuchsia

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\tmongo\n====\n\t3.6" as mongo_3_6 #Aqua

'Chart Dependencies
mongodb_replicaset_3_13_1--[#orange]-|>mongo_3_6

center footer Generated on 2020/03/16 17:23:54 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
