@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for msoms:0.2.2

'There is one referenced Helm Chart
artifact "msoms:0.2.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tmonitoring\n\t\talerting\n\t\tmetric\n\t\tevent\n\t\tlogging" as msoms_0_2_2 #LightSeaGreen

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/06/02 04:13:28 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
