@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for nginx-lego:0.3.1

'There is one referenced Helm Chart
artifact "nginx-lego:0.3.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: Jack Zampolin\n====\n\tKeywords: \n\t\tkube-lego\n\t\tnginx-ingress-controller\n\t\tnginx\n\t\tletsencrypt" as nginx_lego_0_3_1 #FloralWhite

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nk8s.gcr.io/nginx-ingress-controller\n====\n0.8.3" as k8s_gcr_io_nginx_ingress_controller_0_8_3 #DarkSeaGreen
usecase "Image\n====\nDocker Hub\n====\nk8s.gcr.io/defaultbackend\n====\n1.0" as k8s_gcr_io_defaultbackend_1_0 #DarkSeaGreen

'Chart Dependencies
nginx_lego_0_3_1--[#orange]-|>k8s_gcr_io_defaultbackend_1_0
nginx_lego_0_3_1--[#orange]-|>k8s_gcr_io_nginx_ingress_controller_0_8_3

center footer Generated on 2022/06/15 23:12:18 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
