@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for node-red:1.4.2

'There is one referenced Helm Chart
artifact "node-red:1.4.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tbillimek\n\t\tbatazor\n====\n\tKeywords: \n\t\tnodered\n\t\tnode-red" as node_red_1_4_2 #GhostWhite

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nnodered/node-red\n====\n1.0.4-12-minimal" as nodered_node_red_1_0_4_12_minimal #GreenYellow

'Chart Dependencies
node_red_1_4_2--[#orange]-|>nodered_node_red_1_0_4_12_minimal

center footer Generated on 2022/08/12 02:36:14 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
