@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for percona:1.2.2

'There is one referenced Helm Chart
artifact "percona:1.2.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: CaptTofu\n====\n\tKeywords: \n\t\tmysql\n\t\tpercona\n\t\tdatabase\n\t\tsql" as percona_1_2_2 #DarkGoldenRod

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\npercona\n====\n5.7.26" as percona_5_7_26 #DarkGoldenRod

'Chart Dependencies
percona_1_2_2--[#orange]-|>percona_5_7_26

center footer Generated on 2022/06/15 23:15:24 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
