@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for prisma:1.2.2

'There is one referenced Helm Chart
artifact "prisma:1.2.2\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: giacomoguiulfo\n====\n\tKeywords: " as prisma_1_2_2 #FloralWhite

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\nprismagraphql/prisma\n====\n1.29.1-heroku" as prismagraphql_prisma_1_29_1_heroku #AntiqueWhite

'Chart Dependencies
prisma_1_2_2--[#orange]-|>prismagraphql_prisma_1_29_1_heroku

center footer Generated on 2022/08/12 02:40:54 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
