@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for rabbitmq-ha:1.41.0

'There is one referenced Helm Chart
artifact "rabbitmq-ha:1.41.0\n====\n\trabbitmq-ha\n====\n\t1.41.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: steven-sheehy\n====\n\tKeywords: rabbitmq\nmessage queue\nAMQP\nAMQPS\nMQTT\nSTOMP" as rabbitmq_ha_1_41_0 #Chocolate

'There is one referenced Docker Image
usecase "Image\n====\n\tDocker Hub\n====\n\trabbitmq\n====\n\t3.8.0-alpine" as rabbitmq_3_8_0_alpine #Aqua

'Chart Dependencies
rabbitmq_ha_1_41_0--[#orange]-|>rabbitmq_3_8_0_alpine

center footer Generated on 2020/03/16 17:28:24 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
