@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for rocketchat:2.0.7

'There are 2 referenced Helm Charts
artifact "rocketchat:2.0.7\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tRocketChat\n\t\tgeekgonecrazy\n\t\tpierreozoux\n\t\tverwilst\n\t\tsrueg\n====\n\tKeywords: \n\t\tchat\n\t\tcommunication\n\t\thttp\n\t\tweb\n\t\tapplication\n\t\tnodejs\n\t\tjavascript\n\t\tmeteor" as rocketchat_2_0_7 #Beige
artifact "mongodb:7.8.10\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tmongodb\n\t\tdatabase\n\t\tnosql\n\t\tcluster\n\t\treplicaset\n\t\treplication" as mongodb_7_8_10 #GreenYellow

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nrocketchat/rocket.chat:3.6.0\n====\n3.6.0" as docker_io_rocketchat_rocket_chat_3_6_0 #DodgerBlue
usecase "Image\n====\ndocker.io\n====\nbitnami/mongodb:4.2.4-debian-10-r0\n====\n4.2.4-debian-10-r0" as docker_io_bitnami_mongodb_4_2_4_debian_10_r0 #Bisque

'Chart Dependencies
rocketchat_2_0_7--[#green]-|>mongodb_7_8_10
rocketchat_2_0_7--[#orange]-|>docker_io_rocketchat_rocket_chat_3_6_0
mongodb_7_8_10--[#orange]-|>docker_io_bitnami_mongodb_4_2_4_debian_10_r0

center footer Generated on 2022/08/12 02:45:50 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
