@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for satisfy:1.0.0

'There is one referenced Helm Chart
artifact "satisfy:1.0.0\n====\n\tsatisfy\n====\n\t1.0.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: anapsix\n====\n\tKeywords: " as satisfy_1_0_0 #Bisque

'There is one referenced Docker Image
usecase "Image\n====\n\tdocker.io\n====\n\tanapsix/satisfy@sha256:fae78e3809e9d08990c7d7d6699a734f7e584c28ce49381a1a699e1694481ab8\n====\n\tfae78e3809e9d08990c7d7d6699a734f7e584c28ce49381a1a699e1694481ab8" as docker_io_anapsix_satisfy@sha256_fae78e3809e9d08990c7d7d6699a734f7e584c28ce49381a1a699e1694481ab8 #DarkGoldenRod

'Chart Dependencies
satisfy_1_0_0--[#orange]-|>docker_io_anapsix_satisfy@sha256_fae78e3809e9d08990c7d7d6699a734f7e584c28ce49381a1a699e1694481ab8

center footer Generated on 2020/04/26 13:59:19 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
