@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for searchlight:0.3.1

'There is one referenced Helm Chart
artifact "searchlight:0.3.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: appscode\n====\n\tKeywords: " as searchlight_0_3_1 #Coral

'There are 3 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nappscode/postgres\n====\n9.5-alpine" as appscode_postgres_9_5_alpine #Aquamarine
usecase "Image\n====\nDocker Hub\n====\nappscode/searchlight\n====\n5.0.0" as appscode_searchlight_5_0_0 #DeepSkyBlue
usecase "Image\n====\nDocker Hub\n====\nappscode/icinga\n====\n5.0.0-k8s" as appscode_icinga_5_0_0_k8s #AliceBlue

'Chart Dependencies
searchlight_0_3_1--[#orange]-|>appscode_postgres_9_5_alpine
searchlight_0_3_1--[#orange]-|>appscode_icinga_5_0_0_k8s
searchlight_0_3_1--[#orange]-|>appscode_searchlight_5_0_0

center footer Generated on 2022/08/12 02:46:53 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
