@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for sonarqube:3.4.1

'There are 2 referenced Helm Charts
artifact "postgresql:8.2.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_8_2_0 #LightSteelBlue
artifact "sonarqube:3.4.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\trjkernick\n\t\ttsiddique\n====\n\tKeywords: \n\t\tcoverage\n\t\tsecurity\n\t\tcode\n\t\tquality" as sonarqube_3_4_1 #Azure

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:11.6.0-debian-10-r0\n====\n11.6.0-debian-10-r0" as docker_io_bitnami_postgresql_11_6_0_debian_10_r0 #DarkSalmon
usecase "Image\n====\nDocker Hub\n====\nsonarqube\n====\n7.9.2-community" as sonarqube_7_9_2_community #Azure

'Chart Dependencies
sonarqube_3_4_1--[#green]-|>postgresql_8_2_0
postgresql_8_2_0--[#orange]-|>docker_io_bitnami_postgresql_11_6_0_debian_10_r0
sonarqube_3_4_1--[#orange]-|>sonarqube_7_9_2_community

center footer Generated on 2022/08/12 02:48:38 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
