@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for spark:1.0.3

'There is one referenced Helm Chart
artifact "spark:1.0.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tlachie83\n\t\tdaixiang0\n====\n\tKeywords: " as spark_1_0_3 #LightSeaGreen

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nk8s.gcr.io/spark\n====\n1.5.1_v3" as k8s_gcr_io_spark_1_5_1_v3 #Fuchsia
usecase "Image\n====\nDocker Hub\n====\napache/zeppelin\n====\n0.7.3" as apache_zeppelin_0_7_3 #LightGrey

'Chart Dependencies
spark_1_0_3--[#orange]-|>k8s_gcr_io_spark_1_5_1_v3
spark_1_0_3--[#orange]-|>apache_zeppelin_0_7_3

center footer Generated on 2022/08/12 02:48:59 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
