@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for sysdig:1.7.16

'There is one referenced Helm Chart
artifact "sysdig:1.7.16\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tmonitoring\n\t\tsecurity\n\t\talerting\n\t\tmetric\n\t\ttroubleshooting\n\t\trun-time" as sysdig_1_7_16 #GreenYellow

'There are 0 referenced Docker Images

'Chart Dependencies

center footer Generated on 2022/05/30 23:33:48 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
