@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for testlink:7.1.5

'There are 2 referenced Helm Charts
artifact "testlink:7.1.5\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\ttestlink\n\t\ttesting\n\t\thttp\n\t\tphp" as testlink_7_1_5 #Gold
artifact "mariadb:7.3.12\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: Bitnami\n====\n\tKeywords: \n\t\tmariadb\n\t\tmysql\n\t\tdatabase\n\t\tsql\n\t\tprometheus" as mariadb_7_3_12 #DarkTurquoise

'There are 2 referenced Docker Images
usecase "Image\n====\ndocker.io\n====\nbitnami/mariadb:10.3.22-debian-10-r27\n====\n10.3.22-debian-10-r27" as docker_io_bitnami_mariadb_10_3_22_debian_10_r27 #DarkGoldenRod
usecase "Image\n====\ndocker.io\n====\nbitnami/testlink:1.9.20-debian-10-r19\n====\n1.9.20-debian-10-r19" as docker_io_bitnami_testlink_1_9_20_debian_10_r19 #HoneyDew

'Chart Dependencies
testlink_7_1_5--[#green]-|>mariadb_7_3_12
testlink_7_1_5--[#orange]-|>docker_io_bitnami_testlink_1_9_20_debian_10_r19
mariadb_7_3_12--[#orange]-|>docker_io_bitnami_mariadb_10_3_22_debian_10_r27

center footer Generated on 2022/06/15 23:29:11 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
