@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for tomcat:0.4.1

'There is one referenced Helm Chart
artifact "tomcat:0.4.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: yahavb\n====\n\tKeywords: " as tomcat_0_4_1 #Darkorange

'There is one referenced Docker Image
usecase "Image\n====\nDocker Hub\n====\ntomcat\n====\n7.0" as tomcat_7_0 #Darkorange

'Chart Dependencies
tomcat_0_4_1--[#orange]-|>tomcat_7_0

center footer Generated on 2022/06/15 23:29:21 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
