@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-sync-service:3.0.3

'There are 2 referenced Helm Charts
artifact "postgresql:0.9.3\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: databus23\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql" as postgresql_0_9_3 #LightSteelBlue
artifact "alfresco-sync-service:3.0.3\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: Alfresco Apps Repo Team\n====\n\tKeywords: \n\t\tsyncservice\n\t\talfresco\n\t\tapplication" as alfresco_sync_service_3_0_3 #CadetBlue

'There are 2 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\npostgres\n====\n10.1" as postgres_10_1 #Ivory
usecase "Image\n====\nquay.io\n====\nalfresco/service-sync:3.3.1\n====\n3.3.1" as quay_io_alfresco_service_sync_3_3_1 #LightPink

'Chart Dependencies
alfresco_sync_service_3_0_3--[#green]-|>postgresql_0_9_3
postgresql_0_9_3--[#orange]-|>postgres_10_1
alfresco_sync_service_3_0_3--[#orange]-|>quay_io_alfresco_service_sync_3_3_1

center footer Generated on 2022/05/21 23:33:29 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
