@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-content-services-community:6.0.5-ea

'There are 2 referenced Helm Charts
artifact "postgresql:0.9.3\n====\n\tpostgresql\n====\n\t0.9.3\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: databus23\n====\n\tKeywords: postgresql\npostgres\ndatabase\nsql" as postgresql_0_9_3 #LightSteelBlue
artifact "alfresco-content-services-community:6.0.5-ea\n====\n\talfresco-content-services-community\n====\n\t6.0.5-ea\n====\n\thttps://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: \n====\n\tKeywords: alfresco\ncommunity\nalfresco community\ncontent\ncontent services" as alfresco_content_services_community_6_0_5_ea #LightSkyBlue

'There are 4 referenced Docker Images
usecase "Image\n====\n\tDocker Hub\n====\n\talfresco/alfresco-share\n====\n\t6.0.a" as alfresco_alfresco_share_6_0_a #LightSalmon
usecase "Image\n====\n\tDocker Hub\n====\n\tpostgres\n====\n\t10.1" as postgres_10_1 #Ivory
usecase "Image\n====\n\tDocker Hub\n====\n\talfresco/alfresco-content-repository-community\n====\n\t6.0.5-ea" as alfresco_alfresco_content_repository_community_6_0_5_ea #Aqua
usecase "Image\n====\n\tDocker Hub\n====\n\talfresco/alfresco-search-services\n====\n\t1.1.1" as alfresco_alfresco_search_services_1_1_1 #Coral

'Chart Dependencies
alfresco_content_services_community_6_0_5_ea--[#green]-|>postgresql_0_9_3
postgresql_0_9_3--[#orange]-|>postgres_10_1
alfresco_content_services_community_6_0_5_ea--[#orange]-|>alfresco_alfresco_content_repository_community_6_0_5_ea
alfresco_content_services_community_6_0_5_ea--[#orange]-|>alfresco_alfresco_search_services_1_1_1
alfresco_content_services_community_6_0_5_ea--[#orange]-|>alfresco_alfresco_share_6_0_a

center footer Generated on 2020/03/21 16:05:14 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
