@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-process-application:7.1.0-M9

'There are 8 referenced Helm Charts
artifact "runtime-bundle:7.1.0-M9\n====\n\tType: application\n====\n\tRepo: N/A - Explicit Dependency\n====\n\tMaintainers: \n====\n\tKeywords: " as runtime_bundle_7_1_0_M9 #Cyan
artifact "rabbitmq-ha:1.38.1\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: steven-sheehy\n====\n\tKeywords: \n\t\trabbitmq\n\t\tmessage queue\n\t\tAMQP\n\t\tAMQPS\n\t\tMQTT\n\t\tSTOMP" as rabbitmq_ha_1_38_1 #Chocolate
artifact "alfresco-adf-app:2.2.2\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: \n\t\talfresco\n\t\tadf\n\t\talfresco development framework\n\t\tcontent\n\t\tcontent services\n\t\talfresco content services\n\t\tprocess\n\t\tprocess services\n\t\talfresco process services\n\t\tactiviti\n\t\tactiviti enterprise\n\t\talfresco activiti enterprise" as alfresco_adf_app_2_2_2 #Fuchsia
artifact "alfresco-process-application:7.1.0-M9\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: \n====\n\tKeywords: \n\t\tprocess\n\t\talfresco\n\t\tactiviti\n\t\talfresco activiti enterprise" as alfresco_process_application_7_1_0_M9 #LightSeaGreen
artifact "activiti-cloud-query:7.1.0-M9\n====\n\tType: application\n====\n\tRepo: N/A - Explicit Dependency\n====\n\tMaintainers: \n====\n\tKeywords: " as activiti_cloud_query_7_1_0_M9 #Darkorange
artifact "postgresql:6.3.9\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: \n\t\tBitnami\n\t\tdesaintmartin\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql\n\t\treplication\n\t\tcluster" as postgresql_6_3_9 #LightSteelBlue
artifact "activiti-cloud-connector:7.1.0-M9\n====\n\tType: application\n====\n\tRepo: N/A - Explicit Dependency\n====\n\tMaintainers: \n====\n\tKeywords: " as activiti_cloud_connector_7_1_0_M9 #Ivory
artifact "common:7.1.0-M9\n====\n\tType: application\n====\n\tRepo: N/A - Explicit Dependency\n====\n\tMaintainers: \n====\n\tKeywords: " as common_7_1_0_M9 #DarkSeaGreen

'There are 6 referenced Docker Images
usecase "Image\n====\nDocker Hub\n====\nactiviti/example-cloud-connector\n====\n7.1.0-M9" as activiti_example_cloud_connector_7_1_0_M9 #DarkSeaGreen
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-adf-app:latest\n====\nlatest" as quay_io_alfresco_alfresco_adf_app_latest #Cornsilk
usecase "Image\n====\ndocker.io\n====\nbitnami/postgresql:11.5.0-debian-9-r34\n====\n11.5.0-debian-9-r34" as docker_io_bitnami_postgresql_11_5_0_debian_9_r34 #DarkSalmon
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-process-runtime-bundle-service:develop\n====\ndevelop" as quay_io_alfresco_alfresco_process_runtime_bundle_service_develop #Coral
usecase "Image\n====\nquay.io\n====\nalfresco/alfresco-process-query-service:develop\n====\ndevelop" as quay_io_alfresco_alfresco_process_query_service_develop #DarkSeaGreen
usecase "Image\n====\nDocker Hub\n====\nrabbitmq\n====\n3.8.0-alpine" as rabbitmq_3_8_0_alpine #Aqua

'Chart Dependencies
alfresco_process_application_7_1_0_M9--[#green]-|>activiti_cloud_connector_7_1_0_M9
activiti_cloud_connector_7_1_0_M9--[#green]-|>common_7_1_0_M9
alfresco_process_application_7_1_0_M9--[#green]-|>rabbitmq_ha_1_38_1
alfresco_process_application_7_1_0_M9--[#green]-|>alfresco_adf_app_2_2_2
alfresco_adf_app_2_2_2--[#green]-|>common_7_1_0_M9
alfresco_process_application_7_1_0_M9--[#green]-|>runtime_bundle_7_1_0_M9
runtime_bundle_7_1_0_M9--[#green]-|>common_7_1_0_M9
alfresco_process_application_7_1_0_M9--[#green]-|>activiti_cloud_query_7_1_0_M9
activiti_cloud_query_7_1_0_M9--[#green]-|>common_7_1_0_M9
alfresco_process_application_7_1_0_M9--[#green]-|>postgresql_6_3_9
runtime_bundle_7_1_0_M9--[#orange]-|>quay_io_alfresco_alfresco_process_runtime_bundle_service_develop
rabbitmq_ha_1_38_1--[#orange]-|>rabbitmq_3_8_0_alpine
alfresco_adf_app_2_2_2--[#orange]-|>quay_io_alfresco_alfresco_adf_app_latest
activiti_cloud_query_7_1_0_M9--[#orange]-|>quay_io_alfresco_alfresco_process_query_service_develop
postgresql_6_3_9--[#orange]-|>docker_io_bitnami_postgresql_11_5_0_debian_9_r34
activiti_cloud_connector_7_1_0_M9--[#orange]-|>activiti_example_cloud_connector_7_1_0_M9

center footer Generated on 2022/06/15 22:09:11 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
