@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for alfresco-process-infrastructure:7.1.0-M4

'There are 11 referenced Helm Charts
artifact "postgresql:0.11.0\n====\n\tpostgresql\n====\n\t0.11.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: databus23\n====\n\tKeywords: postgresql\npostgres\ndatabase\nsql" as postgresql_0_11_0 #LightSteelBlue
artifact "alfresco-identity-service:1.1.2\n====\n\talfresco-identity-service\n====\n\t1.1.2\n====\n\thttps://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: alfresco\nkeycloak\nidentity-service" as alfresco_identity_service_1_1_2 #Chartreuse
artifact "alfresco-event-gateway:0.1.2\n====\n\talfresco-event-gateway\n====\n\t0.1.2\n====\n\thttps://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: alfresco\nevents\ngateway" as alfresco_event_gateway_0_1_2 #Chartreuse
artifact "postgresql:0.15.0\n====\n\tpostgresql\n====\n\t0.15.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: databus23\n====\n\tKeywords: postgresql\npostgres\ndatabase\nsql" as postgresql_0_15_0 #LightSteelBlue
artifact "common:1.1.21\n====\n\tcommon\n====\n\t1.1.21\n====\n\thttps://activiti.github.io/activiti-cloud-helm-charts\n====\n\tMaintainers: \n====\n\tKeywords: " as common_1_1_21 #DarkSeaGreen
artifact "alfresco-process-springboot-service:2.1.0\n====\n\talfresco-process-springboot-service\n====\n\t2.1.0\n====\n\thttps://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: alfresco\ncontent\ncontent services\nalfresco content services\nactiviti\nprocess\nalfresco activiti enterprise\njava\nspring boot\nmicroservice" as alfresco_process_springboot_service_2_1_0 #Coral
artifact "alfresco-process-infrastructure:7.1.0-M4\n====\n\talfresco-process-infrastructure\n====\n\t7.1.0-M4\n====\n\thttps://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: \n====\n\tKeywords: process\nprocess services\nalfresco\nalfresco process services\nactiviti\nactiviti enterprise\nalfresco activiti enterprise" as alfresco_process_infrastructure_7_1_0_M4 #GoldenRod
artifact "alfresco-infrastructure:5.1.1\n====\n\talfresco-infrastructure\n====\n\t5.1.1\n====\n\thttps://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: \n====\n\tKeywords: " as alfresco_infrastructure_5_1_1 #Cornsilk
artifact "keycloak:4.3.0\n====\n\tkeycloak\n====\n\t4.3.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: unguiculus, thomasdarimont\n====\n\tKeywords: sso\nidm\nopenid connect\nsaml\nkerberos\nldap" as keycloak_4_3_0 #LightBlue
artifact "nginx-ingress:0.14.0\n====\n\tnginx-ingress\n====\n\t0.14.0\n====\n\thttps://kubernetes-charts.storage.googleapis.com\n====\n\tMaintainers: jackzampolin, mgoodness, chancez\n====\n\tKeywords: ingress\nnginx" as nginx_ingress_0_14_0 #DarkSalmon
artifact "activemq:1.1.1\n====\n\tactivemq\n====\n\t1.1.1\n====\n\thttps://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: \n====\n\tKeywords: activemq\nmessage broker" as activemq_1_1_1 #LightBlue

'There are 8 referenced Docker Images
usecase "Image\n====\n\tDocker Hub\n====\n\tpostgres\n====\n\t11.3" as postgres_11_3 #Ivory
usecase "Image\n====\n\tDocker Hub\n====\n\tpostgres\n====\n\t9.6.2" as postgres_9_6_2 #Ivory
usecase "Image\n====\n\tDocker Hub\n====\n\tjboss/keycloak\n====\n\t4.8.3.Final" as jboss_keycloak_4_8_3_Final #LemonChiffon
usecase "Image\n====\n\tDocker Hub\n====\n\tk8s.gcr.io/defaultbackend\n====\n\t1.3" as k8s_gcr_io_defaultbackend_1_3 #DarkSeaGreen
usecase "Image\n====\n\tDocker Hub\n====\n\talfresco/alfresco-event-gateway\n====\n\t0.3-SNAPSHOT" as alfresco_alfresco_event_gateway_0_3_SNAPSHOT #LightSalmon
usecase "Image\n====\n\tquay.io\n====\n\tkubernetes-ingress-controller/nginx-ingress-controller:0.12.0\n====\n\t0.12.0" as quay_io_kubernetes_ingress_controller_nginx_ingress_controller_0_12_0 #LightSkyBlue
usecase "Image\n====\n\tDocker Hub\n====\n\tactiviti/example-runtime-bundle\n====\n\t7.0.0.SR1" as activiti_example_runtime_bundle_7_0_0_SR1 #LightSkyBlue
usecase "Image\n====\n\tDocker Hub\n====\n\talfresco/alfresco-activemq\n====\n\t5.15.8-java-8-oracle-centos-7-87b15e37ce8b" as alfresco_alfresco_activemq_5_15_8_java_8_oracle_centos_7_87b15e37ce8b #Khaki

'Chart Dependencies
alfresco_process_infrastructure_7_1_0_M4--[#green]-|>alfresco_infrastructure_5_1_1
alfresco_infrastructure_5_1_1--[#green]-|>nginx_ingress_0_14_0
alfresco_infrastructure_5_1_1--[#green]-|>activemq_1_1_1
alfresco_infrastructure_5_1_1--[#green]-|>alfresco_identity_service_1_1_2
alfresco_identity_service_1_1_2--[#green]-|>keycloak_4_3_0
keycloak_4_3_0--[#green]-|>postgresql_0_15_0
alfresco_infrastructure_5_1_1--[#green]-|>alfresco_event_gateway_0_1_2
alfresco_event_gateway_0_1_2--[#green]-|>activemq_1_1_1
alfresco_process_infrastructure_7_1_0_M4--[#green]-|>common_1_1_21
alfresco_process_infrastructure_7_1_0_M4--[#green]-|>postgresql_0_11_0
alfresco_process_infrastructure_7_1_0_M4--[#green]-|>alfresco_process_springboot_service_2_1_0
alfresco_process_springboot_service_2_1_0--[#green]-|>common_1_1_21
postgresql_0_11_0--[#orange]-|>postgres_9_6_2
alfresco_event_gateway_0_1_2--[#orange]-|>alfresco_alfresco_event_gateway_0_3_SNAPSHOT
postgresql_0_15_0--[#orange]-|>postgres_11_3
alfresco_process_springboot_service_2_1_0--[#orange]-|>activiti_example_runtime_bundle_7_0_0_SR1
keycloak_4_3_0--[#orange]-|>jboss_keycloak_4_8_3_Final
nginx_ingress_0_14_0--[#orange]-|>k8s_gcr_io_defaultbackend_1_3
nginx_ingress_0_14_0--[#orange]-|>quay_io_kubernetes_ingress_controller_nginx_ingress_controller_0_12_0
activemq_1_1_1--[#orange]-|>alfresco_alfresco_activemq_5_15_8_java_8_oracle_centos_7_87b15e37ce8b

center footer Generated on 2020/03/16 14:38:25 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
