@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for hello-world-app:0.2.1

'There are 4 referenced Helm Charts
artifact "hello-world-app:0.2.1\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/stable\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: \n\t\talfresco\n\t\tanaxes\n\t\thello\n\t\tworld" as hello_world_app_0_2_1 #Gainsboro
artifact "postgresql:0.11.0\n====\n\tType: application\n====\n\tRepo: https://charts.helm.sh/stable\n====\n\tMaintainers: databus23\n====\n\tKeywords: \n\t\tpostgresql\n\t\tpostgres\n\t\tdatabase\n\t\tsql" as postgresql_0_11_0 #LightSteelBlue
artifact "hello-world-service:0.2.1\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: \n\t\talfresco\n\t\tanaxes\n\t\thello\n\t\tworld" as hello_world_service_0_2_1 #Ivory
artifact "hello-world-ui:0.2\n====\n\tType: application\n====\n\tRepo: https://kubernetes-charts.alfresco.com/incubator\n====\n\tMaintainers: Alfresco\n====\n\tKeywords: \n\t\talfresco\n\t\tanaxes\n\t\thello\n\t\tworld" as hello_world_ui_0_2 #CadetBlue

'There are 3 referenced Docker Images
usecase "Image\n====\nquay.io\n====\nalfresco/anaxes-hello-world-service:0.1-SNAPSHOT\n====\n0.1-SNAPSHOT" as quay_io_alfresco_anaxes_hello_world_service_0_1_SNAPSHOT #DarkSalmon
usecase "Image\n====\nquay.io\n====\nalfresco/anaxes-hello-world-ui:0.1-SNAPSHOT\n====\n0.1-SNAPSHOT" as quay_io_alfresco_anaxes_hello_world_ui_0_1_SNAPSHOT #BurlyWood
usecase "Image\n====\nDocker Hub\n====\npostgres\n====\n10.1" as postgres_10_1 #Ivory

'Chart Dependencies
hello_world_app_0_2_1--[#green]-|>hello_world_ui_0_2
hello_world_app_0_2_1--[#green]-|>hello_world_service_0_2_1
hello_world_service_0_2_1--[#green]-|>postgresql_0_11_0
postgresql_0_11_0--[#orange]-|>postgres_10_1
hello_world_service_0_2_1--[#orange]-|>quay_io_alfresco_anaxes_hello_world_service_0_1_SNAPSHOT
hello_world_ui_0_2--[#orange]-|>quay_io_alfresco_anaxes_hello_world_ui_0_1_SNAPSHOT

center footer Generated on 2022/05/21 23:33:34 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
