@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for jenkins:1.7.0

'There is one referenced Helm Chart
artifact "jenkins:1.7.0\n====\n\tType: application\n====\n\tRepo: https://codecentric.github.io/helm-charts\n====\n\tMaintainers: unguiculus\n====\n\tKeywords: \n\t\tci\n\t\tcontinuous integration\n\t\tcontinuous delivery\n\t\tcontinuous deployment\n\t\tdevops\n\t\tautomation" as jenkins_1_7_0 #LightCoral

'There is one referenced Docker Image
usecase "Image\n====\ndocker.io\n====\njenkins/jenkins:2.222.3-alpine\n====\n2.222.3-alpine" as docker_io_jenkins_jenkins_2_222_3_alpine #Fuchsia

'Chart Dependencies
jenkins_1_7_0--[#orange]-|>docker_io_jenkins_jenkins_2_222_3_alpine

center footer Generated on 2022/06/15 22:14:13 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
