@startuml
skinparam linetype ortho
skinparam backgroundColor white
skinparam usecaseBorderColor black
skinparam usecaseArrowColor LightSlateGray
skinparam artifactBorderColor black
skinparam artifactArrowColor LightSlateGray

title Chart Map for keycloakx:1.6.0

'There is one referenced Helm Chart
artifact "keycloakx:1.6.0\n====\n\tType: application\n====\n\tRepo: https://codecentric.github.io/helm-charts\n====\n\tMaintainers: thomasdarimont\n====\n\tKeywords: \n\t\tsso\n\t\tidm\n\t\topenid connect\n\t\tsaml\n\t\tkerberos\n\t\toauth\n\t\tldap\n\t\tkeycloakx\n\t\tquarkus" as keycloakx_1_6_0 #Cornsilk

'There is one referenced Docker Image
usecase "Image\n====\nquay.io\n====\nkeycloak/keycloak:18.0.0\n====\n18.0.0" as quay_io_keycloak_keycloak_18_0_0 #CadetBlue

'Chart Dependencies
keycloakx_1_6_0--[#orange]-|>quay_io_keycloak_keycloak_18_0_0

center footer Generated on 2022/08/12 01:35:35 by com.melahn.util.helm.PlantUmlChartMapPrinter\nhttps://github.com/melahn/helm-chartmap
@enduml
