# This workflow will generate the example chart maps using helm-chart-generator
# and commit them using git.
#
# It can be run manually.
#
# Because thousands of chart map versions can be generated, this step can take a long 
# time.
name: Generate Examples
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Generate Example Chart Maps'
jobs:
  generate-examples:
    name: Generate Examples
    runs-on: ubuntu-latest
    # Permissions are needed to write updated artifacts and write the package
    permissions: 
      contents: write
      packages: write 
    steps:
      # Checkout (using V2)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    
      # Install helm
      - name: Helm tool installer
        uses: Azure/setup-helm@v1
      # Get the helm repos
      - name: Get helm repos
        run: |
          helm version
          helm repo add alfresco-incubator	https://kubernetes-charts.alfresco.com/incubator
          helm repo add alfresco-stable   	https://kubernetes-charts.alfresco.com/stable
          helm repo add stable            	https://charts.helm.sh/stable                
          helm repo add bitnami           	https://charts.bitnami.com/bitnami              
          helm repo add codecentric       	https://codecentric.github.io/helm-charts       
          helm repo add nuxeo             	https://chartmuseum.platform.dev.nuxeo.com/
          helm repo update
          helm repo list
          helm env
      # Install Graphviz so images can be generated from the generated PlantUML files
      - name: Install graphviz
        run: sudo apt-get install graphviz
      # Setup Java 11 with a settings.xml file setup for signatures
      # Note: maven caching is done here
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'maven'
      # Generate the helm-chartmap-generator jar file
      - name: Build helm-chartmap-generator 
        run: mvn -B package -DskipTests=true
      # Generate the chartmap examples starting with the simplest one to fail fast
      - name: Generate nuxeo charts and commit them to git
        run: | 
          cd ./docs/chartmuseum.platform.dev.nuxeo.com
          rm helm-chartmap.log
          rm index.html
          java -jar ../../target/helm-chartmap-generator-1.1.0-SNAPSHOT.jar -n 3 -f jpt -e ../../resource/example/example-env-spec.yaml -r nuxeo
          if [[ `git status --porcelain` ]]; then
              git config --global user.email "melahn@github"
              git config --global user.name "GitHub Action (generate-examples.yml)"
              git add .
              git commit -m "Update Nuxeo Example Chart Maps"
              git pull origin master
              git push origin master
          else
              echo no git changes found
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate alfresco-stable charts and commit them to git
        run: | 
          cd ./docs/kubernetes-charts.alfresco.com-stable
          rm helm-chartmap.log
          rm index.html
          java -jar ../../target/helm-chartmap-generator-1.1.0-SNAPSHOT.jar -n 3 -f jpt -e ../../resource/example/example-env-spec.yaml -r alfresco-stable
          if [[ `git status --porcelain` ]]; then
              git config --global user.email "melahn@github"
              git config --global user.name "GitHub Action (generate-examples.yml)"
              git add .
              git commit -m "Update Alfresco Stable Example Chart Maps"
              git pull origin master
              git push origin master
          else
              echo no git changes found
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate alfresco-incubator charts and commit them to git
        run: | 
          cd ./docs/kubernetes-charts.alfresco.com-incubator
          rm helm-chartmap.log
          rm index.html
          java -jar ../../target/helm-chartmap-generator-1.1.0-SNAPSHOT.jar -n 3 -f jpt -e ../../resource/example/example-env-spec.yaml -r alfresco-incubator
          if [[ `git status --porcelain` ]]; then
              git config --global user.email "melahn@github"
              git config --global user.name "GitHub Action (generate-examples.yml)"
              git add .
              git commit -m "Update Alfresco Incubator Example Chart Maps"
              git pull origin master
              git push origin master
          else
              echo no git changes found
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate codecentric charts and commit them to git
        run: | 
          cd ./docs/codecentric.github.io
          rm helm-chartmap.log
          rm index.html
          java -jar ../../target/helm-chartmap-generator-1.1.0-SNAPSHOT.jar -n 3 -f jpt -e ../../resource/example/example-env-spec.yaml -r codecentric
          if [[ `git status --porcelain` ]]; then
              git config --global user.email "melahn@github"
              git config --global user.name "GitHub Action (generate-examples.yml)"
              git add .
              git commit -m "Update Codecentric Example Chart Maps"
              git pull origin master
              git push origin master
          else
              echo no git changes found
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate bitnami charts and commit them to git
        run: | 
          cd ./docs/charts.bitnami.com
          rm helm-chartmap.log
          rm index.html
          java -jar ../../target/helm-chartmap-generator-1.1.0-SNAPSHOT.jar -n 3 -f jpt -e ../../resource/example/example-env-spec.yaml -r bitnami
          if [[ `git status --porcelain` ]]; then
              git config --global user.email "melahn@github"
              git config --global user.name "GitHub Action (generate-examples.yml)"
              git add .
              git commit -m "Update Bitnami Example Chart Maps"
              git pull origin master
              git push origin master
          else
              echo no git changes found
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate google stable charts and commit them to git
        run: | 
          cd ./docs/kubernetes-charts.storage.googleapis.com
          rm helm-chartmap.log
          rm index.html
          java -jar ../../target/helm-chartmap-generator-1.1.0-SNAPSHOT.jar -n 3 -f jpt -e ../../resource/example/example-env-spec.yaml -r stable
          if [[ `git status --porcelain` ]]; then
              git config --global user.email "melahn@github"
              git config --global user.name "GitHub Action (generate-examples.yml)"
              git add .
              git commit -m "Update Google Example Chart Maps"
              git pull origin master
              git push origin master
          else
              echo no git changes found
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
              
